# Импорты

In [2]:
import numpy as np
import math

# 2.2 Линейные операции над матрицами

In [2]:
A = np.matrix([[-2, 4, 0],
               [2, -5, 3],
               [2, 0, 6]])

B = np.matrix([[-2, -4, 6],
               [1, 0, 3],
               [1, 2, -5]])

C = 1 / 2 * A + 2 * B - np.eye(A.shape[0])
np.sum(C)

6.0

# 2.3 Линейные операции над векторами

In [3]:
# Проверка коллинеарности

# a, b = [np.fromstring(input(), sep=' ', dtype=np.int16) for _ in range(2)]

a, b = '1 2 3', '2 4 6'

a, b = [np.fromstring(i, sep=' ', dtype=np.int16) for i in [a, b]]

print(sum(np.cross(a, b)) == 0)

True


In [4]:
import numpy as np

# Отрезок AB имел координаты: A(3; −5; 2) и B(5; −3; 1). 
# Тогда нужно было использовать формулу для нахождения точек, 
# делящих отрезок на заданное отношение (на k = 3).

a = np.array([3, -5, 2], dtype=float)
b = np.array([5, -3, 1], dtype=float)
k = 3

step = (b - a) / k
print(*np.round(a + step, 2))
print(*np.round(a + step * 2, 2))

3.67 -4.33 1.67
4.33 -3.67 1.33


# 2.3 Нелинейные операции над матрицами

In [5]:
# Транспонирование

A = np.matrix([[2, 4, 6],
              [7, 5 ,1]])

A.T

matrix([[2, 7],
        [4, 5],
        [6, 1]])

In [6]:
# Умножение матриц

A = np.matrix([[1, 0, -1],
               [2, 4, 3]])

B = np.matrix([[1, 5, 7],
               [-1, 0, 1],
               [2, 3, 1]])

A @ B

matrix([[-1,  2,  6],
        [ 4, 19, 21]])

In [7]:
# В ответе запишите сумму всех элементов обеих матриц AB и BA.

A = np.matrix([3, 4, 2]).reshape(3, 1)
B = np.matrix([5, -2, 3])

display(A, B)

print(np.sum(A @ B) + np.sum(B @ A))

matrix([[3],
        [4],
        [2]])

matrix([[ 5, -2,  3]])

67


# 2.4 Линейная зависимость векторов. Проекции вектора, базис

# 2.4  Определители

In [8]:
# Что будет, если сначала в определителе порядка n поменять местами две строки, 
# потом умножить первый столбец на 3 и поменять его местами со вторым столбцом?

A = np.matrix([[2, 1, 1],
               [2, 2, 3],
               [2, 2, 1]])



B = A.copy()
B[[0, 1], :] = B[[1, 0], :] # если поменять местами две строки или два столбца, то определитель изменит знак

display(A, B)
print(np.linalg.det(A))
print(np.linalg.det(B))

B[:, 0] *= 3 # если умножить столбец или строку на число n, то определитель увеличится в n раз
display(B)
print(np.linalg.det(B))

B[:, [0, 1]] = B[:, [1, 0]]
display(B)
print(np.linalg.det(B))

# Значение определителя увеличится в 3 раз

matrix([[2, 1, 1],
        [2, 2, 3],
        [2, 2, 1]])

matrix([[2, 2, 3],
        [2, 1, 1],
        [2, 2, 1]])

-4.0
4.0


matrix([[6, 2, 3],
        [6, 1, 1],
        [6, 2, 1]])

12.0


matrix([[2, 6, 3],
        [1, 6, 1],
        [2, 6, 1]])

-12.0


In [9]:
# Линейная зависимость двух строк или двух столбцов = определитель равен 0

A = np.matrix([[2, 3, 4],
               [8, 12, 16],
               [56, 2, 21]])

# Первая и вторая строка линейно зависимы

print(np.round(np.linalg.det(A)))

0.0


In [10]:
# Найти x, при которых определитель будет равен 0

x = -6

A = np.matrix([[5, -3, x],
               [1, 1, -2],
               [2, x+2, -1]])


print(np.round(np.linalg.det(A)))

0.0


In [11]:
from sympy import symbols, Symbol, solve, simplify, Matrix

x = Symbol('x')

expr = 5 * 1 * (-1) + (-3) * (-2) * 2 + x * 1 * (x+2) - (x * 1 * 2 + 1 * (-3) * (-1) + (x+2) * (-2) * 5)

simplify_expr = simplify(expr)
print(simplify_expr)

result = solve(simplify_expr)
print(result)

x**2 + 10*x + 24
[-6, -4]


In [12]:
x = Symbol('x')
A = Matrix([[5, -3, x],
            [1, 1, -2],
            [2, x+2, -1]])
det = A.det()

print(solve(det))

[-6, -4]


In [13]:
print(expr.subs({x: -4}))
print(expr.subs({x: -6}))

0
0


# 2.5 Обратная матрица

In [14]:
# A^(-1) * A == A * A^(-1) = E

In [15]:
# Обратная матрица

A = np.matrix([[3, 5],
               [1, 2]])

print(np.round(np.linalg.det(A)))

E = np.eye(A.shape[0])



A_inv = np.linalg.solve(A, E)
A_inv

1.0


array([[ 2., -5.],
       [-1.,  3.]])

In [16]:
# Обратная матрица

A = np.matrix([[3, 1, -5],
               [1, 2, 4],
               [3, 2, -1]])

print(np.round(np.linalg.det(A)))

E = np.eye(A.shape[0])

A_inv = np.linalg.solve(A, E)
A_inv

3.0


array([[-3.33333333, -3.        ,  4.66666667],
       [ 4.33333333,  4.        , -5.66666667],
       [-1.33333333, -1.        ,  1.66666667]])

In [17]:
# Найти X
# A * X = Y

A = np.matrix([[3, 5],
               [1, 2]])

Y = np.matrix([[1, 2],
               [3, 4]])

X = np.linalg.solve(A, Y)
X

matrix([[-13., -16.],
        [  8.,  10.]])

In [18]:
E = np.eye(A.shape[0])
A_inv = np.linalg.solve(A, E)
display(A_inv)

X = A_inv @ Y
X

array([[ 2., -5.],
       [-1.,  3.]])

matrix([[-13., -16.],
        [  8.,  10.]])

In [19]:
# Найти элемент, расположенный в третьей строке и втором столбце обратной матрицы к матрице A

A = np.array([[0,0,1,1], [0,3,1,-7],[2,7,6,1],[1,2,2,1]])
E = np.eye(A.shape[0])

A_inv = np.linalg.solve(A, E)
display(A_inv)

A_inv[2, 1]

array([[-0.46666667,  0.2       , -0.86666667,  2.73333333],
       [-0.86666667, -0.2       ,  0.53333333, -1.06666667],
       [ 1.2       ,  0.2       , -0.2       ,  0.4       ],
       [-0.2       , -0.2       ,  0.2       , -0.4       ]])

0.2

In [20]:
A = np.array([[0,0,1,1], [0,3,1,-7],[2,7,6,1],[1,2,2,1]]) 
A_inv = np.linalg.inv(A)
display(A_inv)

A_inv[2, 1]

array([[-0.46666667,  0.2       , -0.86666667,  2.73333333],
       [-0.86666667, -0.2       ,  0.53333333, -1.06666667],
       [ 1.2       ,  0.2       , -0.2       ,  0.4       ],
       [-0.2       , -0.2       ,  0.2       , -0.4       ]])

0.2

In [21]:
# Решить матричное уравнение
# В ответе укажите сумму элементов матрицы-решения.
# A*X*B=Y

# A*X* * B*B_inv = Y*B_inv
# A * X * E = Y_2

# A * X = Y_2
# A_inv * A * X = A_inv * Y_2
# E * X = A_inv * Y_2
# X = A_inv * Y_2

A = np.array([[3, -1], 
              [5, -2]]) 

B = np.array([[5, 6], 
              [7, 8]])

Y = np.array([[14, 16], 
              [9, 10]])

# B_inv = np.linalg.solve(B, np.eye(B.shape[0]))
B_inv = np.linalg.inv(B)

Y_2 = Y @ B_inv

X = np.round(np.linalg.solve(A, Y_2))
display(X)

print(np.sum(X))

array([[1., 2.],
       [3., 4.]])

10.0


In [22]:
a = np.array([[3,-1], [5,-2]]) 
b = np.array([[14,16], [9,10]]) 
c = np.array([[5,6], [7,8]]) 
c_inv = np.linalg.inv(c)
b = np.dot(b, c_inv)

# A*x=B
a_inv = np.linalg.inv(a)
x = np.dot(a_inv, b)

print(x.sum())

10.000000000000018


In [23]:
# Найти ранг матрицы

A = np.array([[1, 1, 2, 3, -1], 
              [2, -1, 0, -4, -5], 
              [-1, -1, 0, -3, -2], 
              [6, 3, 4, 8, -3]]) 

rank = np.linalg.matrix_rank(A) 
rank

3

# 2.6 Задачи

In [24]:
# Исходные данные

A = np.matrix([[1,2,3], 
              [4,2,1], 
              [1,0,1]])

B = np.matrix([[1,2,1], 
              [1,-1,2], 
              [1,2,1]])

C = np.matrix([[2,2], 
               [1,4]]) 

D = np.matrix([[3,1],
               [2,1],
               [-1,2]])

G = np.matrix([[1,1,2,3],
               [4,2,1,3],
               [2,1,2,3],
               [1,2,5,4]])

In [25]:
# 1. Найти -ЗС.
# Укажите сумму элементов полученной матрицы.


Q = -3 * C
display(Q)

np.sum(Q)

matrix([[ -6,  -6],
        [ -3, -12]])

-27

In [26]:
# 2. Найти -A + 2B - 3Е.
# Укажите сумму элементов главной диагонали полученной матрицы.

# E = np.identity(B.shape[0])

Q = -A + 2 * B - 3 * np.eye(B.shape[0])
display(Q)

np.trace(Q)

matrix([[-2.,  2., -1.],
        [-2., -7.,  3.],
        [ 1.,  4., -2.]])

-11.0

In [27]:
# 3. Найти все возможные парные произведения матриц: A, B, С, D, G.

lst = [A, B, C, D, G]

d = {k: v for k, v in zip(range(len(lst)), 'A, B, C, D, G'.split(', '))}

for i in range(len(lst)):
    for j in range(len(lst)):
        if i != j:
            print(d[i], '*' ,d[j], '=',  lst[i].shape[1] == lst[j].shape[0])

print()

for i in range(len(lst)):
    for j in range(len(lst)):
        if i != j and lst[i].shape[1] == lst[j].shape[0]:
            print(d[i], '*' ,d[j], '=',  lst[i].shape[1] == lst[j].shape[0])

A * B = True
A * C = False
A * D = True
A * G = False
B * A = True
B * C = False
B * D = True
B * G = False
C * A = False
C * B = False
C * D = False
C * G = False
D * A = False
D * B = False
D * C = True
D * G = False
G * A = False
G * B = False
G * C = False
G * D = False

A * B = True
A * D = True
B * A = True
B * D = True
D * C = True


In [28]:
# Укажите сумму элементов, стоящих в первой строке и втором столбце, всех результирующих матриц, 
# полученных в результате парных произведений исходных матриц, которые существуют.

lst = [A, B, C, D, G]
total_arr = []

for i in range(len(lst)):
    for j in range(len(lst)):
        if i != j and lst[i].shape[1] == lst[j].shape[0]:
            Q = np.dot(lst[i], lst[j])
            display(Q)
            total_arr.append(Q[0, 1])

print(total_arr)
sum(total_arr)

matrix([[6, 6, 8],
        [7, 8, 9],
        [2, 4, 2]])

matrix([[ 4,  9],
        [15,  8],
        [ 2,  3]])

matrix([[10,  6,  6],
        [-1,  0,  4],
        [10,  6,  6]])

matrix([[ 6,  5],
        [-1,  4],
        [ 6,  5]])

matrix([[ 7, 10],
        [ 5,  8],
        [ 0,  6]])

[6, 9, 6, 5, 10]


36

In [29]:
# 4. Найти А_T.
# Укажите элемент результирующей матрицы, стоящий во второй строке и первом столбце.

A_T = np.transpose(A)
display(A_T)

A_T[1, 0]

matrix([[1, 4, 1],
        [2, 2, 0],
        [3, 1, 1]])

2

In [30]:
# 5. Найти D_T.
# Укажите элемент результирующей матрицы, стоящий во второй строке и первом столбце.

G_T = np.transpose(G)
display(G_T)

G_T[1, 0]

matrix([[1, 4, 2, 1],
        [1, 2, 1, 2],
        [2, 1, 2, 5],
        [3, 3, 3, 4]])

1

In [31]:
# 6. Найти det С.
# 7. Найти det А.
# 8. Найти det G

for i in [C, A, G]:
    print(np.round(np.linalg.det(i)))

6.0
-10.0
9.0


In [32]:
# 9. Найти А_inv.
# Укажите сумму элементов полученной матрицы
A_inv = np.linalg.inv(A)
display(A_inv)

A_inv = np.linalg.solve(A, np.identity(A.shape[0]))
display(A_inv)

np.sum(A_inv)

matrix([[-0.2,  0.2,  0.4],
        [ 0.3,  0.2, -1.1],
        [ 0.2, -0.2,  0.6]])

array([[-0.2,  0.2,  0.4],
       [ 0.3,  0.2, -1.1],
       [ 0.2, -0.2,  0.6]])

0.4

In [33]:
# 10. Найти A @ А_inv непосредственным перемножением матриц.
# Укажите сумму элементов полученной матрицы
Q = A @ A_inv
display(Q)

np.sum(Q)

matrix([[ 1.00000000e+00,  5.55111512e-17, -2.22044605e-16],
        [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -5.55111512e-17,  1.00000000e+00]])

3.0

# 3 Системы линейных алгебраических уравнений (СЛАУ)

In [34]:
# Добавление столбца в матрицу

A = np.matrix([[2, 2],
               [3, 3]])

B = np.matrix([[1],
               [1]])

np.c_[A, B]

matrix([[2, 2, 1],
        [3, 3, 1]])

In [35]:
# Сколько решений системы с тремя неизвестными?

A = np.matrix([[2, 3, -1],
               [1, 1, 1]])

np.linalg.matrix_rank(A)

# Бесконечное множество, так как ранг матрица не равен числу неизвестных

2

In [36]:
# Решить систему линейных алгебраических уравнений


A = np.array([[4, 2, -1], 
              [1, 2, 1], 
              [0, 1, -1]])

B = np.array([0, 1, -3])
np.linalg.solve(A, B)

array([ 1., -1.,  2.])

In [37]:
# Решить систему линейных алгебраических уравнений

A = np.array([[3, -6], 
              [1, -2]])

B = np.array([5, -4])

try:
    print(np.linalg.solve(A, B))
except np.linalg.LinAlgError as ex:
    print(ex)

[1.02081592e+17 5.10407958e+16]


In [38]:
import sympy as sp

x, y = sp.symbols('x y')

equations = [
    sp.Eq(3 * x - 6*y,  5),
    sp.Eq(    x - 2*y, -4)
    ]

print(sp.solve(equations))

[]


In [39]:
# Решить СЛАУ

A = np.array([[2, 3, 11,5], 
              [0, 0, 2, -2], 
              [3, 3, 9, 5], 
              [2,1,3,2]]) 

b = np.array([2, 4, -2,-3]) 

print(sum(np.linalg.solve(A, b)))

-2.0


In [40]:
A = np.array([[1, 4, -1], [0, 5, 4], [3, -2, 5]]) 
b = np.array([6, -20, -22]) 
print(sum(np.linalg.solve(A, b)))

-4.0


In [41]:
A = np.array([[4, -9, 5], [7, -4, 1], [3, 5, -4]]) 
b = np.array([1, 11, 5])

print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(np.c_[A, b]))

2
3


In [42]:
A = np.array([[1, 7, -3], [3, -5, 1], [1, 4, -2]]) 
b = np.array([0, 0, 0])

print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(np.c_[A, b]))

print(sum(np.linalg.solve(A, b)))

3
3
0.0


In [43]:
A = np.array([[3, -2, 1], [3, 3, -5], [6, 1, -4]]) 
b = np.array([0, 0, 0])

print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(np.c_[A, b]))

try:
    print(sum(np.linalg.solve(A, b)))

except np.linalg.LinAlgError as ex:
    print(ex)
    
# СЛАУ имеет бесконечное множество решений

2
2
Singular matrix


In [3]:
A = np.array([[-1,0,-1,-2,2],
              [2,-1,1,-2,2],
              [1,-2,0,-1,-1]])
b = np.array([2,1,2,1,1])

print(np.linalg.matrix_rank(A))
# print(np.linalg.matrix_rank(np.c_[A, b]))

try:
    print(sum(np.linalg.solve(A, b)))

except np.linalg.LinAlgError as ex:
    print(ex)

3
Last 2 dimensions of the array must be square


# Tail

In [2]:
non_zero = filter(None, [-2, -1, 0, 1, 2])
list(non_zero)

[-2, -1, 1, 2]