In [66]:
import math
import numpy as np

In [67]:
# Даны 2 вектора
# Найти 2 * a - 3 * b:
a = np.array([1, 0, 3])
b = np.array([0, 2, 1])
2 * a - 3 * b

array([ 2, -6,  3])

In [68]:
# Пятитомное собрание сочинений расположено на полке в случайном порядке. 
# Какова вероятность того, что книги стоят слева направо в порядке нумерации томов (от 1 до 5)?

1 / np.prod(range(1, 6))

0.008333333333333333

In [69]:
# В пирамиде 5 винтовок, три из которых снабжены оптическим прицелом.

# Вероятность того, что стрелок поразит мишень при выстреле из винтовки с оптическим прицелом, равна 0,95;
# для винтовки без оптического прицела эта вероятность равна 0,7.
# Найти вероятность того, что мишень будет поражена, если стрелок производит один выстрел из наудачу взятой винтовки.

Pa = 0.95
Pb = 0.7

a = 3 / 5
b = 2 / 5

Pa * a + Pb * b

0.8499999999999999

In [70]:
# Измерение некой величины дало результаты:
# 1, 5, 2, 7, 1, 9, 3, 8, 5, 9
# Рассчитайте стандартное (среднеквадратическое) отклонение данных выборочных значений.
# Не забудьте о необходимости нормировать дисперсию и стандартное отклонение для выборочных (экспериментальных, а не теоретических) значений на степень свободы.

a = np.array([1, 5, 2, 7, 1, 9, 3, 8, 5, 9])
n = len(a)

Sx = np.sqrt(sum(np.square(a - a.mean())) / (n - 1))
print(Sx)

Sx = np.std(a, ddof=1)
print(Sx)

3.1622776601683795
3.1622776601683795


In [71]:
# На склад поступило 2 партии изделий:
# первая – 4000 штук,
# вторая – 6000 штук.
# Средний процент нестандартных изделий в первой партии составляет 20%, а во второй – 10%. 
# Наудачу взятое со склада изделие оказалось стандартным. 
# Найти вероятность того, что оно из первой партии.

P1 = 4000 / (4000 + 6000)
P2 = 6000 / (4000 + 6000)

P1_pos = 0.8
P2_pos = 0.9

P_pos = P1_pos * P1 + P2_pos * P2 # - полная вероятность того, что деталь окажется стандартной без учета принадлежности к конкретной партии
print(P_pos)

P_pos_1 = P1_pos * P1 / P_pos
print(P_pos_1)

0.8600000000000001
0.372093023255814


# 2.2 Математические операции

In [72]:
# Даны длины 3 сторон треугольника (каждая с новой строки).

a, b, c = 5, 5, 5

P = a + b + c # Периметр
p = P / 2     # Полупериметр

S = (p * (p - a) * (p - b) * (p - c)) ** 0.5 # Формула Герона

print(P)
print(S)

15
10.825317547305483


In [73]:
# Даны длины 2 диагоналей ромба (каждая с новой строки).
# Значения могут быть дробными.

# Найдите площадь ромба S. В качестве ответа запишите (каждое с новой строки) следующие значения:
# S, приведённое к целочисленному типу
# S, округлённое до 1 знака после запятой с помощью функции  round()
# S, точное значение без округления

a, b = 3.5, 6.5



S = a * b / 2

print(int(S))
print(round(S, 1))
print(S)

11
11.4
11.375


In [74]:
# Нарисован правильный шестиугольник со стороной a.

# К 5 сторонам этого шестиугольника снаружи дорисовали по правильному треугольнику.

a = 85

S3 = ((a * a) * 3 ** 0.5) / 4
S6 = (3 * 3 ** 0.5 * (a * a)) / 2

S = S6 + 5 * S3
print(round(S))

34414


In [75]:
# На плоскости нарисован правильный шестиугольник с длиной стороны a.

# У 3 сторон шестиугольника нарисовали по квадрату с длиной стороны, равной стороне шестиугольника.

# Оставшиеся 3 стороны разделили пополам, после чего нарисовали по равностороннему треугольнику, касающемуся каждого из получившихся половинных отрезков.

a = 8

b = a / 2
S3 = ((b * b) * 3 ** 0.5) / 4
S4 = a * a
S6 = (3 * 3 ** 0.5 * (a * a)) / 2

S = S6 + 3 * S4 + 6 * S3
print(round(S))

400


In [76]:
a = 2


S = 3 * a ** 2 * (5 * (5 + 2 * 5 ** 0.5)) ** 0.5
V = a ** 3 / 4 * (15 + 7 * 5 ** 0.5)

print(round(S, 2))
print(round(V, 2))

82.58
61.3


In [77]:
i = 0
while i <= 10:
    i = i + 1
    if i > 7:
        i = i + 2

In [78]:
i

13

# Предел функции

In [79]:
from math import exp

def f(x):
    return (exp(x) - 1) / x

x0 = 0

dx_list = [0.1, 0.01, 0.001, 0.001, 0.0001]

for dx in dx_list:
    print(f(x0 + dx))

print()

for dx in dx_list:
    print(f(x0 - dx))

# Функция при x = 0 стремится к 1

1.0517091807564771
1.005016708416795
1.0005001667083846
1.0005001667083846
1.000050001667141

0.9516258196404048
0.9950166250831893
0.9995001666249781
0.9995001666249781
0.9999500016666385


In [80]:
# Предел функции f(x)=2arctg(x) от +оо

from math import atan, inf
def f(x):
    return 2 * atan(x)
    
x0 = inf
    
lim = round(f(x0), 3)
print (lim)

3.142


In [81]:
# Предел функции f(x)=2arctg(x) от +оо

import sympy as sym

x = sym.symbols('x')
lim = sym.limit(2 * sym.atan(x), x, sym.oo)
print(round(float(lim), 3))

3.142


# Производная функции

In [82]:
# Скорость приращения (роста) функции
# Отношение изменения значения функции к изменению аргумента функции

def f(x):
    return x**2

# При значении аргумента x0 = 3
x0 = 3

dx_list = [1, 0.1, 0.01, 0.001]

for dx in dx_list:
    print((f(x0 + dx) - f(x0)) / dx)

# Функция стремится к 6

7.0
6.100000000000012
6.009999999999849
6.000999999999479


In [83]:
n = 1242

def kaprekar(n):
    for i in range(8):
        print(n)
        a = sorted(str(n), key=lambda x: int(x))
        a = int(''.join(a))
        b = sorted(str(n), key=lambda x: int(x), reverse=True)
        b = int(''.join(b))
        n = b - a
        print(n)
kaprekar(n)

1242
2997
2997
7173
7173
6354
6354
3087
3087
8352
8352
6174
6174
6174
6174
6174


In [84]:
n = 1242

def kaprekar(n):
    while n != 6174:
        print(n)
        a = sorted(str(n), key=lambda x: int(x))
        a = int(''.join(a))
        b = sorted(str(n), key=lambda x: int(x), reverse=True)
        b = int(''.join(b))
        n = b - a
        print(n)
kaprekar(n)

1242
2997
2997
7173
7173
6354
6354
3087
3087
8352
8352
6174


# 6. Numpy

In [85]:
import numpy as np

In [86]:
x = np.array([(1, 2, 6),
              (3, 4, 1), 
              (7, 8, 2)], 
              dtype=[('a', '<i4'),('b', '<i4'), ('g', '<i4')])
x['g']

array([6, 1, 2])

In [87]:
np.array(np.asmatrix('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [88]:
# Создайте и сохраните:

# в переменную V1 Numpy вектор из этих чисел в том же порядке
# в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
# в переменную V3 Numpy вектор из этих чисел в обратном порядке
# в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
# в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход

s = '2 3 4 5 6 7'
s = s.split()
V1 = np.array(s).astype(float)
V2 = V1[-2:-1]
V3 = V1[::-1]
V4 = V1[::3]
V5 = np.arange(len(V1))
print(V1, V2, V3, V4, V5, sep='\n')

[2. 3. 4. 5. 6. 7.]
[6.]
[7. 6. 5. 4. 3. 2.]
[2. 5.]
[0 1 2 3 4 5]


In [89]:
# Даны 3 переменные: A1, A2, A3. 
# Каждая содержит вектор с 2 координатами соответствующей вершины треугольника.

# Найдите площадь треугольника по формуле Герона .

A1 = np.array((-1, 1))
A2 = np.array((2, 5))
A3 = np.array((5, -3))

print(abs(np.cross(A1 - A2, A1 - A3)) / 2)

18.0


In [90]:
# Переменная M1 содержит Numpy матрицу.

# Произведите операции последовательно:

# 1. Замените значения в предпоследней строке на значения по формуле:
# sin(x⋅π / 6​), где x - старое значение

# 2. Замените значения в предпоследнем столбце на значения по формуле:
# e**x

M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

M1[-2] = np.sin(M1[-2] * np.pi / 6)
M1[:, -2] = np.exp(M1[:, -2])

M2 = np.array(M1)
M2

array([[1.00000000e+00, 2.00000000e+00, 2.00855369e+01, 0.00000000e+00],
       [4.00000000e+00, 5.00000000e+00, 4.03428793e+02, 0.00000000e+00],
       [0.00000000e+00, 5.00000000e-01, 1.64872127e+00, 1.22464680e-16],
       [7.00000000e+00, 8.00000000e+00, 8.10308393e+03, 0.00000000e+00]])

In [91]:
Z = np.arange(6).reshape((2, 3))
print(Z)
Z[Z > 3]

[[0 1 2]
 [3 4 5]]


array([4, 5])

In [92]:
Z.min()
Z.max()

5

In [93]:
np.random.rand(2*5).reshape(2, 5)

array([[0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224],
       [0.52475643, 0.43194502, 0.29122914, 0.61185289, 0.13949386]])

In [94]:
# Найдите среднее значение для каждого из столбцов.

np.random.seed(42)

n = 3
m= 4

M = np.random.rand(n * m).reshape(n, m)

print(M)
print()
print(np.mean(M, axis=0))

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

[0.37722459 0.60492713 0.27022068 0.81158149]


In [95]:
# Считайте 2 числа: n, m.

# Создайте матрицу размера n*m такую что:

# На границе матрицы будут стоять 1
# Внутри матрицы будут стоять 0
# Сохраните матрицу в переменную Z.

n = 5
m = 7

Z = np.ones((n, m))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [96]:
# Имеется матрица Z
# Добавьте вокруг имеющихся значений матрицы "забор" из 0.

Z = np.array([
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
Z = np.pad(Z, 1, mode='constant', constant_values=0)
Z

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

In [97]:
print(np.nan == np.nan)
print(0 * np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)
print(np.isnan(np.nan))
print(np.nan in set([np.nan]))

False
nan
False
nan
False
True
True


In [107]:
# Создайте диагональную матрицу размера n*n. На главной диагонали должны быть числа от 1 до n.
# Сохраните матрицу в переменную Z.

n = 5

Z = np.diagflat(np.arange(1, n + 1))
Z

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [108]:
n = 5
Z = np.diag(np.arange(1, n + 1))
Z

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [110]:
n = 5
Z = np.eye(n, dtype=int)
Z[Z != 0] = np.arange(1, n + 1)
Z

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [111]:
n = 5

Z = np.diagflat(np.arange(1, n + 1), -1)
Z

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [115]:
# Считайте 2 числа:

# x - сдвиг для единственной ненулевой диагонали в матрице.
# k - верхняя граница для интервала чисел на диагонали (т.е. если k = 5, то на диагонали будут стоять числа 1, 2, 3, 4 и 5)

x = -1
k = 3

Z = np.diagflat(np.arange(1, k + 1), x)
Z

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [120]:
# Считайте 2 числа: n, m.
# Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.
# 0 - "чёрное"
# 1 - "белое"

n, m = 5, 5

Z = np.ones((n, m))
Z[::2, ::2] = 0
Z[1::2, 1::2] = 0
Z

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

In [127]:
Z = np.tile([[0.,1.],[1.,0.]], (1 + n // 2,1 + m // 2) )[:n, :m]
Z

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])