In [ ]:
# Среднеквадратическая ошибка (MSE).

# Даны матрица с наблюдениями, вектор с ответами и вектор с весовыми коэффициентами и записаны в переменные X, y и w соответственно. 
# Рассчитайте среднеквадратическую ошибку по формуле

# loss = ((y - X @ w)**2).mean(axis=0)

In [1]:
import numpy as np

In [25]:
# необходимо вычислить коэффициенты w модели: a(x,w)=w0 + w1 * x

np.random.seed(0) # псевдослучайные числа образуют одну и ту же последовательность (при каждом запуске)
x = np.arange(-1.0, 1.0, 0.1) # аргумент [-1; 1] с шагом 0,1


model_a = lambda xx, ww: (ww[0] + ww[1] * xx) # модель
Y = -5.2 + 0.7 * x + np.random.normal(0, 0.1, len(x)) # вектор целевых значений

# здесь продолжайте программу
X = x.reshape(len(x), 1)
X = np.c_[np.ones(X.shape[0]), X]
X

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 1.00000000e+00, -9.00000000e-01],
       [ 1.00000000e+00, -8.00000000e-01],
       [ 1.00000000e+00, -7.00000000e-01],
       [ 1.00000000e+00, -6.00000000e-01],
       [ 1.00000000e+00, -5.00000000e-01],
       [ 1.00000000e+00, -4.00000000e-01],
       [ 1.00000000e+00, -3.00000000e-01],
       [ 1.00000000e+00, -2.00000000e-01],
       [ 1.00000000e+00, -1.00000000e-01],
       [ 1.00000000e+00, -2.22044605e-16],
       [ 1.00000000e+00,  1.00000000e-01],
       [ 1.00000000e+00,  2.00000000e-01],
       [ 1.00000000e+00,  3.00000000e-01],
       [ 1.00000000e+00,  4.00000000e-01],
       [ 1.00000000e+00,  5.00000000e-01],
       [ 1.00000000e+00,  6.00000000e-01],
       [ 1.00000000e+00,  7.00000000e-01],
       [ 1.00000000e+00,  8.00000000e-01],
       [ 1.00000000e+00,  9.00000000e-01]])

In [26]:
X_T = np.transpose(X)
X_T

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [-1.00000000e+00, -9.00000000e-01, -8.00000000e-01,
        -7.00000000e-01, -6.00000000e-01, -5.00000000e-01,
        -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
        -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
         2.00000000e-01,  3.00000000e-01,  4.00000000e-01,
         5.00000000e-01,  6.00000000e-01,  7.00000000e-01,
         8.00000000e-01,  9.00000000e-01]])

In [30]:
X_T_X = X_T @ X
X_T_X

array([[20. , -1. ],
       [-1. ,  6.7]])

In [31]:
X_T_X_inv = np.linalg.inv(X_T_X)
X_T_X_inv

array([[0.05037594, 0.0075188 ],
       [0.0075188 , 0.15037594]])

In [32]:
X_T_y = X_T @ Y
X_T_y

array([-103.56133081,    9.43503749])

In [33]:
X_T_y @ X_T_X_inv

array([-5.14605924,  0.64014601])