In [34]:
import pandas as pd
import numpy as np

In [35]:
my_dict = {'A':[1,1,0],
        'B':[2,0,1],
        'C':[0,1,5],
        'D':[4,1,None]}

In [36]:
df = pd.DataFrame.from_dict(data=my_dict, orient='index', columns=['P1', 'P2', 'P3'])

In [37]:
df.head()

P1  P2   P3
A   1   1  0.0
B   2   0  1.0
C   0   1  5.0
D   4   1  NaN

In [38]:
df['P3'].fillna(np.mean(df['P3'].dropna()))

A    0.0
B    1.0
C    5.0
D    2.0
Name: P3, dtype: float64

In [39]:
df['P3'].fillna(np.median(df['P3'].dropna()))

A    0.0
B    1.0
C    5.0
D    1.0
Name: P3, dtype: float64

Метрики

In [40]:
P1 = [0, 1, 2]
P2 = [2, 1, 0]
evklid_metric = sum([((x - y)**2) for x, y in zip(P1, P2)])**0.5
manh_metric = sum([abs(x - y) for x, y in zip(P1, P2)])
max_metric = max([abs(x - y) for x, y in zip(P1, P2)])
print(f'Метрика Евклида: {evklid_metric}\nМетрика Манхэттен: {manh_metric}\nМакс-метрика: {max_metric}')

Метрика Евклида: 2.8284271247461903
Метрика Манхэттен: 4
Макс-метрика: 2


Нормализация

In [41]:
P = (1,0,5,2,2)
min_max_normalization = [(x - min(P)) / (max(P) - min(P)) for x in P]
print(min_max_normalization)

[0.2, 0.0, 1.0, 0.4, 0.4]


In [42]:
P = [1,0,5,2,2]
n = ((np.array(P) - min(P))/(max(P) - min(P)))
print(n)

[0.2 0.  1.  0.4 0.4]


In [43]:
from sklearn.preprocessing import MinMaxScaler

a = np.array([1, 0, 5, 2, 2]).reshape(-1, 1)
scaler = MinMaxScaler()
scaler.fit_transform(a)

array([[0.2],
       [0. ],
       [1. ],
       [0.4],
       [0.4]])

In [44]:
# P = (1,0,5,2,2)
# P_mean = np.mean(P)
# P_n = len(P)
# P_std = (sum([((x - P_mean)**2) for x in P]) / P_n) ** 0.5
# min_std_normalization = [(x - P_mean) / P_std for x in P]
# min_std_normalization

In [45]:
P = (1,0,5,2,2)
n = (np.array(P) - np.mean(P)) / np.std(P)
n

array([-0.5976143 , -1.19522861,  1.79284291,  0.        ,  0.        ])

In [46]:
from sklearn.preprocessing import StandardScaler

a = np.array([1, 0, 5, 2, 2]).reshape(-1, 1)
scaler = StandardScaler()
scaler.fit_transform(a)

array([[-0.5976143 ],
       [-1.19522861],
       [ 1.79284291],
       [ 0.        ],
       [ 0.        ]])

Заполнение пропущенного значения по метрике Манхэттен 

In [47]:
import pandas as pd
from sklearn.metrics.pairwise import manhattan_distances

my_dict = {'Vasia': [5, 5, 5, 3],
           'Petia': [5, 3, 4, 4],
           'Masha': [2, 5, 3, 5],
           'Sasha': [3, 4, 4, None]}

df = pd.DataFrame.from_dict(data=my_dict, orient='index', columns=['Silence', 'Titanic', 'Matrix', 'Harry'])

md = manhattan_distances(df.iloc[0:3, 0:3], [df.iloc[3, 0:3]]).reshape(3)
norm_mul = 1 / ((1 / md)).sum()
sim = ((df.iloc[0:3, 3]/md)).sum()
print(norm_mul*sim)

4.090909090909092


In [48]:
df

Silence  Titanic  Matrix  Harry
Vasia        5        5       5    3.0
Petia        5        3       4    4.0
Masha        2        5       3    5.0
Sasha        3        4       4    NaN

In [49]:
df.loc[['Vasia'],['Silence', 'Titanic',	'Matrix']]

Silence  Titanic  Matrix
Vasia        5        5       5

In [50]:
a = np.abs(df.loc['Vasia',['Silence', 'Titanic', 'Matrix']] - df.loc[['Sasha'],['Silence', 'Titanic', 'Matrix']]).sum(axis=1).sum()
b = np.abs(df.loc['Petia',['Silence', 'Titanic', 'Matrix']] - df.loc[['Sasha'],['Silence', 'Titanic', 'Matrix']]).sum(axis=1).sum()
c = np.abs(df.loc['Masha',['Silence', 'Titanic', 'Matrix']] - df.loc[['Sasha'],['Silence', 'Titanic', 'Matrix']]).sum(axis=1).sum()
print(a,b,c)

(1 / ((1 / a) + (1 / b) + (1/c))) * \
((df.loc['Vasia','Harry'] / a) + \
(df.loc['Petia','Harry'] / b) + \
(df.loc['Masha','Harry'] / c))

4.0 3.0 3.0


4.090909090909092

In [51]:
A = [1,0,1,0,1,0]
C = [1,1,0,1,1,0]
evklid_metric = sum([(x-y)**2 for x, y in zip(A,C)])**0.5
evklid_metric

1.7320508075688772

In [52]:
from scipy.spatial.distance import euclidean

A = (1, 0, 1, 0, 1, 0)
C = (1, 1, 0, 1, 1, 0)

print(round(euclidean(A, C), 2))

1.73


In [53]:
q_25, q_75 = 2, 4
p = [8, -1.5, 7.5, 0, 3, 6.5, 0.5]

p_min = q_25 - 1.5 * (q_75 - q_25)
p_max = q_75 + 1.5 * (q_75 - q_25)

p = filter(lambda x: x < p_min or x > p_max, p)
print(list(p))

[8, -1.5, 7.5]


In [54]:
mean, std, median, n = 10, 1.1, 9, 10

P = [13.5, 14, 7, 6, 6.5, 13]

(mean - median) <= 3*std / np.sqrt(n)

for i in P:
    if (mean - 3*std) < i < (mean + 3*std):
        print(i, end=' ')
print()

def is_outliers(P) -> list:
    if (mean - median) <= 3*std / np.sqrt(n):
        return list(filter(lambda x: (mean - 3*std) < x < (mean + 3*std), P))
    list(filter(lambda x: (mean - 5*std) < x < (mean + 5*std), P))

result = is_outliers(P)
print(*result)

7 13 
7 13


In [55]:
df = pd.DataFrame.from_dict({'A': [1, 1, 0], 'B': [0, 2, -1], 'C': [2, 3, 1], 'D': [1, 0, 4]}, orient='index', columns=['P1', 'P2', 'P3'])
df

P1  P2  P3
A   1   1   0
B   0   2  -1
C   2   3   1
D   1   0   4

In [56]:
for i in df.index:
    print(list(df.loc[i]))
    globals()['x_' + str(i)] = list(df.loc[i])

[1, 1, 0]
[0, 2, -1]
[2, 3, 1]
[1, 0, 4]


In [57]:
def manhet(list1, list2, list3, list4):
    s = 0
    for a, b, c, d in zip(list1, list2, list3, list4):
        s += abs(a - b) + abs(a - c) + abs(a - d)
    return s

In [58]:
print('A:', manhet(x_A, x_B, x_C, x_D))
print('B:', manhet(x_B, x_C, x_D, x_A))
print('C:', manhet(x_C, x_D, x_A, x_B))
print('D:', manhet(x_D, x_A, x_B, x_C))

A: 12
B: 16
C: 16
D: 20


In [59]:
data = np.array([[1, 1, 0], [0, 2, -1], [2, 3, 1], [1, 0, 4]])
df = pd.DataFrame(data, columns=('P1', 'P2', 'P3'), index=('A', 'B', 'C', 'D'))
metric_dict = {}
for idx, row in df.iterrows():
    res = (abs(df - df.loc[idx]).sum()).sum()
    metric_dict[idx] = res
k = sorted(metric_dict, key=metric_dict.__getitem__)[-1]
print(k, metric_dict[k])

D 20


In [60]:
a = [0, 3, 4, 4, 1] 
b = [3, 0, 1 ,2, 5]
c = [4, 1, 0, 3, 3]
d = [3, 2, 3, 0, 4]
e = [1, 5, 3, 4, 0]

def dist(a, b):
    return sum(np.abs(np.array(a) - np.array(b)))**0.5 

print('a - b:', dist(a, b))
print('a - c:', dist(a, c))
print('a - d:', dist(a, d))
print('a - e:', dist(a, e))

a - b: 3.872983346207417
a - c: 3.605551275463989
a - d: 3.4641016151377544
a - e: 2.23606797749979


Набор объектов A,B,C,D,E,F,G планируется разбить на 3 кластера. Для этого был применен графовый алгоритм и было построено остовное дерево минимального веса, состоящее из ребер AE, BD, CD, DF, ED, EG. Длины ребер соответственно равны 1, 2, 4, 1, 3, 2. Какие объекты попадут в один кластер с объектом A?

In [61]:
import networkx as nx

G = nx.Graph() # Создаем граф и добавляем ребра
edges = [("A", "E", 1), ("B", "D", 2), ("C", "D", 4), ("D", "F", 1), ("E", "D", 3), ("E", "G", 2)]
G.add_weighted_edges_from(edges)

G.remove_edge("C", "D")
G.remove_edge("E", "D")

cluster_with_A = list(nx.node_connected_component(G, "A"))
cluster_with_A


['G', 'E', 'A']

In [62]:
features = np.array([[1, 1, 0], [0, 2, -1], [2, 3, 1], [1, 0, 4]])
print(features.mean(axis=0))

[1.  1.5 1. ]


Какие объекты попадают в окружность с центром (1,2) и радиусом 2,5   (используется max-метрика)?

In [63]:
#инициализация исходных данных
data = pd.DataFrame({'Object':['A','B','C','D','E'],'P1':[4,3,1,-1,0],'P2':[2,2,-1,1,4]})
data

Object  P1  P2
0      A   4   2
1      B   3   2
2      C   1  -1
3      D  -1   1
4      E   0   4

In [64]:
data['R'] = data[['P1','P2']].apply(lambda x: max(abs(x[0]-1),abs(x[1]-2)),axis=1)
data['isOk'] = data['R'] < 2.5
data

C:\Users\kuche\AppData\Local\Temp\ipykernel_18448\4051848404.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data['R']=data[['P1','P2']].apply(lambda x: max(abs(x[0]-1),abs(x[1]-2)),axis=1)


Object  P1  P2  R   isOk
0      A   4   2  3  False
1      B   3   2  2   True
2      C   1  -1  3  False
3      D  -1   1  2   True
4      E   0   4  2   True

In [65]:
#найдем какие точки ближе к (2,3), а какие к (1,1)
data.drop(['R','isOk'], axis=1, inplace=True)
data['K'] = data[['P1','P2']].apply(lambda x: 1 if (abs(x[0]-2)+abs(x[1]-3))<=(abs(x[0]-1)+abs(x[1]-1)) else 2,axis=1)
data

C:\Users\kuche\AppData\Local\Temp\ipykernel_18448\3204260063.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data['K'] = data[['P1','P2']].apply(lambda x: 1 if (abs(x[0]-2)+abs(x[1]-3))<=(abs(x[0]-1)+abs(x[1]-1)) else 2,axis=1)


Object  P1  P2  K
0      A   4   2  1
1      B   3   2  1
2      C   1  -1  2
3      D  -1   1  2
4      E   0   4  1

In [82]:
df = pd.DataFrame(np.array([[4,2],[3,2],[1,-1],[-1,1],[0,4]]),
                   columns=['P1', 'P2'], index=['A', 'B', 'C', 'D', 'E'])
df.index[((df.P1 - 1).abs() <= 2.5) & ((df.P2 - 2).abs() <= 2.5)]

Index(['B', 'D', 'E'], dtype='object')

In [83]:
df

P1  P2
A   4   2
B   3   2
C   1  -1
D  -1   1
E   0   4