In [1]:
import numpy as np

In [2]:
print(np.linspace(-5, 5, 10))

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [3]:
# a, b = map(int, input().split())
a, b = 2, 9
arr = np.array(list(i for i in range(a, b + 1) if i % 3 == 0))
print(arr)
arr = np.arange(a, b + 1)
arr = arr[arr % 3 == 0]
print(arr)

[3 6 9]
[3 6 9]


In [4]:
np.random.seed(32)
# n = int(input())
n = 6
arr = np.random.rand(n)
arr

array([0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ,
       0.81620514])

In [5]:
n = 3
arr = []
for i in range(0, n + 100): 
    if i > 1: 
        for j in range(2, i):
            if(i % j) == 0: 
                break 
        else:
            if len(arr) < n:
                arr.append(i)
print(arr)

[2, 3, 5]


In [6]:
n = 10
i = 2
arr = []
while len(arr) < n:
    for j in range(2, i):
        if(i % j) == 0: 
                break
    else:
         arr.append(i)
    i += 1
print(arr)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [7]:
# a, b = map(float, input().split())
a, b = 0.22, 2.0

np.round(np.arange(-1*a, a+0.001, b), 1)

array([-0.2])

In [8]:
b = 5
arr = np.linspace(0, np.pi, b)
arr

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [9]:
import numpy as np
arr=np.array([1, 2, '3', {'key1':66}])

print(arr.dtype)
print(arr.size)
print(arr.shape)

object
4
(4,)


In [10]:
# 3, 4, 2
arr = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],

                [[9, 10], [11, 12], [13, 14], [15, 16]],
                
                [[17, 18], [19, 20], [21, 22], [23, 24]]])
arr.shape

(3, 4, 2)

In [11]:
arr = np.empty([256, 256, 3])
arr.shape

(256, 256, 3)

In [12]:
arr1, arr2, arr3 = np.array_split(arr, 3, axis=2)
print(arr1.shape, arr2.shape, arr3.shape)

(256, 256, 1) (256, 256, 1) (256, 256, 1)


In [13]:
arr1 = np.squeeze(arr1)
arr2 = np.squeeze(arr2)
arr3 = np.squeeze(arr3)

arr1 = np.expand_dims(arr1, axis=0)
arr2 = np.expand_dims(arr2, axis=0)
arr3 = np.expand_dims(arr3, axis=0)

np.concatenate([arr1, arr2, arr3]).shape

(3, 256, 256)

# 1.5 Добавление и удаление элементов.

In [14]:
data = np.empty([1000, 28, 28])
arr1 = np.empty([50, 28, 28])
arr2 = np.empty([28, 28])

print(f'Размер data: {data.shape}')
print(f'Размер arr1: {arr1.shape}')
print(f'Размер arr2: {arr2.shape}')

Размер data: (1000, 28, 28)
Размер arr1: (50, 28, 28)
Размер arr2: (28, 28)


In [15]:
# Добавление элементов

new_data1 = np.append(data, arr1) # - одномерный массив
new_data2 = np.append(data, arr1, axis=0) # - многомерный, объединенрие по нулевой оси
new_data3 = np.append(arr1, arr1, axis=2) # - многомерный, объединенрие по второй оси
new_data4 = np.append(data, arr2[np.newaxis], axis=0) # - добавление одного элемента с предварительным добавлением оси

print(f'Размер new_data1: {new_data1.shape}')
print(f'Размер new_data2: {new_data2.shape}')
print(f'Размер new_data3: {new_data3.shape}')
print(f'Размер new_data4: {new_data4.shape}')

Размер new_data1: (823200,)
Размер new_data2: (1050, 28, 28)
Размер new_data3: (50, 28, 56)
Размер new_data4: (1001, 28, 28)


In [16]:
# Удаление элементов по индексу

print(new_data4.shape)

new_data4 = np.delete(new_data4, 1000, axis=0)

print(new_data4.shape)

(1001, 28, 28)
(1000, 28, 28)


In [17]:
# В программе созданы два массива с картинками 28 на 28 пикселей. 
# Массивы записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28), а массив arr_2 имеет размер (5, 28, 28). 
# К картинкам из arr_1 добавьте картинки из arr_2.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28])
arr_2 = np.empty([5, 28, 28])

new_arr = np.append(arr_1, arr_2, axis=0)

new_arr.shape

(15, 28, 28)

In [18]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28), 10 картинок 28 на 28 пикселей. 
# Массив arr_2 имеет размер (28, 28), содержит одну картинку. 
# К картинкам из arr_1 добавьте картинку arr_2.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28])
arr_2 = np.empty([28, 28])

new_arr = np.append(arr_1, arr_2[np.newaxis], axis=0)

new_arr.shape

(11, 28, 28)

In [19]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28, 2), 10 картинок 28 на 28 пикселей с двумя цветовыми каналами G и B. 
# Массив arr_2 имеет размер (10, 28, 28, 1), 10 картинок 28 на 28 пикселей с одним цветовым каналом R. 
# Добавьте один массив к другому так, чтобы получить 10 картинок с тремя цветовыми каналами RGB.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28, 2])
arr_2 = np.empty([10, 28, 28, 1])

new_arr = np.append(arr_2, arr_1, axis=3) # - arr_2 + arr_1, потому что RGB (не GBR)

new_arr.shape

(10, 28, 28, 3)

In [20]:
# В программе создан массив записан в переменную arr. Удалите последний элемент на нулевой оси.

# Результат запишите в переменную new_arr.

arr = np.empty([10, 28, 28])

print(arr.shape)

new_arr = np.delete(arr, -1, axis=0)

print(new_arr.shape)

(10, 28, 28)
(9, 28, 28)


In [21]:
# В программе создан массив записан в переменную arr. Удалите элементы с индексами 1, 3, 5 на последней оси.

# Результат запишите в переменную new_arr.

arr = np.empty([10, 28, 28])

print(arr.shape)

new_arr = np.delete(arr, [1, 3, 5], axis=-1)

print(new_arr.shape)

(10, 28, 28)
(10, 28, 25)


In [22]:
delete_items = (1, 3, 5)
new_arr = np.delete(arr=arr, obj=delete_items, axis=arr.ndim - 1)

print(new_arr.shape)

(10, 28, 25)


In [23]:
img = np.random.randint(0, 255, 28*28).reshape([28, 28]) # - генерация картинки 28 на 28 пикселей
print(f'Размер картинки {img.shape}')

Размер картинки (28, 28)


In [24]:
# Множественное добавление картинок в массив картинок

# Копирует каждый раз существующий массив, выделяя память на него, и добавляет к нему новый элемент (долго)

arr = np.empty([100, 28, 28]) # - имеется массив 100 картинок

for i in range(10):
    img = np.random.randint(0, 255, 28*28).reshape([28, 28])
    arr = np.append(arr, img[np.newaxis], axis=0)

print(arr.shape)

(110, 28, 28)


In [25]:
# Множественное добавление картинок в массив картинок

# Изменяет существующий массив (быстрее)

arr = np.empty([100, 28, 28]) # - имеется массив 100 картинок
arr.resize([100 + 10, 28, 28]) # - расширение массива (10 элементов заполняется нулями)

for i in range(10):
    img = np.random.randint(0, 255, 28*28).reshape([28, 28])
    arr[100 + i] = img

print(arr.shape)

(110, 28, 28)


# 1.6 Индексация и срезы.

In [26]:
# В программе создан массив с наборам картинок и записан в переменную arr. 
# Размер массива (10, 28, 28), 10 картинок 28 на 28 пикселей​​. 

# Картинку с индексом 5 запишите в переменную img.

arr = np.arange(7840).reshape(10, 28 ,28)

print(arr.shape)

img = arr[5]

print(img.shape)

(10, 28, 28)
(28, 28)


In [27]:
# В программе создан массив содержащий координаты точек и записан в переменную coord. 
# Размер массива (10, 3), 10 точек с тремя координатами X, Y, Z​​. 
# Получите значение координаты X у точки с индексом 4.

# Результат запишите в переменную coord_X.

coord = np.arange(30).reshape(10, 3)

print(coord.shape)

coord_X = coord[4, 0]

print(coord_X)

(10, 3)
12


In [28]:
# В программе создан массив с наборам картинок и записан в переменную img. 
# Размер массива (100, 28, 28), 100 картинок 28 на 28 пикселей​​. 
# Получите изображения с индексами с 1 по 10 включительно. 

# Результат запишите в переменную new_img.

img = np.arange(100 * 28 * 28).reshape(100, 28, 28)

print(img.shape)

new_img = img[1:11, :, :]
new_img = img[1:11]

print(new_img.shape)

(100, 28, 28)
(10, 28, 28)


In [29]:
# В программе создан массив с наборам картинок и записан в переменную img. 
# Размер массива (100, 28, 28), 100 картинок 28 на 28 пикселей​​. 
# Получите изображения с индексами с 1 по 50 включительно, с шагом 3. 

# Результат запишите в переменную new_img.

img = np.arange(100 * 28 * 28).reshape(100, 28, 28)

print(img.shape)

new_img = img[1:51:3]

print(new_img.shape)

(100, 28, 28)
(17, 28, 28)


In [30]:
# В программе создан массив с наборам картинок и записан в переменную img. 
# Размер массива (100, 28, 28), 100 картинок 28 на 28 пикселей​​. 
# Разделите массив на четыре равные части, по 25 картинок в каждом.

# Результат запишите в переменные img_1, img_2, img_3, img_4.

img = np.arange(100 * 28 * 28).reshape(100, 28, 28)

img_1 = img[:25]
img_2 = img[25:50]
img_3 = img[50:75]
img_4 = img[75:100]

img_1, img_2, img_3, img_4 = [img[i: i + 25] for i in range(0, 76, 25)]

img_1, img_2, img_3, img_4 = np.array_split(img, 4)

In [31]:
# В программе создан массив с картинкой и записан в переменную img. 
# Размер массива (256, 256, 3), картинка 256 на 256 пикселей​​ с тремя цветовыми каналами RGB. 
# Получите фрагмент картинки с размерами по высоте начиная с индекса 10 до 100 включительно, 
# по ширине начиная с индекса 50 до 110 включительно. 

# Нулевая ось - высота\строки.
# Первая ось - ширина\столбцы.

# Фрагмент картинки запишите в переменную new_img.

img = np.arange(256 * 256 * 3).reshape(256, 256, 3)

new_img = img[10:101, 50:111]

In [32]:
# В программе создан массив с картинкой и записан в переменную img. 
# Размер массива (256, 256, 3), картинка 256 на 256 пикселей​​ с тремя цветовыми каналами RGB. 
# Получите фрагмент картинки высотой 50 пикселей и шириной 100 пикселей, 
# начиная с пикселя индекс которого 10 по высоте и 20 по ширине.

# Нулевая ось - высота\строки.
# Первая ось - ширина\столбцы.

# Фрагмент картинки запишите в переменную new_img.

img = np.arange(256 * 256 * 3).reshape(256, 256, 3)

new_img = img[:50, :100]
print(new_img.shape)

new_img = img[10:60, 20:120]
print(new_img.shape)

(50, 100, 3)
(50, 100, 3)


In [33]:
# В программе создан массив с картинкой и записан в переменную img. 
# Размер массива (256, 256, 3), картинка 256 на 256 пикселей​​ с тремя цветовыми каналами RGB. 
# Получите фрагмент картинки высотой 50 пикселей, шириной 100 пикселей, 
# начиная с пикселя индекс которого 100 по высоте и 50 по ширине, только R и B цветовые каналы.

# Нулевая ось - высота\строки.
# Первая ось - ширина\столбцы.

# Фрагмент картинки запишите в переменную new_img.

img = np.arange(256 * 256 * 3).reshape(256, 256, 3)

new_img = img[100: 100+50, 50: 50+100, [0, 2]]
print(new_img.shape)

new_img = img[100: 100+50, 50: 50+100, [True, False, True]]
print(new_img.shape)


(50, 100, 2)
(50, 100, 2)


In [34]:
# Создайте массив размером (5, 5) состоящий из нулей и типом данных int8. 
# Строки массива заполните единицами с шагом в два.

# Результат запишите в переменную new_arr.

arr = np.zeros([5, 5], dtype='int8')
print(arr)

print()

new_arr = arr.copy()
new_arr[:, ::2] = 1
print(new_arr)

print()

print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [35]:
# Создайте массив размером (5, 5) состоящий из нулей и типом данных int8. 
# Элементы строк заполните единицами начиная с индекса 1 и с шагом в два.

# Результат запишите в переменную new_arr.

arr = np.zeros([5, 5], dtype='int8')
print(arr)

print()

new_arr = arr.copy()
new_arr[:, 1::2] = 1
print(new_arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


In [36]:
# Создайте массив размером (5, 5) состоящий из единиц и типом данных int8. 
# Элементы массива заполните нулями в шахматном порядке.

arr = np.ones([5, 5], dtype='int8').ravel()
print(arr)

print()

new_arr = arr.copy()
new_arr[::2] = 0
new_arr = new_arr.reshape(5, 5)

print(new_arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [37]:
new_arr = np.ones([5, 5], dtype=np.int8)
print(new_arr)
print()

new_arr[::2, ::2] = 0
print(new_arr)
print()

new_arr[1::2, 1::2] = 0
print(new_arr)
print()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 0 1 0]
 [1 1 1 1 1]
 [0 1 0 1 0]
 [1 1 1 1 1]
 [0 1 0 1 0]]

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]



In [38]:
# В программе создан массив размером (5, 5) с типом данных np.int8 и записан в переменную arr. 
# Получите массив с внешним отступом в один элемент заполненный нулями.

arr = np.random.randint(1, 100, 5 * 5, dtype='int8').reshape(5, 5)
print(arr)
print()

new_arr = np.zeros(np.array(arr.shape) + (2, 2), dtype='int8')
print(new_arr)

[[22  4 90 52 27]
 [55 32 23 64  7]
 [83 81 93 67 38]
 [45 31 26 88 89]
 [94 52 62 60 94]]

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [39]:
new_arr[1:len(new_arr) - 1, 1: len(new_arr) - 1] = arr
new_arr

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 22,  4, 90, 52, 27,  0],
       [ 0, 55, 32, 23, 64,  7,  0],
       [ 0, 83, 81, 93, 67, 38,  0],
       [ 0, 45, 31, 26, 88, 89,  0],
       [ 0, 94, 52, 62, 60, 94,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [40]:
new_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
new_arr

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 22,  4, 90, 52, 27,  0],
       [ 0, 55, 32, 23, 64,  7,  0],
       [ 0, 83, 81, 93, 67, 38,  0],
       [ 0, 45, 31, 26, 88, 89,  0],
       [ 0, 94, 52, 62, 60, 94,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [41]:
arr = np.random.randint(1, 100, 10 * 10, dtype='int8').reshape(10, 10)
print(arr)
print()

new_arr = arr.copy()

new_arr[0] = 0
new_arr[-3:] = 0
new_arr[:, :4] = 0
new_arr[:, -2:] = 0

new_arr

[[ 9 58 30 54 12 60 46 37 53 22]
 [90 91  1  6 34 58 97 92 13 61]
 [22 28 13 61 34 63 57 92  3 57]
 [65 92  5 99 76 18 48 30  6 88]
 [52 69 32 74 74 10 70 59  6  3]
 [24 69 59 12 44 91 80 33 92 87]
 [18  1 37 40 76 64 98 94 16 50]
 [67 16 40  3 41 71 77 34 11 17]
 [25  6 16 73 71 15 30 96 86 26]
 [89 58 74  6  3 85 15 91 28 10]]



array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 34, 58, 97, 92,  0,  0],
       [ 0,  0,  0,  0, 34, 63, 57, 92,  0,  0],
       [ 0,  0,  0,  0, 76, 18, 48, 30,  0,  0],
       [ 0,  0,  0,  0, 74, 10, 70, 59,  0,  0],
       [ 0,  0,  0,  0, 44, 91, 80, 33,  0,  0],
       [ 0,  0,  0,  0, 76, 64, 98, 94,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [42]:
new_arr = np.zeros((10,10), dtype=np.int8)
new_arr[1:7,4:8] = arr[1:7,4:8]
new_arr

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 34, 58, 97, 92,  0,  0],
       [ 0,  0,  0,  0, 34, 63, 57, 92,  0,  0],
       [ 0,  0,  0,  0, 76, 18, 48, 30,  0,  0],
       [ 0,  0,  0,  0, 74, 10, 70, 59,  0,  0],
       [ 0,  0,  0,  0, 44, 91, 80, 33,  0,  0],
       [ 0,  0,  0,  0, 76, 64, 98, 94,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [43]:
new_arr = np.zeros_like(arr)
top, right, bottom, left = 1, 2, 3, 4
new_arr[top:-bottom, left:-right] = arr[top:-bottom, left:-right]
new_arr

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 34, 58, 97, 92,  0,  0],
       [ 0,  0,  0,  0, 34, 63, 57, 92,  0,  0],
       [ 0,  0,  0,  0, 76, 18, 48, 30,  0,  0],
       [ 0,  0,  0,  0, 74, 10, 70, 59,  0,  0],
       [ 0,  0,  0,  0, 44, 91, 80, 33,  0,  0],
       [ 0,  0,  0,  0, 76, 64, 98, 94,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [44]:
# В программе создан массив и записан в переменную arr
# С помощью списочной индексации получите массив:
# array(['x_1', 'y_1', 'x_2', 'y_2', 'x_3', 'y_3'])

arr = np.array(['x_1', 'x_2', 'y_3', 'x_3', 'y_2', 'y_1'])
new_arr = np.empty(0)

for i in range(len(arr) // 2):
    new_arr = np.append(new_arr, arr[[i, -i - 1]])
new_arr[-1], new_arr[-2] = new_arr[-2], new_arr[-1]
new_arr.shape = (3, 2)
new_arr

array([['x_1', 'y_1'],
       ['x_2', 'y_2'],
       ['x_3', 'y_3']], dtype='<U32')

In [45]:
arr = np.array(['x_1', 'x_2', 'y_3', 'x_3', 'y_2', 'y_1'])
new_arr = arr[np.array([0, 5, 1, 4, 3, 2])]
new_arr = new_arr.reshape(3,2)
new_arr

array([['x_1', 'y_1'],
       ['x_2', 'y_2'],
       ['x_3', 'y_3']], dtype='<U3')

# 2.1 Математические операции. Транслирование массивов.

In [46]:
arr1 = np.random.randint(0, 5, 10).reshape(5, 2)
arr2 = np.random.randint(0, 5, 10).reshape(5, 2)

display(arr1, arr2)
display(arr1 + arr2)

array([[4, 0],
       [3, 2],
       [3, 4],
       [4, 3],
       [1, 2]])

array([[4, 4],
       [4, 2],
       [4, 0],
       [1, 2],
       [2, 2]])

array([[8, 4],
       [7, 4],
       [7, 4],
       [5, 5],
       [3, 4]])

In [47]:
# В программе создан массив и записан в переменную arr. Умножьте массив на 10.

arr = np.arange(1, 11)
print(arr)

new_arr = arr * 10
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100]


In [48]:
# Даны размеры массивов. Какие из указанных массивов, благодаря транслированию, можно считать согласованными?

# (3, 2) - (2)                      +
# (4, 1, 8) - (4, 2)                -
# (16, 28, 28, 3) - (28, 28, 1)     +
# (2, 3, 4) - (1, 4)                +
# (5, 3, 7) - (3, 7)                +
# (10, 5) - (1)                     +

In [49]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (5, 3, 7), а массив arr_2 имеет размер (5). 
# Умножьте массив arr_1 на arr_2.

arr1 = np.empty(5 * 3 * 7).reshape(5, 3, 7)
arr2 = np.empty(5)
print(arr1.shape)
print(arr2.shape)

new_arr = arr1 * arr2[:, np.newaxis, np.newaxis]
print(new_arr.shape)

(5, 3, 7)
(5,)
(5, 3, 7)


In [50]:
arr1 = np.empty(5 * 3 * 7).reshape(5, 3, 7)
arr2 = np.empty(5)
print(arr1.shape)
print(arr2.shape)

arr2.shape = (5, 1, 1)
new_arr = arr1 * arr2
print(new_arr.shape)

(5, 3, 7)
(5,)
(5, 3, 7)


In [51]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (5, 3, 7), а массив arr_2 имеет размер (7). 
# Прибавьте  к массиву arr_1 массив arr_2.

arr1 = np.empty(5 * 3 * 7).reshape(5, 3, 7)
arr2 = np.empty(7)
print(arr1.shape)
print(arr2.shape)

arr2.shape = (1, 1, 7)
new_arr = arr1 + arr2
print(new_arr.shape)

(5, 3, 7)
(7,)
(5, 3, 7)


In [52]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (5, 3, 7), а массив arr_2 имеет размер (5, 7). 
# Поделите массив arr_1 на arr_2.

arr1 = np.empty(5 * 3 * 7).reshape(5, 3, 7)
arr2 = np.empty(5 * 7).reshape(5, 7)
print(arr1.shape)
print(arr2.shape)

new_arr = np.divide(arr1, arr2[:, np.newaxis, :])
print(new_arr.shape)

(5, 3, 7)
(5, 7)
(5, 3, 7)


In [53]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (6, 4, 3), а массив arr_2 имеет размер (4). 
# Умножьте массив arr_1 на arr_2.

arr1 = np.empty(6 * 4 * 3).reshape(6, 4, 3)
arr2 = np.empty(4)
print(arr1.shape)
print(arr2.shape)

new_arr = arr1 * arr2[:, np.newaxis]
print(new_arr.shape)

(6, 4, 3)
(4,)
(6, 4, 3)


In [54]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (6, 4, 3), а массив arr_2 имеет размер (6, 4). 
# Умножьте массив arr_1 на arr_2.

arr1 = np.empty(6 * 4 * 3).reshape(6, 4, 3)
arr2 = np.empty(6 * 4).reshape(6, 4)
print(arr1.shape)
print(arr2.shape)

new_arr = arr1 * arr2[:, :, np.newaxis]
print(new_arr.shape)

new_arr = arr1 * np.expand_dims(arr2, axis=-1)
print(new_arr.shape)

(6, 4, 3)
(6, 4)
(6, 4, 3)
(6, 4, 3)


In [55]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (5, 3), а массив arr_2 имеет размер (4, 2). 
# Прибавьте к массиву arr_1 массив arr_2.

arr1 = np.empty(5 * 3).reshape(5, 3)
arr2 = np.empty(4 * 2).reshape(4, 2)
print(arr1.shape)
print(arr2.shape)

new_arr = arr1[:, :, np.newaxis, np.newaxis] + arr2
print(new_arr.shape)

(5, 3)
(4, 2)
(5, 3, 4, 2)


In [56]:
# В программе создан массив размером (10, 2) и записан в переменную arr. 
# Массив содержит 10 точек с двумя координатами x и y. Массив loss имеет размер (10), содержит погрешность в измерениях координат для каждой точки. 
# Из координат в массиве arr вычтите погрешность.

arr = np.empty(10 * 2).reshape(10, 2)
loss = np.empty(10)
print(arr.shape)
print(loss.shape)

new_arr = arr - loss[:, np.newaxis]
print(new_arr.shape)

(10, 2)
(10,)
(10, 2)


In [57]:
# В программе создан массив размером (5, 3) и записан в переменную arr. 
# Массив содержит 10 точек с тремя координатами x, y и z. Массив loss имеет размер (5), содержит погрешность в измерениях координаты y. 
# В массиве arr исправьте значение координаты y вычев из нее погрешность.

arr = np.arange(1, 16).reshape(5, 3)
loss = np.arange(5)
display(arr, loss)

arr[:, 1] = arr[:, 1] - loss
display(arr)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

array([0, 1, 2, 3, 4])

array([[ 1,  2,  3],
       [ 4,  4,  6],
       [ 7,  6,  9],
       [10,  8, 12],
       [13, 10, 15]])

In [58]:
# В программе создан массив размером (10, 4, 2) и записан в переменную arr. 
# Массив содержит 10 наблюдений, в которых четырьмя разными методами измерялись координаты x и y. 
# Массив loss имеет размер (4), содержит погрешность в измерениях каждого метода. 
# В массиве arr исправьте значение координат вычев из них погрешность.

arr = np.arange(2 * 3 * 2).reshape(2, 3, 2)
loss = np.array([2, 2, 2])
display(arr, loss)

new_arr = arr - loss[np.newaxis, :, np.newaxis]
display(new_arr)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

array([2, 2, 2])

array([[[-2, -1],
        [ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7],
        [ 8,  9]]])

In [59]:
# Создан массив с размером (16, 28, 28), 16 картинок 28 на 28 пикселей в градации серого. 
# В массиве взят срез по первой и второй оси и записан в переменную arr. 
# Срез имеет размер (16, 3, 3). 
# Умножьте срез на массив kernels с размером (64, 3, 3), 64 ядра размером 3 на 3 пикселя.

arr = np.empty(16 * 3 * 3).reshape(16, 3, 3)
print(arr.shape)
kernels = np.empty(64 * 3 * 3).reshape(64, 3, 3)
print(kernels.shape)

new_arr = arr[np.newaxis, :, :, :] * kernels[:, np.newaxis, :, :]
print(new_arr.shape)

(16, 3, 3)
(64, 3, 3)
(64, 16, 3, 3)


In [60]:
# Создан массив с размером (16, 28, 28, 3), 16 картинок 28 на 28 пикселей с тремя цветовыми каналами RGB. 
# В массиве взят срез по первой и второй оси и записан в переменную arr. 
# Срез имеет размер (16, 3, 3, 3). 
# Умножьте срез на массив kernels с размером (32, 3, 3), 32 ядра размером 3 на 3 пикселя.

arr = np.empty(16 * 3 * 3 * 3).reshape(16, 3, 3, 3)
print(arr.shape)
kernels = np.empty(32 * 3 * 3).reshape(32, 3, 3)
print(kernels.shape)

new_arr = arr[np.newaxis, :, :, :, :] * kernels[ :, np.newaxis, np.newaxis, :, :]
print(new_arr.shape)

(16, 3, 3, 3)
(32, 3, 3)
(32, 16, 3, 3, 3)


In [61]:
arr = np.empty(16 * 3 * 3 * 3).reshape(16, 3, 3, 3)
print(arr.shape)
kernels = np.empty(32 * 3 * 3).reshape(32, 3, 3)
print(kernels.shape)

arr = arr.reshape(16, 1, 3, 3, 3)
kernels = kernels.reshape(1, 32, 3, 3, 1)

new_arr = arr * kernels
print(new_arr.shape)

(16, 3, 3, 3)
(32, 3, 3)
(16, 32, 3, 3, 3)


C:\Users\kuche\AppData\Local\Temp\ipykernel_11540\986492731.py:9: RuntimeWarning: overflow encountered in multiply
  new_arr = arr * kernels


# 2.2 Математические функции.

In [62]:
arr = np.arange(2, 20).reshape([3, 3, 2])
arr

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [63]:
# Методы

print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.mean())
print(arr.std())

2
19
189
10.5
5.188127472091127


In [64]:
# Функции

print(np.abs(arr))
print()
print(np.max(arr))
print(np.log(arr))
# print(np.exp(arr))
print(np.max(np.exp(arr)))

[[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]]

 [[14 15]
  [16 17]
  [18 19]]]

19
[[[0.69314718 1.09861229]
  [1.38629436 1.60943791]
  [1.79175947 1.94591015]]

 [[2.07944154 2.19722458]
  [2.30258509 2.39789527]
  [2.48490665 2.56494936]]

 [[2.63905733 2.7080502 ]
  [2.77258872 2.83321334]
  [2.89037176 2.94443898]]]
178482300.96318725


In [65]:
print(np.sin(arr))
print(np.cos(arr))
print(np.arctan(arr))

[[[ 0.90929743  0.14112001]
  [-0.7568025  -0.95892427]
  [-0.2794155   0.6569866 ]]

 [[ 0.98935825  0.41211849]
  [-0.54402111 -0.99999021]
  [-0.53657292  0.42016704]]

 [[ 0.99060736  0.65028784]
  [-0.28790332 -0.96139749]
  [-0.75098725  0.14987721]]]
[[[-0.41614684 -0.9899925 ]
  [-0.65364362  0.28366219]
  [ 0.96017029  0.75390225]]

 [[-0.14550003 -0.91113026]
  [-0.83907153  0.0044257 ]
  [ 0.84385396  0.90744678]]

 [[ 0.13673722 -0.75968791]
  [-0.95765948 -0.27516334]
  [ 0.66031671  0.98870462]]]
[[[1.10714872 1.24904577]
  [1.32581766 1.37340077]
  [1.40564765 1.42889927]]

 [[1.44644133 1.46013911]
  [1.47112767 1.48013644]
  [1.48765509 1.49402444]]

 [[1.49948886 1.50422816]
  [1.50837752 1.5120405 ]
  [1.51529782 1.51821327]]]


In [66]:
arr = np.arange(2, 20).reshape([3, 3, 2])
arr

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [67]:
print(np.sum(arr, axis=0))
print()
print(np.sum(arr, axis=1))
print()
print(np.sum(arr, axis=2))

[[24 27]
 [30 33]
 [36 39]]

[[12 15]
 [30 33]
 [48 51]]

[[ 5  9 13]
 [17 21 25]
 [29 33 37]]


In [68]:
# В программе создан одномерный массив и записан в переменную arr. 
# Получите индекс максимального и минимального значения в массиве.

# Результат запишите в переменные arr_argmax, arr_argmin соответственно.

arr = np.arange(1, 5)
print(arr)

print(np.argmax(arr))
print(*np.where(arr == 4)[0])

[1 2 3 4]
3
3


In [69]:
# В программе создан одномерный массив и записан в переменную arr. Найдите значение в массиве ближайшее к числу 10

# Результат запишите в переменную value.

value = arr[np.argmin(np.abs(arr - 10))]
value

4

In [70]:
# На пяти фотографиях лиц определенны координаты четырех точек 
# Первая точка - внешний уголок правого глаза, вторая точка - внешний уголок левого глаза, 
# третья точка - переносица, четвёртая точка - кончик носа. 
# Все данные записаны в массив coord с размером (5, 4, 2). 
# Определите среднее значение координат x и y в массиве.

coord = np.arange(5 * 4 * 2).reshape([5, 4, 2])

display(coord)

mean_coord = np.mean(coord, axis=(0, 1))
mean_coord

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

array([19., 20.])

In [71]:
# На пяти фотографиях лиц определенны координаты четырех точек. 
# Первая точка - внешний уголок правого глаза, вторая точка - внешний уголок левого глаза, 
# третья точка - переносица, четвёртая точка - кончик носа. 
# Все данные записаны в массив coord с размером (5, 4, 2). 
# Определите среднее значение координат x и y для каждой фотографии в массиве.

coord = np.arange(5 * 4 * 2).reshape([5, 4, 2])

mean_coord = np.mean(coord, axis=0)
mean_coord

array([[16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [72]:
# На пяти фотографиях лиц определенны координаты четырех точек. 
# Первая точка - внешний уголок правого глаза, вторая точка - внешний уголок левого глаза, 
# третья точка - переносица, четвёртая точка - кончик носа. 
# Все данные записаны в массив coord с размером (5, 4, 2). 
# Определите среднее значение координат x и y для каждой точки.

coord = np.arange(5 * 4 * 2).reshape([5, 4, 2])

mean_coord = np.mean(coord, axis=0)
mean_coord

array([[16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [73]:
# Набор данных состоящий из 100 картинок 28 на 28 пикселей с 3-мя цветовыми каналами RGB записан в массив img 
# и имеет размер(100, 28, 28, 3). 
# Определите среднее значение и стандартное отклонение (std) для каждого цветового канала по всему массиву.

# Результат запишите в переменные mean_img и std_img соответственно.

img = np.arange(100 * 28 * 28 * 3).reshape([100, 28, 28, 3])
print(img.shape)

mean_img = np.mean(img, axis=(0, 1, 2))
std_img = np.std(img, axis=(0, 1, 2))

print(mean_img, std_img)

(100, 28, 28, 3)
[117598.5 117599.5 117600.5] [67896.39165118 67896.39165118 67896.39165118]


In [74]:
# Набор данных состоящий из 100 картинок 28 на 28 пикселей с 3-мя цветовыми каналами RGB записан в массив img 
# и имеет размер(100, 28, 28, 3). 
# Определите среднее значение и стандартное отклонение (std) каждого цветового канала для каждой картинки.

# Результат запишите в переменные mean_img и std_img соответственно.

img = np.arange(100 * 28 * 28 * 3).reshape([100, 28, 28, 3])
print(img.shape)

mean_img = np.mean(img, axis=(1, 2))
std_img = np.std(img, axis=(1, 2))

print(mean_img.shape, std_img.shape)

(100, 28, 28, 3)
(100, 3) (100, 3)


In [75]:
# Набор данных состоящий из 100 картинок 28 на 28 пикселей с 3-мя цветовыми каналами RGB записан в массив img 
# и имеет размер(100, 28, 28, 3). 
# Определите среднее значение и стандартное отклонение (std) каждого цветового канала для каждого пикселя.

# Результат запишите в переменные mean_img и std_img соответственно. Размер массивов должен быть (28, 28, 3).

img = np.arange(100 * 28 * 28 * 3).reshape([100, 28, 28, 3])
print(img.shape)

mean_img = np.mean(img, axis=0)
std_img = np.std(img, axis=0)

print(mean_img.shape, std_img.shape)

(100, 28, 28, 3)
(28, 28, 3) (28, 28, 3)


In [76]:
# В программе создан массив и записан в переменную arr. Сформируйте массив с пятью элементами рандомно взятых из массива arr.

# Результат запишите в переменные new_arr.

arr = np.arange(10)
print(arr)

new_arr = np.random.choice(arr, 5)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[7 1 9 3 6]


In [77]:
# В программе создан массив и записан в переменную arr. 
# Перемешайте элементы на нулевой оси.

arr = np.arange(10)
print(arr)

np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[7 1 9 2 8 0 3 4 5 6]


# 2.3 Операции сравнения.

In [78]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (2, 7, 3), а массив arr_2 имеет размер (2, 7). 
# Сравните массив arr_1 с arr_2, операция сравнения <.

arr_1 = np.arange(2 * 7 * 3).reshape(2, 7, 3)
arr_2 = np.arange(2 * 7).reshape(2, 7)

new_arr = arr_1 < arr_2[:, :, np.newaxis]
print(new_arr)

[[[False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]]


In [79]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (2, 7, 3), а массив arr_2 имеет размер (1, 7). 
# Сравните массив arr_1 с arr_2, операция сравнения <.

arr_1 = np.arange(2 * 7 * 3).reshape(2, 7, 3)
arr_2 = np.arange(7).reshape(1, 7)

new_arr = arr_1 < arr_2[:, :, np.newaxis]
print(new_arr)

[[[False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]]


In [80]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (2, 7, 3), а массив arr_2 имеет размер (2, 3). 
# Сравните массив arr_1 с arr_2, операция сравнения <.

arr_1 = np.arange(2 * 7 * 3).reshape(2, 7, 3)
arr_2 = np.arange(2 * 3).reshape(2, 3)

new_arr = arr_1 != arr_2[:, np.newaxis, :]
print(new_arr)

[[[False False False]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [81]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. Проверьте массивы на равенство.

arr_1 = np.array([1, 3, 5, 6])
arr_2 = np.array([1, 3, 5, 6])

arr_equal = arr_1 == arr_2
arr_equal

array([ True,  True,  True,  True])

In [82]:
arr_equal = np.array_equal(arr_1, arr_2)
arr_equal

True

# 2.4 Матрицы и вектора.

In [83]:
np.random.seed(42)

vector_1 = np.array([1, 2, 3, 4, 5])
vector_2 = np.array([2, 3, 4, 5, 6])

matrix_1 = np.random.randint(10, size=[3, 3])
matrix_2 = np.random.randint(10, size=[3, 3])

display(vector_1, vector_2)
display(matrix_1, matrix_2)

array([1, 2, 3, 4, 5])

array([2, 3, 4, 5, 6])

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7]])

array([[4, 3, 7],
       [7, 2, 5],
       [4, 1, 7]])

In [84]:
# Умножение векторов

# Скалярное произведение

print(np.dot(vector_1, vector_2))
print(vector_1 @ vector_2)
print(np.inner(vector_1, vector_2))

70
70
70


In [85]:
# Внешнее произведение

# Каждый эдемент первого ветора умножается на строку второго вектра, образуя новую строку

print(np.outer(vector_1, vector_2))

[[ 2  3  4  5  6]
 [ 4  6  8 10 12]
 [ 6  9 12 15 18]
 [ 8 12 16 20 24]
 [10 15 20 25 30]]


In [86]:
# Умножение матриц

# Строка первой матрицы умножается на столбец второй матрицы

display(np.dot(matrix_1, matrix_2))
display(matrix_1 @ matrix_2)
display(np.matmul(matrix_1, matrix_2))

array([[ 73,  31, 106],
       [ 94,  33, 121],
       [ 78,  25,  93]])

array([[ 73,  31, 106],
       [ 94,  33, 121],
       [ 78,  25,  93]])

array([[ 73,  31, 106],
       [ 94,  33, 121],
       [ 78,  25,  93]])

In [87]:
vec_1 = np.array([1, 2, 3])
vec_2 = np.array([2, 3, 4, 5])

mat = np.random.randint(10, size=[4, 3])

display(vec_1, vec_2)
display(mat)

array([1, 2, 3])

array([2, 3, 4, 5])

array([[5, 1, 4],
       [0, 9, 5],
       [8, 0, 9],
       [2, 6, 3]])

In [88]:
# Умножение матрицы на вектро

# Вектор-строка умножается на столбец матрицы

display(np.dot(vec_2, mat))
display(vec_2 @ mat)

array([52, 59, 74])

array([52, 59, 74])

In [89]:
display(np.dot(mat, vec_1[:, np.newaxis]))
display(mat @ vec_1[:, np.newaxis])

array([[19],
       [33],
       [35],
       [23]])

array([[19],
       [33],
       [35],
       [23]])

In [90]:
print(np.linalg.matrix_rank(mat)) # - ранг матрицы
print(np.trace(mat))              # - след матрицы
print(np.linalg.det(mat[:3]))     # - определитель матрицы
display(np.linalg.eig(mat[:3]))   # - собственные значения и собственные вектора матрицы
display(np.linalg.inv(mat[:3]))   # - обратная матрица
display(np.linalg.svd(mat))       # - сингулярное разложение

3
23
156.99999999999994


EigResult(eigenvalues=array([ 1.45967618, 13.67503457,  7.86528925]), eigenvectors=array([[ 0.61773255, -0.37068144, -0.03137554],
       [ 0.43459076, -0.67840834, -0.97472235],
       [-0.65539101, -0.63431648,  0.22120559]]))

array([[ 0.51592357, -0.05732484, -0.19745223],
       [ 0.25477707,  0.08280255, -0.15923567],
       [-0.45859873,  0.05095541,  0.2866242 ]])

SVDResult(U=array([[-0.38091271, -0.24347434,  0.56272178, -0.69207655],
       [-0.49356808,  0.69609481, -0.41731837, -0.3125507 ],
       [-0.6831247 , -0.56940578, -0.35641648,  0.28650481],
       [-0.38031134,  0.36324829,  0.61818838,  0.58417215]]), S=array([15.61506165,  9.7495324 ,  1.76535201]), Vh=array([[-0.52066293, -0.45500258, -0.72241453],
       [-0.51757573,  0.84115508, -0.15675936],
       [ 0.67898857,  0.29228544, -0.67345656]]))

In [91]:
# Создайте единичную матрицу размером (4, 4).

mat_I = np.eye(4)
mat_I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [92]:
# Создайте матрицу на главной диагонали которой лежат числа от 1 до 10 включительно.

mat_diag = np.diag(np.arange(1, 11))
mat_diag

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [93]:
# Создайте матрицу размером (3, 3) все строки которой одинаковые и состоят из значений от 0 до 3

mat_A = np.full([3, 3], np.arange(0, 3))
mat_A

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [94]:
# Создайте матрицу размером (5, 5) все строки которой одинаковые и состоят из значений от 0 до 10 с шагом 2

mat_A = np.full([5, 5], np.arange(0, 10, 2))
mat_A

array([[0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [95]:
# Создайте матрицу размером (5, 5) все столбцы которой одинаковые и состоят из значений от 0 до 10 с шагом 2

mat_A = np.full([5, 5], np.arange(0, 10, 2))
np.transpose(mat_A)

array([[0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8]])

In [96]:
mat_A = (np.full([5, 5], np.arange(0, 10, 2))).T
mat_A

array([[0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8]])

In [97]:
# В программе создана матрица и записана в переменную mat_A. Из каждой строки массива вычтите среднее значение в этой строке.

np.random.seed(42)

mat = np.random.randint(10, size=[4, 3])
display(mat)

print(np.mean(mat, axis=1))

mat - np.mean(mat, axis=1)[:, np.newaxis]

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7]])

[5.33333333 6.33333333 5.         4.66666667]


array([[ 0.66666667, -2.33333333,  1.66666667],
       [-2.33333333, -0.33333333,  2.66666667],
       [-3.        ,  1.        ,  2.        ],
       [-0.66666667, -1.66666667,  2.33333333]])

In [98]:
np.invert(mat)

array([[ -7,  -4,  -8],
       [ -5,  -7, -10],
       [ -3,  -7,  -8],
       [ -5,  -4,  -8]])

# 1.7 Индексация по булевым значениям

In [99]:
# Дан массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл. 
# Найдите имена, средние баллы и другую информацию студентов, 
# которые старше 20 лет, женского пола и учатся на третьем курсе.

data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

mask = (np.int16(data[:, 1]) > 20) & (data[:, 2] == 'F') & (np.int16(data[:, 3]) == 3)

result = data[mask]

print(result)

[['Вера' '21' 'F' '3' '4.8']]


# 1.8 Транспонирование массивов

In [100]:
# 1. T (транспонирование): 
# Метод T используется для транспонирования массива, меняя местами строки и столбцы.
# numpy.ndarray.T

arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T
print("Исходный массив:")
print(arr)
print("\nТранспонированный массив:")
print(transposed_arr)

Исходный массив:
[[1 2 3]
 [4 5 6]]

Транспонированный массив:
[[1 4]
 [2 5]
 [3 6]]


In [101]:
# 2. dot (умножение матриц):
# Метод dot используется для вычисления скалярного произведения векторов или матричного умножения (если массивы являются двумерными, то выполняется матричное умножение, однако в этом случае предпочтительно использовать matmul или @)

# numpy.dot(a, b, out=None)

# a, b: Входные массивы.
# out: Опциональный аргумент для указания массива, в который будет записан результат.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.dot(arr1, arr2)
print("Первый массив:")
print(arr1) 
print("\nВторой массив:")
print(arr2) 
print("\nРезультат умножения:")
print(result)

Первый массив:
[[1 2]
 [3 4]]

Второй массив:
[[5 6]
 [7 8]]

Результат умножения:
[[19 22]
 [43 50]]


In [102]:
# 3. reshape (изменение формы):
# Метод reshape используется для изменения формы массива.

# numpy.reshape(a, newshape, order='C')

# a: Входной массив.
# newshape: Новая форма (количество строк и столбцов).
# order: Порядок расположения элементов в массиве. По умолчанию 'C' (порядок C-стайл, сначала строки).

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reshaped_arr = np.reshape(arr, (1, 9))
print("Исходный массив:")
print(arr)
print("\nМассив после изменения формы:")
print(reshaped_arr)

Исходный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Массив после изменения формы:
[[1 2 3 4 5 6 7 8 9]]


In [103]:
# 4. transpose (транспонирование):
# Метод transpose используется для транспонирования массива, позволяя указать порядок осей.

# numpy.transpose(arr, axes=None)

# arr: Входной массив.
# axes: Последовательность осей. По умолчанию - None, что означает, что оси будут изменены местами.

arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr, (1, 0))
print("Исходный массив:")
print(arr)
print("\nТранспонированный массив:")
print(transposed_arr)

Исходный массив:
[[1 2 3]
 [4 5 6]]

Транспонированный массив:
[[1 4]
 [2 5]
 [3 6]]


In [104]:
# 5. swapaxes (обмен осями):
# Метод swapaxes используется для обмена осями массива, меняя местами указанные оси.

# numpy.swapaxes(arr, axis1, axis2)

# arr: Входной массив.
# axis1: Ось, которую нужно поменять местами с axis2.
# axis2: Ось, которую нужно поменять местами с axis1.

arr = np.array([[1, 2, 3], [4, 5, 6]])
swapped_arr = np.swapaxes(arr, 0, 1)
print("Исходный массив:")
print(arr)
print("\nМассив после обмена осями:")
print(swapped_arr)

Исходный массив:
[[1 2 3]
 [4 5 6]]

Массив после обмена осями:
[[1 4]
 [2 5]
 [3 6]]


In [105]:
# Транспонировать только те строки, у которых первый элемент больше 3.

# Заданная матрица A
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]])

condition = A[:, 0] > 3

A[condition] = np.transpose(A[condition])

print("Матрица A после транспонирования строк с первым элементом больше 3:")
print(A)

Матрица A после транспонирования строк с первым элементом больше 3:
[[ 1  2  3  4]
 [ 5  9 13 17]
 [ 6 10 14 18]
 [ 7 11 15 19]
 [ 8 12 16 20]]


# 2.1 Унарные универсальные функции

In [106]:
# Унарные универсальные функции в NumPy представляют собой функции, 
# которые выполняют операции над отдельными элементами массивов. 
# Они называются "унарными", потому что они оперируют только над одним операндом.

In [107]:
# abs и fabs: Вычисляет абсолютное значение элементов массива. 
# Для работы с числами с плавающей запятой в NumPy обычно используется функция numpy.fabs.


# Пример с numpy.abs
array1 = np.array([-1, -2, -3, -4])
abs_values1 = np.abs(array1)
print(abs_values1)

# Пример с numpy.fabs
array2 = np.array([-1.5, -2.5, -3.5, -4.5])
abs_values2 = np.fabs(array2)
print(abs_values2)

[1 2 3 4]
[1.5 2.5 3.5 4.5]


In [108]:
# sqrt: Вычисляет квадратный корень из каждого элемента массива.

array = np.array([4, 9, 16, 25])
sqrt_values = np.sqrt(array)
print(sqrt_values)

# square:  Возводит каждый элемент массива в квадрат.

arr_square = np.square(np.array([2, 3, 4]))
print(arr_square)

[2. 3. 4. 5.]
[ 4  9 16]


In [109]:
# exp: Вычисляет экспоненту для каждого элемента массива (e^x).

arr_exp = np.exp(np.array([1, 2, 3]))
print(arr_exp)

# log, log10, log2, log1p: Вычисляют натуральный логарифм (log_e), логарифм по основанию 10, логарифм по основанию 2, и log(1 + x), соответственно.
# Синтаксис: numpy.log(x), numpy.log10(x), numpy.log2(x), numpy.log1p(x)

[ 2.71828183  7.3890561  20.08553692]


In [110]:
# sign: Определяет знак каждого элемента: 1 (положительное), 0 (ноль), или –1 (отрицательное).

arr_sign = np.sign(np.array([-5, 0, 5]))
print(arr_sign)

[-1  0  1]


In [111]:
# ceil: Вычисляет наименьшее целое число, не меньшее каждого элемента массива (округление по верхней границе).

arr_ceil = np.ceil(np.array([1.2, 2.7, 3.1]))
print(arr_ceil)

# floor: Вычисляет наибольшее целое число, не большее каждого элемента массива (округление по нижней границе).
# Синтаксис: numpy.floor(x)


# rint: Округляет элементы массива до ближайшего целого числа, сохраняя тип данных.
arr_rint = np.rint(np.array([1.2, 2.7, 3.1]))
print(arr_rint)

[2. 3. 4.]
[1. 3. 3.]


In [112]:
# modf: Возвращает дробную и целую части каждого элемента массива в двух отдельных массивах.

arr_modf = np.modf(np.array([1.2, 2.7, 3.1]))
print(arr_modf)

(array([0.2, 0.7, 0.1]), array([1., 2., 3.]))


In [113]:
# isin: Используется для проверки наличия элементов одного массива в другом. 
# Она возвращает булев массив той же формы, что и входные массивы, указывающий, 
# где элементы из первого массива присутствуют во втором массиве.
arr1= np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6])
result = np.isin(arr1, arr2)
print(result)

[False  True False  True False]


In [114]:
# isnan: Возвращает булев массив, показывающий, является ли каждый элемент NaN (Not a Number).
arr = np.array([1.0, np.nan, np.inf, -np.inf, 5.0])
nan_mask = np.isnan(arr)
print("isNaN:", nan_mask)

isNaN: [False  True False False False]


In [115]:
# isfinite, isinf: Возвращают булев массив, указывающий, является ли каждый элемент конечным числом или бесконечностью.
# Проверка на конечность (не NaN и не бесконечность)
arr = np.array([1.0, np.nan, np.inf, -np.inf, 5.0])
finite_mask = np.isfinite(arr)
print("isfinite:", finite_mask)
# Вывод: isfinite: [ True False False False True]  

# Проверка на бесконечность
arr = np.array([1.0, np.nan, np.inf, -np.inf, 5.0])
inf_mask = np.isinf(arr)
print("isinf:", inf_mask)
# Вывод: isinf: [False False True True False]

isfinite: [ True False False False  True]
isinf: [False False  True  True False]


In [116]:
# Найдите дробную и целую часть массива.

array = np.array([2.5, -3.7, 4.2])

fractional_part, integer_part = np.modf(array)

print(f'Дробная часть: {fractional_part}')
print(f'Целая часть: {integer_part}')

Дробная часть: [ 0.5 -0.7  0.2]
Целая часть: [ 2. -3.  4.]


# 2.2 Бинарные функции.

In [117]:
# Бинарные функции (Binary Universal Functions (ufuncs)) представляют собой функции, которые выполняют операции над парами элементов входных массивов

## Арифметические операции

In [118]:
# add:

# Описание: Выполняет поэлементное сложение двух массивов.
# Синтаксис: result = np.add(array1, array2)
# array1 и array2: Массивы для сложения. Они должны иметь одинаковую форму.

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.add(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат сложения:", result)

Первый массив: [1 2 3]
Второй массив: [4 5 6]
Результат сложения: [5 7 9]


In [119]:
# subtract:

# Описание: Выполняет поэлементное вычитание второго массива из первого.
# Синтаксис: result = np.subtract(array1, array2)
# array1 и array2: Массивы для вычитания. Они должны иметь одинаковую форму.

array1 = np.array([7, 8, 9])
array2 = np.array([4, 5, 6])
result = np.subtract(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат вычитания:", result)

Первый массив: [7 8 9]
Второй массив: [4 5 6]
Результат вычитания: [3 3 3]


In [120]:
# multiply:

# Описание: Выполняет поэлементное умножение двух массивов.
# Синтаксис: result = np.multiply(array1, array2)
# array1 и array2: Массивы для умножения. Они должны иметь одинаковую форму.

array1 = np.array([2, 3, 4])
array2 = np.array([5, 6, 7])
result = np.multiply(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат умножения:", result)

Первый массив: [2 3 4]
Второй массив: [5 6 7]
Результат умножения: [10 18 28]


In [121]:
# divide и floor_divide:

# Описание: divide выполняет поэлементное деление первого массива на второй. 
# floor_divide также округляет результат вниз, возвращая только целую часть.
# Синтаксис: result_divide = np.divide(array1, array2) 
# result_floor_divide = np.floor_divide(array1, array2)
# array1 и array2: Массивы для деления. Они должны иметь одинаковую форму.

array1 = np.array([10, 20, 30])
array2 = np.array([2, 3, 5])

# Используем функцию divide() для деления массивов
result_divide = np.divide(array1, array2)

# Используем функцию floor_divide() для целочисленного деления массивов
result_floor_divide = np.floor_divide(array1, array2)

print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат деления:", result_divide)
print("Результат целочисленного деления:", result_floor_divide)

Первый массив: [10 20 30]
Второй массив: [2 3 5]
Результат деления: [5.         6.66666667 6.        ]
Результат целочисленного деления: [5 6 6]


In [122]:
# power:

# Описание: Возводит элементы первого массива в степени, указанные во втором массиве.
# Синтаксис: result = np.power(array1, array2)
# array1 и array2: Массивы для возведения в степень. Они должны иметь одинаковую форму.

array = np.array([2, 3, 4])
result = np.power(array, 3)  
print("Исходный массив:", array)
print("Результат возведения в степень:", result)

print()

array = np.array([2, 3, 4])
degrees = np.array([5, 2, 1])
result = np.power(array, degrees)  
print("Исходный массив:", array)
print("Результат возведения в степень:", result)

Исходный массив: [2 3 4]
Результат возведения в степень: [ 8 27 64]

Исходный массив: [2 3 4]
Результат возведения в степень: [32  9  4]


In [123]:
# maximum и fmax:

# Описание: maximum возвращает поэлементный максимум двух массивов. 
# fmax также возвращает максимум, игнорируя значения NaN.

# Синтаксис: result_maximum = np.maximum(array1, array2) result_fmax = np.fmax(array1, array2)
# array1 и array2: Массивы для сравнения. Они должны иметь одинаковую форму.

array1 = np.array([2, 7, 5])
array2 = np.array([8, 3, 10])
result_maximum = np.maximum(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат maximum():", result_maximum)

print()

result_fmax = np.fmax(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат maximum():", result_fmax)

Первый массив: [2 7 5]
Второй массив: [ 8  3 10]
Результат maximum(): [ 8  7 10]

Первый массив: [2 7 5]
Второй массив: [ 8  3 10]
Результат maximum(): [ 8  7 10]


In [124]:
# minimum и fmin:

# Описание: minimum возвращает поэлементный минимум двух массивов. 
# fmin также возвращает минимум, игнорируя значения NaN.

# Синтаксис: result_minimum = np.minimum(array1, array2) result_fmin = np.fmin(array1, array2)
# array1 и array2: Массивы для сравнения. Они должны иметь одинаковую форму.

array1 = np.array([2, 7, 5])
array2 = np.array([8, 3, 10])
result_minimum = np.minimum(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат minimum():", result_minimum)

print()

result_fmin = np.fmin(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат maximum():", result_fmin)

Первый массив: [2 7 5]
Второй массив: [ 8  3 10]
Результат minimum(): [2 3 5]

Первый массив: [2 7 5]
Второй массив: [ 8  3 10]
Результат maximum(): [2 3 5]


In [125]:
# mod:

# Описание: Вычисляет остаток от деления элементов первого массива на соответствующие элементы второго массива (либо заданнаго числа). 
# Синтаксис: result = np.mod(array1, array2)
# array1 и array2: Массивы для выполнения операции взятия остатка. Они должны иметь одинаковую форму.

array1 = np.array([10, 21, 34])
array2 = np.array([3, 7, 8])
result = np.mod(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат mod():", result)

Первый массив: [10 21 34]
Второй массив: [3 7 8]
Результат mod(): [1 0 2]


In [126]:
# copysign:

# Описание: Копирует знак значения из второго массива в значения первого массива.
# Синтаксис: result = np.copysign(array1, array2) 
# array1 и array2: Массивы, знаки которых нужно скопировать. Они должны иметь одинаковую форму.

array1 = np.array([-1.5, 2.7, -3.1])
array2 = np.array([1.0, -1.0, 1.0])
result = np.copysign(array1, array2)
print("Первый массив:", array1)
print("Второй массив:", array2)
print("Результат copysign():", result)

Первый массив: [-1.5  2.7 -3.1]
Второй массив: [ 1. -1.  1.]
Результат copysign(): [ 1.5 -2.7  3.1]


## Поэлементное сравнение:

In [127]:
# Greater (np.greater)

# Описание: Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив той же формы, где каждый элемент равен True, 
# если соответствующий элемент в x больше соответствующего элемента в y, и False в противном случае.
# Синтаксис: np.greater(x, y)
# x и y - массивы для сравнения.

x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
result = np.greater(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Greater:", result)

print()

# Greater Equal (np.greater_equal)

# Описание: Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, 
# если соответствующий элемент в x больше или равен соответствующему элементу в y, и False в противном случае.
# Синтаксис: np.greater_equal(x, y)
# x и y - массивы для сравнения.

x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
result = np.greater_equal(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Greater Equal:", result)

Первый массив: [1 2 3]
Второй массив: [2 2 2]
Результат Greater: [False False  True]

Первый массив: [1 2 3]
Второй массив: [2 2 2]
Результат Greater Equal: [False  True  True]


In [128]:
# Less (np.less)

# Описание: Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, 
# если соответствующий элемент в x меньше соответствующего элемента в y, и False в противном случае.
# Синтаксис: np.less(x, y)

x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
result = np.less(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Less:", result)

print()

# Less Equal (np.less_equal)

# Описание: Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, 
# если соответствующий элемент в x меньше или равен соответствующему элементу в y, и False в противном случае.
# Синтаксис: np.less_equal(x, y)

x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
result = np.less_equal(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Less Equal:", result)

Первый массив: [1 2 3]
Второй массив: [2 2 2]
Результат Less: [ True False False]

Первый массив: [1 2 3]
Второй массив: [2 2 2]
Результат Less Equal: [ True  True False]


In [129]:
# Equal (np.equal)

# Описание: Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, 
# если соответствующий элемент в x равен соответствующему элементу в y, и False в противном случае.
# Синтаксис: np.equal(x, y)

x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
result = np.equal(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Equal:", result)

print()

# Not Equal (np.not_equal)

# Описание: Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, 
# если соответствующий элемент в x не равен соответствующему элементу в y, и False в противном случае.
# Синтаксис: np.not_equal(x, y)

x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
result = np.not_equal(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Not Equal:", result)

Первый массив: [1 2 3]
Второй массив: [2 2 2]
Результат Equal: [False  True False]

Первый массив: [1 2 3]
Второй массив: [2 2 2]
Результат Not Equal: [ True False  True]


## Логические операции:

In [130]:
# Logical AND (np.logical_and)

# Описание: Выполняет поэлементную логическую операцию И между элементами двух массивов и возвращает булев массив, где каждый элемент равен True, 
# если оба соответствующих элемента входных массивов равны True, и False в противном случае.
# Синтаксис: np.logical_and(x, y)

x = np.array([True, True, False])
y = np.array([True, False, False])
result = np.logical_and(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Logical AND:", result)

print()

# Logical OR (np.logical_or)

# Описание: Выполняет поэлементную логическую операцию ИЛИ между элементами двух массивов и возвращает булев массив, где каждый элемент равен True, 
# если хотя бы один из соответствующих элементов входных массивов равен True, и False в противном случае.
# Синтаксис: np.logical_or(x, y)

x = np.array([True, True, False])
y = np.array([True, False, False])
result = np.logical_or(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Logical OR:", result)

Первый массив: [ True  True False]
Второй массив: [ True False False]
Результат Logical AND: [ True False False]

Первый массив: [ True  True False]
Второй массив: [ True False False]
Результат Logical OR: [ True  True False]


In [131]:
# Logical XOR (np.logical_xor)

# Описание: Выполняет поэлементную логическую операцию "исключающее ИЛИ" между элементами двух массивов и возвращает булев массив, 
# где каждый элемент равен True, если ровно один из соответствующих элементов входных массивов равен True, и False в противном случае.
# Синтаксис: np.logical_xor(x, y)

x = np.array([True, True, False])
y = np.array([True, False, False])
result = np.logical_xor(x, y)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Logical XOR:", result)

print()

# Logical_not (np.logical_not)

# Описание: np.logical_not выполняет поэлементную логическую операцию НЕ (logical NOT) для массивов и возвращает булев массив, 
# где каждый элемент равен True, если соответствующий элемент входного массива равен False, и наоборот.
# Синтаксис: np.logical_not(x)

x = np.array([True, False, True])
result = np.logical_not(x)
print("Первый массив:", x)
print("Второй массив:", y)
print("Результат Logical_not:", result)

Первый массив: [ True  True False]
Второй массив: [ True False False]
Результат Logical XOR: [False  True False]

Первый массив: [ True False  True]
Второй массив: [ True False False]
Результат Logical_not: [False  True False]


In [132]:
# У вас есть массив чисел secret_codes, представляющих собой последовательность некоторых секретных кодов. 
# К сожалению, не все коды были переданы вам, а только часть provided_codes. Вам нужно определить, какие коды вам не предоставили.

secret_codes = np.array([15, 23, 7, 42, 18, 10, 7, 29])
provided_codes = np.array([23, 7, 18, 7])

res = secret_codes[~np.in1d(secret_codes, provided_codes)]
res = secret_codes[~np.isin(secret_codes, provided_codes)]
print(res)

[15 42 10 29]


In [133]:
numbers = np.array([2, 5, 8, 12, 15, 20, 23])

even_numbers = numbers[numbers % 2 * True]

print(f'Четные числа: {even_numbers}')

Четные числа: [2 5 2 2 5 2 5]


In [134]:
(numbers % 2 *True)

array([0, 1, 0, 0, 1, 0, 1], dtype=int32)

# 3.1 Запись логических условий в виде операций с массивами

In [135]:
# np.where — это функция библиотеки NumPy в Python, 
# предназначенная для выполнения условного элементарного поэлементного выбора значений из двух массивов 
# в зависимости от заданного условия. 
# Она имеет несколько форм синтаксиса, основные из которых выглядят следующим образом:

# numpy.where(condition[x, y])

# condition: Логическое выражение или массив булевых значений. Если condition равно True, то соответствующее значение из x выбирается, в противном случае - из y.
# x: Значение или массив, используемый при условии True.
# y: Значение или массив, используемый при условии False.

In [136]:
# Простой выбор между двумя значениями:

x = np.array([1, 2, 3, 4, 5])
y = np.where(x > 3, 'больше трех', 'трое и меньше')
print(y)

print()

# Замена значений в массиве:

import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.where(x % 2 == 0, 'четное', 'нечетное')
print(y)

print()

# Использование без явного указания y:

import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.where(x > 2)
print(y)

['трое и меньше' 'трое и меньше' 'трое и меньше' 'больше трех'
 'больше трех']

['нечетное' 'четное' 'нечетное' 'четное' 'нечетное']

(array([2, 3, 4], dtype=int64),)


In [137]:
# Пример использования

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.where(x > 2, x, y)

print(z)

[4 5 3]


In [138]:
# Замените все отрицательные значения в массиве arr на 0.

arr = np.array([-1, 2, -3, 4, -5])

modified_arr = np.where(arr < 0, 0, arr)

print("Исходный массив:")
print(arr)
print("Модифицированный массив:")
print(modified_arr)

Исходный массив:
[-1  2 -3  4 -5]
Модифицированный массив:
[0 2 0 4 0]


In [139]:
# Создайте новый массив,  который содержит 'A' для элементов больше 5, 'B' для элементов от 1 до 5 включительно и 'C' в противном случае.

arr = np.array([3, 8, 1, 6, 0, 7])

result_arr = np.where(arr > 5, 'A', np.where(arr < 1, 'C', 'B'))

print("Массив arr:")
print(arr)
print("Итоговый массив:")
print(result_arr)

Массив arr:
[3 8 1 6 0 7]
Итоговый массив:
['B' 'A' 'B' 'A' 'C' 'A']


In [140]:
# Замените все значения, которые делятся и на 2, и на 3, на значение  -1.

arr = np.array([2, 6, 9, 12, 15])

modified_arr = np.where((arr % 3 == 0) & (arr % 2 == 0), -1, arr)

print("Массив arr:")
print(arr)
print("Модифицированный массив:")
print(modified_arr)

Массив arr:
[ 2  6  9 12 15]
Модифицированный массив:
[ 2 -1  9 -1 15]


In [141]:
# Выберите значения, которые нечетные и больше 3 или четные и меньше 0. Остальные значения замените на ноль.

arr = np.array([-2, 3, 5, -4, 6, 1])

selected_values = np.where(((arr > 3) & (arr % 2 != 0)) | ((arr < 0) & (arr % 2 == 0)), arr, 0)

print("Массив arr:")
print(arr)
print("Выбранные значения:")
print(selected_values)

Массив arr:
[-2  3  5 -4  6  1]
Выбранные значения:
[-2  0  5 -4  0  0]


# 3.2 Математические и статистические операции с массивами

In [142]:
# Математические и статистические операции с массивами в библиотеке NumPy включают в себя различные функции, 
# позволяющие проводить вычисления с элементами массивов. 
# Эти операции обеспечивают мощные инструменты для анализа данных, научных вычислений и многих других приложений

In [143]:
# sum:

# Описание: Вычисляет сумму элементов массива.
# Синтаксис: numpy.sum(a, axis=None, dtype=None, keepdims=<no value>, initial=<no value>, where=<no value>)
# a: Входной массив.
# axis: Опциональный параметр, указывающий ось или оси, по которым производится суммирование. По умолчанию суммирует все элементы массива.
# dtype: Опциональный параметр, указывающий желаемый тип данных результата.
# keepdims: Опциональный параметр, указывающий, следует ли сохранять размерности в выводе. Если True, то размерности сохраняются.
# initial: Опциональный параметр, указывающий начальное значение для суммирования.
# where: Опциональный параметр, который определяет условие, при котором элементы участвуют в операции.

# mean:

# Описание: Вычисляет среднее значение элементов массива.
# Синтаксис: numpy.mean(a, axis=None, dtype=None, keepdims=<no value>, where=<no value>)
# Параметры аналогичны sum.

# median()

# Описание: Метод numpy.median() используется для вычисления медианы значений в массиве. 
# Медиана - это значение, которое делит упорядоченный массив пополам, то есть половина значений меньше медианы, а другая половина больше.
# Синтаксис:numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
# a: Входной массив, для которого вы хотите вычислить медиану.
# axis: Опциональный параметр, указывающий ось или оси, вдоль которых необходимо вычислить медиану. По умолчанию (axis=None), 
# медиана вычисляется по всем элементам массива.
# out: Опциональный параметр. Если указан, результат будет записан в этот массив. В противном случае будет создан новый массив.
# overwrite_input: Опциональный параметр. Если True, разрешено использовать данные входного массива a для хранения результата. 
# Если False, результат будет храниться в новом массиве. По умолчанию (overwrite_input=False), не изменяет входной массив.
# keepdims: Опциональный параметр. Если True, размеры осей, вдоль которых вычисляется медиана, будут сохранены в выводе. 
# Если False, размерности этих осей будут удалены из вывода. По умолчанию (keepdims=False), размерности уменьшаются.


In [144]:
# std (Standard Deviation):

# Описание: Вычисляет стандартное отклонение элементов массива.
# Синтаксис: numpy.std(a, axis=None, dtype=None, ddof=0, keepdims=<no value>, where=<no value>)
# a: Входной массив.
# axis: Опциональный параметр, указывающий ось или оси, по которым производится вычисление стандартного отклонения. По умолчанию вычисляется по всем элементам массива.
# dtype: Опциональный параметр, указывающий желаемый тип данных результата.
# ddof: Опциональный параметр, степень свободы для коррекции. По умолчанию 0.
# keepdims: Опциональный параметр, указывающий, следует ли сохранять размерности в выводе.
# where: Опциональный параметр, который определяет условие, при котором элементы участвуют в операции.

# var (Variance):

# Описание: Вычисляет дисперсию элементов массива.
# Синтаксис: numpy.var(a, axis=None, dtype=None, ddof=0, keepdims=<no value>, where=<no value>)
# Параметры аналогичны std.

In [145]:
# min:

# Описание: Возвращает минимальное значение в массиве.
# Синтаксис: numpy.min(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
# a: Входной массив.
# axis: Опциональный параметр, указывающий ось или оси, по которым производится поиск минимального значения. По умолчанию по всем элементам массива.
# out: Опциональный параметр, массив, в который будет сохранен результат. Если не указан, создается новый массив.
# keepdims: Опциональный параметр, указывающий, следует ли сохранять размерности в выводе.
# initial: Опциональный параметр, указывающий начальное значение для поиска минимального значения.
# where: Опциональный параметр, который определяет условие, при котором элементы участвуют в операции.

# max:

# Описание: Возвращает максимальное значение в массиве.
# Синтаксис: numpy.max(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
# Параметры аналогичны min.

In [146]:
# argmin:

# Описание: Возвращает индекс минимального значения в массиве.
# Синтаксис: numpy.argmin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
# Параметры аналогичны min.

# argmax:

# Описание: Возвращает индекс максимального значения в массиве.
# Синтаксис: numpy.argmax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
# Параметры аналогичны min.

In [147]:
# cumsum:

# Описание: Возвращает кумулятивные суммы элементов массива.

# Для массива [a, b, c, d, ...], кумулятивная сумма будет [a, a+b, a+b+c, a+b+c+d, ...].
# Таким образом, каждый элемент кумулятивной суммы представляет собой сумму всех предыдущих элементов и самого элемента на данной позиции.

# Синтаксис: numpy.cumsum(a, axis=None, dtype=None, out=None)
# a: Входной массив, элементы которого будут складываться по указанной оси.
# axis: Опциональный параметр, указывающий ось или оси, по которым производится кумулятивная сумма. По умолчанию операция выполняется над плоским массивом.
# dtype: Опциональный параметр, указывающий желаемый тип данных результата.
# out: Опциональный параметр, массив, в который будет сохранен результат. Если не указан, создается новый массив.

# cumprod:

# Описание: Возвращает кумулятивные произведения элементов массива.

# Для массива [a, b, c, d, ...], кумулятивное произведение будет [a, a*b, a*b*c, a*b*c*d, ...].
# Таким образом, каждый элемент кумулятивного произведения представляет собой произведение всех предыдущих элементов и самого элемента на данной позиции.

# Синтаксис: numpy.cumprod(a, axis=None, dtype=None, out=None)
# a: Входной массив, элементы которого будут перемножаться по указанной оси.
# axis: Опциональный параметр, указывающий ось или оси, по которым производится кумулятивное произведение. По умолчанию операция выполняется над плоским массивом.
# dtype: Опциональный параметр, указывающий желаемый тип данных результата.
# out: Опциональный параметр, массив, в который будет сохранен результат. Если не указан, создается новый массив.

In [148]:
# np.ptp (Peak-to-Peak):

# Описание: ptp возвращает размах (peak-to-peak) значений в массиве, то есть разницу между максимальным и минимальным значениями.

# Синтаксис: numpy.ptp(a, axis=None, out=None)
# a: Входной массив.
# axis: Опциональный параметр, указывающий ось или оси, по которым вычисляется размах. По умолчанию вычисляется размах по всем элементам массива.
# out: Опциональный параметр, массив, в который будет сохранен результат. Если не указан, создается новый массив.

data = np.array([3, 8, 2, 10, 5, 7, 1])
range_of_data = np.ptp(data)
print(f"Массив данных: {data}")
print(f"Разница между максимальным и минимальным значениями: {range_of_data}")

Массив данных: [ 3  8  2 10  5  7  1]
Разница между максимальным и минимальным значениями: 9


In [149]:
# np.diff:

# Описание: diff вычисляет разности между соседними элементами массива. 
# Этот метод особенно полезен при анализе изменений во временных рядах данных.

# Синтаксис: numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
# a: Входной массив.
# n: Опциональный параметр, количество разностей. По умолчанию 1.
# axis: Опциональный параметр, указывающий ось или оси, по которым производится операция. По умолчанию -1 (последняя ось).
# prepend: Опциональный параметр, добавляет значения перед массивом.
# append: Опциональный параметр, добавляет значения после массива.

arr = np.array([1, 4, 7, 2, 9])
diff_arr = np.diff(arr)
print("Исходный массив:", arr)
print("Разности между соседними элементами:", diff_arr)

Исходный массив: [1 4 7 2 9]
Разности между соседними элементами: [ 3  3 -5  7]


In [150]:
# np.bincount(arr) - это метод библиотеки NumPy, предназначенный для подсчета частоты встречаемости каждого неотрицательного целого числа в массиве. 
# Массив может содержать только неотрицательные целые числа. 

# arr: Одномерный массив неотрицательных целых чисел. Обязательный параметр.

data = np.array([1, 2, 2, 3, 4, 4, 4])
bin_counts = np.bincount(data)
print(f"Массив данных: {data}")
print(f"Количество вхождений каждого значения: {bin_counts}")

Массив данных: [1 2 2 3 4 4 4]
Количество вхождений каждого значения: [0 1 2 1 3]


In [151]:
# Представим, что у вас есть данные о ежедневных изменениях стоимости акций компании. 
# Найдите изменение цен за каждый день, а также дни с минимальным и максимальным изменением. 

stock_prices = np.array([50, 55, 60, 52, 48, 65, 70])
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'])

daily_returns = np.diff(stock_prices)
best_day = days[np.argmax(daily_returns) + 1]
worst_day = days[np.argmin(daily_returns) + 1]

print(f"Изменения цен за день: {daily_returns}")
print(f"Лучший день: {best_day}")
print(f"Худший день: {worst_day}")

Изменения цен за день: [ 5  5 -8 -4 17  5]
Лучший день: суббота
Худший день: четверг


In [152]:
# Представим, что у вас есть данные о температуре воздуха в течение года. 
# Найди размах температур, а также индексы минимальной и максимальной температуры.

temperature_data = np.array([20, 22, 25, 18, 30, 28, 35, 22, 15, 10, 5, 12])

temperature_range = np.ptp(temperature_data)
coldest_day = np.argmin(temperature_data)
hottest_day =  np.argmax(temperature_data)

print(f"Размах температур: {temperature_range}")
print(f"Индекс самого холодного дня: {coldest_day}")
print(f"Индекс самого теплого дня: {hottest_day}")

Размах температур: 30
Индекс самого холодного дня: 10
Индекс самого теплого дня: 6


In [153]:
# Заданные данные (доходы инвесторов в тысячах долларов)
income_data = np.array([40, 55, 60, 75, 80, 85, 90, 100, 120, 150])

median_income = np.median(income_data)

above_median = income_data[income_data > median_income]
below_median = income_data[income_data < median_income]

income_range_above_median = np.ptp(above_median)

print("Медиана доходов:", median_income)
print("Инвесторы, заработавшие выше медианы:", above_median)
print("Инвесторы, заработавшие ниже медианы:", below_median)
print("Разброс доходов для инвесторов, заработавших выше медианы:", income_range_above_median)

Медиана доходов: 82.5
Инвесторы, заработавшие выше медианы: [ 85  90 100 120 150]
Инвесторы, заработавшие ниже медианы: [40 55 60 75 80]
Разброс доходов для инвесторов, заработавших выше медианы: 65


In [154]:
# Найдите среднюю стоимость акций каждой компании за все дни. 
# Затем определите компанию с максимальной волатильностью (наибольшим размахом цен). 
# И под конец, найдите день с наибольшим общим изменением в стоимости акций всех компаний.

# Цены акций для 3 компаний(каждый столбец - отдельная компания)
stock_prices = np.array([
    [110, 112, 108],
    [115, 118, 120],
    [108, 110, 105],
    [122, 121, 124],
    [128, 130, 125],
    [133, 132, 134],
    [129, 127, 130]
])

average_prices = np.round(np.mean(stock_prices, axis=0), 2)

volatility = np.ptp(stock_prices, axis=0)
most_volatile_company = np.argmax(volatility)

total_daily_change = np.sum(np.abs(np.diff(stock_prices, axis=0)), axis=1)
day_with_max_change = np.argmax(total_daily_change) + 1

print("Средняя стоимость акций каждой компании:", average_prices) 
print("Индекс самой волатильной компании:", most_volatile_company) 
print("Индекс дня с наибольшим изменением в стоимости акций:", day_with_max_change)

Средняя стоимость акций каждой компании: [120.71 121.43 120.86]
Индекс самой волатильной компании: 2
Индекс дня с наибольшим изменением в стоимости акций: 3


In [155]:
# Найдите средний возраст пациентов. Определите пациента с самым высоким уровнем холестерина и самым низким давлением.

# Заданные данные (1-й столбец: возраст, 2-й столбец: уровень холестерина, 3-й столбец: давление)
medical_data = np.array([
    [30, 200, 120],
    [45, 220, 130],
    [35, 190, 110]
])

average_age = np.round(np.mean(medical_data[:, 0]), 1)
max_cholesterol_patient = medical_data[np.argmax(medical_data[:, 1])]
min_pressure_patient = medical_data[np.argmin(medical_data[:, 2])]

print(f"Средний возраст пациентов: {average_age}")
print("Пациент с самым высоким уровнем холестерина:", max_cholesterol_patient) # Показатели пациента с самым высоким уровнем холестерина
print("Пациент с самым низким давлением:", min_pressure_patient) # Показатели пациента с самым низким давлением

Средний возраст пациентов: 36.7
Пациент с самым высоким уровнем холестерина: [ 45 220 130]
Пациент с самым низким давлением: [ 35 190 110]


In [156]:
# Дан массив student_scores, с оценками студентов(каждая строка один студент). 
# Найдите средний балл за каждую задачу. 
# Определите студента с наивысшим средним баллом. Найдите задачу с наименьшей дисперсией баллов.

student_scores = np.array([
    [5, 4, 3],  # Оценки первого студента за три задачи
    [3, 2, 4],  # Оценки второго студента за три задачи
    [5, 5, 3]   # Оценки третьего студента за три задачи
])

average_scores = np.round(np.mean(student_scores, axis=0), 1)
highest_avg_student = np.argmax(np.mean(student_scores, axis=1))
min_variability_task = np.argmin(np.var(student_scores, axis=0))

print("Средний балл за каждую задачу:", average_scores)
print("Индекс cтудента с наивысшим средним баллом:", highest_avg_student)
print("Индекс задачи с наименьшей дисперсией баллов:", min_variability_task)

Средний балл за каждую задачу: [4.3 3.7 3.3]
Индекс cтудента с наивысшим средним баллом: 2
Индекс задачи с наименьшей дисперсией баллов: 2


In [157]:
# Напишите функцию most_frequent_number(arr), которая находит наиболее часто встречающее число и количество его вхождений

def most_frequent_number(arr):
    bin_counts = np.bincount(arr)
    most_frequent_index = np.argmax(bin_counts)
    # occurrences =  np.sum(arr == most_frequent_index)
    occurrences = bin_counts[most_frequent_index]
    return most_frequent_index, occurrences

arr = np.array([1, 2, 3, 1, 2, 1, 4, 4, 4, 4, 5, 4, 3, 3])
result_number, result_occurrences = most_frequent_number(arr)

print(f"Наиболее часто встречающееся число: {result_number}")
print(f"Количество вхождений: {result_occurrences}")

Наиболее часто встречающееся число: 4
Количество вхождений: 5


# 3.3 Сортировка и другие операции

In [158]:
# Эти функции также являются частью библиотеки NumPy и предоставляют операции для работы с множествами или уникальными элементами массивов

In [159]:
# np.sort
# (a, axis=-1, kind=None, order=None)  -  выполняет сортировку элементов массива.

# a: Исходный массив, который нужно отсортировать.
# axis: Опциональный параметр, указывающий ось, по которой нужно провести сортировку. По умолчанию -1, что означает сортировку по последней оси.
# kind: Опциональный параметр, определяющий алгоритм сортировки. Может принимать значения 'quicksort', 'mergesort', 'heapsort' или None. По умолчанию используется 'quicksort'.
# order: Опциональный параметр, применяется при сортировке структурированных массивов. Может содержать названия полей и направления сортировки для каждого поля.


# np.unique
# (arr, return_index=False, return_inverse=False, return_counts=False, axis=None) - это функция, которая возвращает уникальные элементы массива. 

# return_index: Если True, то также возвращает массив индексов первого вхождения уникальных элементов.
# return_inverse: Если True, то также возвращает массив, который при использовании как индекс восстанавливает исходный массив.
# return_counts: Если True, то также возвращает массив, содержащий количество вхождений каждого уникального элемента.
# axis: Опциональный параметр, указывающий ось, по которой нужно найти уникальные элементы. Если не указан, поиск производится по всему массиву.

In [160]:
# np.intersect1d
# (arr1, arr2, assume_unique=False, return_indices=False)

# Возвращает отсортированный массив уникальных элементов, общих для двух входных массивов.
# assume_unique: Если True, то предполагает, что входные массивы уже уникальны, что ускоряет выполнение.
# return_indices: Если True, то также возвращает индексы элементов в каждом из входных массивов.


# np.union1d
# (arr1, arr2)

# Возвращает отсортированный массив уникальных элементов, объединенных из двух входных массивов.

In [161]:
# np.in1d
# (arr1, arr2, assume_unique=False, invert=False)

# Возвращает булев массив той же формы, что и arr1, указывающий, содержатся ли элементы arr1 в arr2.
# assume_unique: Если True, то предполагает, что arr1 и arr2 уже уникальны.
# invert: Если True, то инвертирует результат, то есть возвращает, содержатся ли элементы arr1 не в arr2.

In [162]:
# np.setdiff1d
# (arr1, arr2, assume_unique=False)

# Возвращает уникальные элементы, которые есть в arr1, но отсутствуют в arr2.
# assume_unique: Если True, то предполагает, что arr1 и arr2 уже уникальны.

In [163]:
# np.setxor1d
# (arr1, arr2, assume_unique=False)

# Возвращает уникальные элементы, которые есть в одном из массивов, но отсутствуют в обоих.
# assume_unique: Если True, то предполагает, что arr1 и arr2 уже уникальны.

In [ ]:
# np.delete
# (arrr, obj, axis=None) - это функция библиотеки NumPy, которая используется для удаления элементов из массива. 
# Она может использоваться для удаления как отдельных элементов, так и целых строк или столбцов в многомерных массивах. 

# arr: Одномерный массив неотрицательных целых чисел. Обязательный параметр.
# arr: Исходный массив.
# obj: Объект, который нужно удалить. Это может быть индекс, срез или последовательность индексов/срезов. Функция возвращает новый массив с удаленными элементами. Исходный массив не изменяется.
# axis: Опциональный параметр, указывающий ось, по которой нужно удалить элементы. Если axis не указан, функция работает с плоским массивом.

In [165]:
# Отсортируйте массив array тремя способами:

# По имени в алфавитном порядке
# По возрасту в порядке возрастания
# По возрасту в порядке убывания

people = np.array([('John', 28), 
                   ('Sam', 22), 
                   ('Smith', 25), 
                   ('Jones', 30)], 
            dtype=[('name', 'S10'), ('age', int)]) # определение структуры данных для массива,
                                                   # где каждый элемент имеет поле 
                                                   # "name" типа str длиной до
                                                   # 10 символов ('S10') и поле "age" типа int

sorted_people_by_name = np.sort(people, order='name')
sorted_people_by_age = np.sort(people, order='age')
sorted_people_by_age_desc = np.sort(people, order='age')[::-1]

print("Исходный массив структур:")
print(people)
print("\nСортировка по полю 'name':")
print(sorted_people_by_name)
print("\nСортировка по полю 'age' в порядке возрастания:")
print(sorted_people_by_age)
print("\nСортировка по полю 'age' в порядке убывания:")
print(sorted_people_by_age_desc)

Исходный массив структур:
[(b'John', 28) (b'Sam', 22) (b'Smith', 25) (b'Jones', 30)]

Сортировка по полю 'name':
[(b'John', 28) (b'Jones', 30) (b'Sam', 22) (b'Smith', 25)]

Сортировка по полю 'age' в порядке возрастания:
[(b'Sam', 22) (b'Smith', 25) (b'John', 28) (b'Jones', 30)]

Сортировка по полю 'age' в порядке убывания:
[(b'Jones', 30) (b'John', 28) (b'Smith', 25) (b'Sam', 22)]


In [166]:
# Найдите уникальные элементы, а также их индексы в порядке их появления, а затем выведите наименьший и наибольший элементы .

arr = np.array([3, 2, 4, 1, 5, 2, 6, 4, 7])

unique_elements = np.unique(arr, return_index=True, return_inverse=False)

min_element = np.min(arr)
max_element = np.max(arr)

print("Уникальные элементы:", unique_elements[0])
print("Индексы вхождения уникальных элементов:", unique_elements[1])
print("Наименьший элемент:", min_element)
print("Наибольший элемент:", max_element)

Уникальные элементы: [1 2 3 4 5 6 7]
Индексы вхождения уникальных элементов: [3 1 0 2 4 6 8]
Наименьший элемент: 1
Наибольший элемент: 7


In [172]:
# У вас есть два массива целых чисел, arr1 и arr2. 
# Ваша задача - найти и вывести объединение уникальных элементов обоих массивов, а также определить те числа, которые встречаются и в arr1, и в arr2.

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

unique_arr1 = np.unique(arr1)
unique_arr2 = np.unique(arr2)

union = np.union1d(unique_arr1, unique_arr2)

in_arr1_mask = np.isin(union, arr1)
in_arr2_mask = np.isin(union, arr2)

common_elements_mask = np.logical_and(in_arr1_mask, in_arr2_mask)
common_elements = union[common_elements_mask]

print("Объединение уникальных элементов:", union)
print("Маска для вхождения в arr1:", in_arr1_mask)
print("Маска для вхождения в arr2:", in_arr2_mask)
print("Маска для общих элементов:", common_elements_mask)
print("Элементы, встречающиеся и в arr1, и в arr2:", common_elements)

Объединение уникальных элементов: [1 2 3 4 5 6 7]
Маска для вхождения в arr1: [ True  True  True  True  True False False]
Маска для вхождения в arr2: [False False  True  True  True  True  True]
Маска для общих элементов: [False False  True  True  True False False]
Элементы, встречающиеся и в arr1, и в arr2: [3 4 5]


In [210]:
# Найдите уникальные элементы массива. 
# Затем удалите из этого массива все уникальные элементы, которые больше заданного порога.

arr = np.array([3, 2, 4, 1, 5, 2, 6, 4, 7])
threshold = 4  # порог для удаления элементов

unique_elements = np.unique(arr) # нахождение уникальных элементов массива
indices_to_remove = np.where(unique_elements > threshold) # нахождение индексов элементов, превышающих порог
filtered_arr = np.delete(unique_elements, indices_to_remove) # удаление элементов массива arr, превышающих порог

print("Исходный массив:", arr)
print("Уникальные элементы:", unique_elements)
print("Массив после удаления элементов больше", threshold, ":", filtered_arr)

Исходный массив: [3 2 4 1 5 2 6 4 7]
Уникальные элементы: [1 2 3 4 5 6 7]
Массив после удаления элементов больше 4 : [1 2 3 4]


In [217]:
# Удалите из массива arr все элементы, которые встречаются более одного раза.

arr = np.array([3, 2, 4, 1, 5, 2, 6, 4, 7])

unique_elements, counts = np.unique(arr, return_counts=True)
elements_to_remove = unique_elements[counts > 1]

filtered_arr = np.delete(arr, np.where(np.isin(arr, elements_to_remove)))

print("Исходный массив:", arr)
print("Массив после удаления элементов, встречающихся более одного раза:", filtered_arr)

Исходный массив: [3 2 4 1 5 2 6 4 7]
Массив после удаления элементов, встречающихся более одного раза: [3 1 5 6 7]


# 3.4 Генерация псевдослучайных чисел в Numpy

In [ ]:
# В NumPy генерация псевдослучайных чисел выполняется с использованием модуля numpy.random. 
# Этот модуль полезен в различных задачах, таких как создание случайных массивов, 
# симуляция случайных процессов и другие приложения, где требуется использование случайности.

In [218]:
# seed:

# Описание: Инициализирует генератор псевдослучайных чисел. Установка зерна (seed) позволяет получать одинаковую последовательность случайных чисел при каждом запуске программы. Это полезно, например, при отладке, чтобы результаты были воспроизводимы.
# Синтаксис:
# numpy.random.seed(seed)

# seed: Начальное значение для генератора случайных чисел. Если seed не указан, используется системное время.

# Установка зерна для воспроизводимости результатов
np.random.seed(42)

# Генерация случайных чисел
random_numbers = np.random.rand(5)
print("Случайные числа:", random_numbers)

# При повторном запуске программы результаты будут такими же, как и в первый раз
np.random.seed(42)
random_numbers_again = np.random.rand(5)
print("Случайные числа после установки зерна:", random_numbers_again)

Случайные числа: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Случайные числа после установки зерна: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [ ]:
# rand:

# Описание: Генерирует равномерно распределенные случайные числа в диапазоне [0.0, 1.0). 
# Каждый элемент в массиве будет случайным числом в интервале от 0.0 (включительно) до 1.0 (исключительно). 
# Если вам нужны случайные числа из другого распределения, такого как нормальное (гауссовское), 
# вы можете использовать numpy.random.randn для генерации чисел с нормальным распределением.

# Синтаксис:
# numpy.random.rand(d0, d1, ..., dn)

# d0, d1, ..., dn: Размеры возвращаемого массива.

# Генерация массива случайных чисел размером 2x3
random_array = np.random.rand(2, 3)

print("Случайный массив:")
print(random_array)

Случайный массив:
[[0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449]]


In [222]:
# randn:

# Описание: Генерирует числа из стандартного нормального распределения (среднее 0, стандартное отклонение 1).

# Синтаксис:
# numpy.random.randn(d0, d1, ..., dn)

# d0, d1, ..., dn: Размеры возвращаемого массива.

# Генерация массива случайных чисел размером 2x3 из стандартного нормального распределения
random_array = np.random.randn(2, 3)

print("Случайный массив из стандартного нормального распределения:")
print(random_array)

Случайный массив из стандартного нормального распределения:
[[-0.60025385  0.94743982  0.291034  ]
 [-0.63555974 -1.02155219 -0.16175539]]


In [223]:
# randint:

# Описание: Генерирует случайные целые числа из дискретного равномерного распределения в указанном диапазоне.

# Синтаксис:
# numpy.random.randint(low, high=None, size=None, dtype='l')

# low: Нижняя граница диапазона.
# high: Верхняя граница диапазона (не включается).
# size: Форма возвращаемого массива.
# dtype: Тип данных возвращаемого массива.

# Генерация массива случайных целых чисел в диапазоне от 1 до 10 (10 не включено) размером 3x3
random_integers = np.random.randint(1, 10, size=(3, 3))

print("Случайный массив целых чисел:")
print(random_integers)

Случайный массив целых чисел:
[[8 3 1]
 [4 2 8]
 [4 2 6]]


In [ ]:
# random_sample:

# Описание: Генерирует случайные числа с плавающей точкой из равномерного распределения в интервале от 0.0 до 1.0 - [0.0, 1.0)

# Синтаксис:
# numpy.random.random_sample(size=None) (или numpy.random.random(size=None)):

# size: Форма возвращаемого массива.

# Генерация массива случайных чисел с плавающей точкой размером 3x3
random_floats = np.random.random_sample(size=(3, 3))

print("Случайный массив чисел с плавающей точкой:")
print(random_floats)

Случайный массив чисел с плавающей точкой:
[[0.20794166 0.56770033 0.03131329]
 [0.84228477 0.44975413 0.39515024]
 [0.92665887 0.727272   0.32654077]]


In [225]:
# choice:

# Описание: Случайным образом выбирает элементы из заданного массива или последовательности. 
# Может принимать на вход массив, последовательность или число, и возвращает случайный выбор из переданных значений.

# Синтаксис:
# numpy.random.choice(a, size=None, replace=True, p=None)

# a: Входной массив или последовательность.
# size: Форма возвращаемого массива.
# replace: Булево значение, указывающее, следует ли выполнять выборку с заменой.
# p: Вероятности соответствующих элементов в a.

# Создание массива и выбор случайных элементов из него
choices = np.random.choice(['apple', 'banana', 'cherry', 'date'], size=3)

print("Случайный выбор из массива:", choices)

Случайный выбор из массива: ['banana' 'cherry' 'date']


In [227]:
# integers:

# Описание: Генерирует случайные целые числа из указанного диапазона.

# Синтаксис:
# numpy.random.integers(low, high=None, size=None, dtype=int)

# low: Нижняя граница диапазона.
# high: Верхняя граница диапазона (не включается).
# size: Форма возвращаемого массива.
# dtype: Тип данных возвращаемого массива.

# Генерация случайных целых чисел в диапазоне [0, 10)
random_integers = np.random.choice(10, size=5)

print("Случайные целые числа:", random_integers)

Случайные целые числа: [8 7 4 1 4]


In [228]:
# permutation:

# Описание: Возвращает случайную перестановку последовательности или перестановку диапазона.

# Синтаксис:
# numpy.random.permutation(x)

# x: Последовательность (массив), которую нужно переставить.

# Создание массива
arr = np.array([1, 2, 3, 4, 5])

# Перестановка элементов массива
shuffled_arr = np.random.permutation(arr)

print("Исходный массив:", arr)
print("Перемешанный массив:", shuffled_arr)

Исходный массив: [1 2 3 4 5]
Перемешанный массив: [5 3 4 1 2]


In [229]:
# shuffle:

# Описание: Производит случайную перестановку элементов последовательности на месте (не создает новую последовательность).

# Синтаксис:
# numpy.random.shuffle(x)

# x: Последовательность (массив), которую нужно переставить.

# Создание массива
arr = np.array([1, 2, 3, 4, 5])

# Перемешивание элементов массива на месте
np.random.shuffle(arr)

print("Перемешанный массив:", arr)

Перемешанный массив: [2 4 1 3 5]


## Генерация случайных данных с различными распределениями

In [239]:
# random_sample :

# Описание: Генерирует случайные числа с плавающей точкой из равномерного распределения в интервале от 0.0 до 1.0.

# Синтаксис:
# numpy.random.random_sample(size=None) (или numpy.random.random(size=None)):

# size: Форма возвращаемого массива.

# Генерация массива случайных чисел с плавающей точкой размером 3x3
random_floats = np.random.random_sample(size=(3, 3))

print("Случайный массив чисел с плавающей точкой:")
print(random_floats)

Случайный массив чисел с плавающей точкой:
[[0.93563499 0.78534065 0.66898825]
 [0.58068662 0.37228277 0.94013344]
 [0.97366384 0.28392097 0.30536386]]


In [230]:
# uniform:

# Описание: Генерирует случайные числа из равномерного распределения на указанном интервале.

# Синтаксис:
# numpy.random.uniform(low=0.0, high=1.0, size=None)

# low: Нижняя граница интервала.
# high: Верхняя граница интервала.
# size: Форма возвращаемого массива.

# Генерация 5 случайных чисел в интервале [0, 1)
random_numbers = np.random.uniform(low=0.0, high=1.0, size=5)

print("Случайные числа из равномерного распределения:", random_numbers)

Случайные числа из равномерного распределения: [0.01563641 0.42340148 0.39488152 0.29348817 0.01407982]


In [231]:
# standard_normal:

# Описание: Генерирует случайные числа из стандартного нормального распределения (среднее 0, стандартное отклонение 1).

# Синтаксис:
# numpy.random.standard_normal(size=None)

# size: Форма возвращаемого массива.

# Генерация 5 случайных чисел из стандартного нормального распределения
random_numbers = np.random.standard_normal(size=5)

print("Случайные числа из стандартного нормального распределения:", random_numbers)

Случайные числа из стандартного нормального распределения: [ 0.63630511 -0.90672067  0.47604259  1.30366127  0.21158701]


In [232]:
# binomial:

# Описание: Генерирует случайные числа из биномиального распределения. 
# Биномиальное распределение моделирует количество успехов в серии независимых бинарных экспериментов, 
# где каждый эксперимент имеет два возможных исхода (успех или неудача).

# Синтаксис:
# numpy.random.binomial(n, p, size=None)

# n: Количество испытаний.
# p: Вероятность успеха в каждом испытании.
# size: Форма возвращаемого массива.

# Генерация 5 случайных чисел из биномиального распределения
# с параметрами n (количество экспериментов) и p (вероятность успеха)
binomial_numbers = np.random.binomial(n=10, p=0.5, size=5)

print("Случайные числа из биномиального распределения:", binomial_numbers)

Случайные числа из биномиального распределения: [7 7 5 3 4]


In [233]:
# normal:

# Описание: Генерирует случайные числа из нормального (гауссова) распределения.

# Синтаксис:
# numpy.random.normal(loc=0.0, scale=1.0, size=None)

# loc: Среднее значение распределения.
# scale: Стандартное отклонение распределения.
# size: Форма возвращаемого массива.

# Генерация 5 случайных чисел из нормального распределения
# со средним значением 0 и стандартным отклонением 1
random_numbers = np.random.normal(loc=0, scale=1, size=5)

print("Случайные числа из нормального распределения:", random_numbers)

Случайные числа из нормального распределения: [ 0.59704465  1.21217234  1.2334968  -1.57415529  0.63795294]


In [234]:
# beta:

# Описание: Генерирует случайные числа из бета-распределения. 
# Бета-распределение является непрерывным распределением на интервале [0, 1].

# Синтаксис:
# numpy.random.beta(a, b, size=None)

# a: Параметр формы 1.
# b: Параметр формы 2.
# size: Форма возвращаемого массива.

# Параметры альфа и бета для бета-распределения
alpha = 2
beta = 5

# Генерация 10 случайных чисел из бета-распределения
beta_numbers = np.random.beta(alpha, beta, size=10)

# Вывод результатов
print("Сгенерированные случайные числа из бета-распределения:")
print(beta_numbers)

Сгенерированные случайные числа из бета-распределения:
[0.54206088 0.45576536 0.31985712 0.3777077  0.11739454 0.54434102
 0.44793979 0.0981224  0.25273158 0.06105195]


In [236]:
# chisquare:

# Описание: Генерирует случайные числа из хи-квадрат распределения.

# Синтаксис:
# numpy.random.chisquare(df, size=None)

# df: Число степеней свободы.
# size: Форма возвращаемого массива.

# Параметр k (степени свободы) для распределения хи-квадрат
k = 3

# Генерация 10 случайных чисел из распределения хи-квадрат
chisquare_numbers = np.random.chisquare(k, size=10)

# Вывод результатов
print(f"Сгенерированные случайные числа из распределения хи-квадрат с k={k}:")
print(chisquare_numbers)

Сгенерированные случайные числа из распределения хи-квадрат с k=3:
[10.7933604   6.13396863  4.28523489  1.23521771  6.07765441  1.5890751
  9.50003111  2.51265752  4.25387117  0.82237992]


In [238]:
# gamma:

# Описание: Генерирует случайные числа из гамма-распределения.

# Синтаксис:
# numpy.random.gamma(shape, scale=1.0, size=None)

# shape: Параметр формы.
# scale: Масштабный параметр.
# size: Форма возвращаемого массива.

# Параметры формы и масштаба для гамма-распределения
shape = 2
scale = 2

# Генерация 10 случайных чисел из гамма-распределения
gamma_numbers = np.random.gamma(shape, scale, size=10)

# Вывод результатов
print(f"Сгенерированные случайные числа из гамма-распределения с shape={shape} и scale={scale}:")
print(gamma_numbers)

Сгенерированные случайные числа из гамма-распределения с shape=2 и scale=2:
[4.56508669 1.60468756 5.40535917 1.96487984 2.15813807 3.49819127
 4.8034233  6.49656745 1.27058517 6.32034577]
