In [1]:
import numpy as np

In [2]:
print(np.linspace(-5, 5, 10))

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [3]:
# a, b = map(int, input().split())
a, b = 2, 9
arr = np.array(list(i for i in range(a, b + 1) if i % 3 == 0))
print(arr)
arr = np.arange(a, b + 1)
arr = arr[arr % 3 == 0]
print(arr)

[3 6 9]
[3 6 9]


In [4]:
np.random.seed(32)
# n = int(input())
n = 6
arr = np.random.rand(n)
arr

array([0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ,
       0.81620514])

In [5]:
n = 3
arr = []
for i in range(0, n + 100): 
    if i > 1: 
        for j in range(2, i):
            if(i % j) == 0: 
                break 
        else:
            if len(arr) < n:
                arr.append(i)
print(arr)

[2, 3, 5]


In [6]:
n = 10
i = 2
arr = []
while len(arr) < n:
    for j in range(2, i):
        if(i % j) == 0: 
                break
    else:
         arr.append(i)
    i += 1
print(arr)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [7]:
# a, b = map(float, input().split())
a, b = 0.22, 2.0

np.round(np.arange(-1*a, a+0.001, b), 1)

array([-0.2])

In [8]:
b = 5
arr = np.linspace(0, np.pi, b)
arr

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [9]:
import numpy as np
arr=np.array([1, 2, '3', {'key1':66}])

print(arr.dtype)
print(arr.size)
print(arr.shape)

object
4
(4,)


In [10]:
# 3, 4, 2
arr = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],

                [[9, 10], [11, 12], [13, 14], [15, 16]],
                
                [[17, 18], [19, 20], [21, 22], [23, 24]]])
arr.shape

(3, 4, 2)

In [11]:
arr = np.empty([256, 256, 3])
arr.shape

(256, 256, 3)

In [12]:
arr1, arr2, arr3 = np.array_split(arr, 3, axis=2)
print(arr1.shape, arr2.shape, arr3.shape)

(256, 256, 1) (256, 256, 1) (256, 256, 1)


In [13]:
arr1 = np.squeeze(arr1)
arr2 = np.squeeze(arr2)
arr3 = np.squeeze(arr3)

arr1 = np.expand_dims(arr1, axis=0)
arr2 = np.expand_dims(arr2, axis=0)
arr3 = np.expand_dims(arr3, axis=0)

np.concatenate([arr1, arr2, arr3]).shape

(3, 256, 256)

# 1.5 Добавление и удаление элементов.

In [14]:
data = np.empty([1000, 28, 28])
arr1 = np.empty([50, 28, 28])
arr2 = np.empty([28, 28])

print(f'Размер data: {data.shape}')
print(f'Размер arr1: {arr1.shape}')
print(f'Размер arr2: {arr2.shape}')

Размер data: (1000, 28, 28)
Размер arr1: (50, 28, 28)
Размер arr2: (28, 28)


In [15]:
# Добавление элементов

new_data1 = np.append(data, arr1) # - одномерный массив
new_data2 = np.append(data, arr1, axis=0) # - многомерный, объединенрие по нулевой оси
new_data3 = np.append(arr1, arr1, axis=2) # - многомерный, объединенрие по второй оси
new_data4 = np.append(data, arr2[np.newaxis], axis=0) # - добавление одного элемента с предварительным добавлением оси

print(f'Размер new_data1: {new_data1.shape}')
print(f'Размер new_data2: {new_data2.shape}')
print(f'Размер new_data3: {new_data3.shape}')
print(f'Размер new_data4: {new_data4.shape}')

Размер new_data1: (823200,)
Размер new_data2: (1050, 28, 28)
Размер new_data3: (50, 28, 56)
Размер new_data4: (1001, 28, 28)


In [16]:
# Удаление элементов по индексу

print(new_data4.shape)

new_data4 = np.delete(new_data4, 1000, axis=0)

print(new_data4.shape)

(1001, 28, 28)
(1000, 28, 28)


In [17]:
# В программе созданы два массива с картинками 28 на 28 пикселей. 
# Массивы записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28), а массив arr_2 имеет размер (5, 28, 28). 
# К картинкам из arr_1 добавьте картинки из arr_2.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28])
arr_2 = np.empty([5, 28, 28])

new_arr = np.append(arr_1, arr_2, axis=0)

new_arr.shape

(15, 28, 28)

In [18]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28), 10 картинок 28 на 28 пикселей. 
# Массив arr_2 имеет размер (28, 28), содержит одну картинку. 
# К картинкам из arr_1 добавьте картинку arr_2.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28])
arr_2 = np.empty([28, 28])

new_arr = np.append(arr_1, arr_2[np.newaxis], axis=0)

new_arr.shape

(11, 28, 28)

In [19]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28, 2), 10 картинок 28 на 28 пикселей с двумя цветовыми каналами G и B. 
# Массив arr_2 имеет размер (10, 28, 28, 1), 10 картинок 28 на 28 пикселей с одним цветовым каналом R. 
# Добавьте один массив к другому так, чтобы получить 10 картинок с тремя цветовыми каналами RGB.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28, 2])
arr_2 = np.empty([10, 28, 28, 1])

new_arr = np.append(arr_2, arr_1, axis=3) # - arr_2 + arr_1, потому что RGB (не GBR)

new_arr.shape

(10, 28, 28, 3)

In [20]:
# В программе создан массив записан в переменную arr. Удалите последний элемент на нулевой оси.

# Результат запишите в переменную new_arr.

arr = np.empty([10, 28, 28])

print(arr.shape)

new_arr = np.delete(arr, -1, axis=0)

print(new_arr.shape)

(10, 28, 28)
(9, 28, 28)


In [21]:
# В программе создан массив записан в переменную arr. Удалите элементы с индексами 1, 3, 5 на последней оси.

# Результат запишите в переменную new_arr.

arr = np.empty([10, 28, 28])

print(arr.shape)

new_arr = np.delete(arr, [1, 3, 5], axis=-1)

print(new_arr.shape)

(10, 28, 28)
(10, 28, 25)


In [22]:
delete_items = (1, 3, 5)
new_arr = np.delete(arr=arr, obj=delete_items, axis=arr.ndim - 1)

print(new_arr.shape)

(10, 28, 25)


In [23]:
img = np.random.randint(0, 255, 28*28).reshape([28, 28]) # - генерация картинки 28 на 28 пикселей
print(f'Размер картинки {img.shape}')

Размер картинки (28, 28)


In [24]:
# Множественное добавление картинок в массив картинок

# Копирует каждый раз существующий массив, выделяя память на него, и добавляет к нему новый элемент (долго)

arr = np.empty([100, 28, 28]) # - имеется массив 100 картинок

for i in range(10):
    img = np.random.randint(0, 255, 28*28).reshape([28, 28])
    arr = np.append(arr, img[np.newaxis], axis=0)

print(arr.shape)

(110, 28, 28)


In [25]:
# Множественное добавление картинок в массив картинок

# Изменяет существующий массив (быстрее)

arr = np.empty([100, 28, 28]) # - имеется массив 100 картинок
arr.resize([100 + 10, 28, 28]) # - расширение массива (10 элементов заполняется нулями)

for i in range(10):
    img = np.random.randint(0, 255, 28*28).reshape([28, 28])
    arr[100 + i] = img

print(arr.shape)

(110, 28, 28)


# 1.6 Индексация и срезы.

In [26]:
# В программе создан массив с наборам картинок и записан в переменную arr. 
# Размер массива (10, 28, 28), 10 картинок 28 на 28 пикселей​​. 

# Картинку с индексом 5 запишите в переменную img.

arr = np.arange(7840).reshape(10, 28 ,28)

print(arr.shape)

img = arr[5]

print(img.shape)

(10, 28, 28)
(28, 28)


In [27]:
# В программе создан массив содержащий координаты точек и записан в переменную coord. 
# Размер массива (10, 3), 10 точек с тремя координатами X, Y, Z​​. 
# Получите значение координаты X у точки с индексом 4.

# Результат запишите в переменную coord_X.

coord = np.arange(30).reshape(10, 3)

print(coord.shape)

coord_X = coord[4, 0]

print(coord_X)

(10, 3)
12


In [28]:
# В программе создан массив с наборам картинок и записан в переменную img. 
# Размер массива (100, 28, 28), 100 картинок 28 на 28 пикселей​​. 
# Получите изображения с индексами с 1 по 10 включительно. 

# Результат запишите в переменную new_img.

img = np.arange(100 * 28 * 28).reshape(100, 28, 28)

print(img.shape)

new_img = img[1:11, :, :]
new_img = img[1:11]

print(new_img.shape)

(100, 28, 28)
(10, 28, 28)


In [29]:
# В программе создан массив с наборам картинок и записан в переменную img. 
# Размер массива (100, 28, 28), 100 картинок 28 на 28 пикселей​​. 
# Получите изображения с индексами с 1 по 50 включительно, с шагом 3. 

# Результат запишите в переменную new_img.

img = np.arange(100 * 28 * 28).reshape(100, 28, 28)

print(img.shape)

new_img = img[1:51:3]

print(new_img.shape)

(100, 28, 28)
(17, 28, 28)


In [30]:
# В программе создан массив с наборам картинок и записан в переменную img. 
# Размер массива (100, 28, 28), 100 картинок 28 на 28 пикселей​​. 
# Разделите массив на четыре равные части, по 25 картинок в каждом.

# Результат запишите в переменные img_1, img_2, img_3, img_4.

img = np.arange(100 * 28 * 28).reshape(100, 28, 28)

img_1 = img[:25]
img_2 = img[25:50]
img_3 = img[50:75]
img_4 = img[75:100]

img_1, img_2, img_3, img_4 = [img[i: i + 25] for i in range(0, 76, 25)]

img_1, img_2, img_3, img_4 = np.array_split(img, 4)

In [31]:
# В программе создан массив с картинкой и записан в переменную img. 
# Размер массива (256, 256, 3), картинка 256 на 256 пикселей​​ с тремя цветовыми каналами RGB. 
# Получите фрагмент картинки с размерами по высоте начиная с индекса 10 до 100 включительно, 
# по ширине начиная с индекса 50 до 110 включительно. 

# Нулевая ось - высота\строки.
# Первая ось - ширина\столбцы.

# Фрагмент картинки запишите в переменную new_img.

img = np.arange(256 * 256 * 3).reshape(256, 256, 3)

new_img = img[10:101, 50:111]

In [32]:
# В программе создан массив с картинкой и записан в переменную img. 
# Размер массива (256, 256, 3), картинка 256 на 256 пикселей​​ с тремя цветовыми каналами RGB. 
# Получите фрагмент картинки высотой 50 пикселей и шириной 100 пикселей, 
# начиная с пикселя индекс которого 10 по высоте и 20 по ширине.

# Нулевая ось - высота\строки.
# Первая ось - ширина\столбцы.

# Фрагмент картинки запишите в переменную new_img.

img = np.arange(256 * 256 * 3).reshape(256, 256, 3)

new_img = img[:50, :100]
print(new_img.shape)

new_img = img[10:60, 20:120]
print(new_img.shape)

(50, 100, 3)
(50, 100, 3)


In [33]:
# В программе создан массив с картинкой и записан в переменную img. 
# Размер массива (256, 256, 3), картинка 256 на 256 пикселей​​ с тремя цветовыми каналами RGB. 
# Получите фрагмент картинки высотой 50 пикселей, шириной 100 пикселей, 
# начиная с пикселя индекс которого 100 по высоте и 50 по ширине, только R и B цветовые каналы.

# Нулевая ось - высота\строки.
# Первая ось - ширина\столбцы.

# Фрагмент картинки запишите в переменную new_img.

img = np.arange(256 * 256 * 3).reshape(256, 256, 3)

new_img = img[100: 100+50, 50: 50+100, [0, 2]]
print(new_img.shape)

new_img = img[100: 100+50, 50: 50+100, [True, False, True]]
print(new_img.shape)


(50, 100, 2)
(50, 100, 2)


In [34]:
# Создайте массив размером (5, 5) состоящий из нулей и типом данных int8. 
# Строки массива заполните единицами с шагом в два.

# Результат запишите в переменную new_arr.

arr = np.zeros([5, 5], dtype='int8')
print(arr)

print()

new_arr = arr.copy()
new_arr[:, ::2] = 1
print(new_arr)

print()

print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [35]:
# Создайте массив размером (5, 5) состоящий из нулей и типом данных int8. 
# Элементы строк заполните единицами начиная с индекса 1 и с шагом в два.

# Результат запишите в переменную new_arr.

arr = np.zeros([5, 5], dtype='int8')
print(arr)

print()

new_arr = arr.copy()
new_arr[:, 1::2] = 1
print(new_arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


In [36]:
# Создайте массив размером (5, 5) состоящий из единиц и типом данных int8. 
# Элементы массива заполните нулями в шахматном порядке.

arr = np.ones([5, 5], dtype='int8').ravel()
print(arr)

print()

new_arr = arr.copy()
new_arr[::2] = 0
new_arr = new_arr.reshape(5, 5)

print(new_arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [37]:
new_arr = np.ones([5, 5], dtype=np.int8)
print(new_arr)
print()

new_arr[::2, ::2] = 0
print(new_arr)
print()

new_arr[1::2, 1::2] = 0
print(new_arr)
print()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 0 1 0]
 [1 1 1 1 1]
 [0 1 0 1 0]
 [1 1 1 1 1]
 [0 1 0 1 0]]

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]



In [38]:
# В программе создан массив размером (5, 5) с типом данных np.int8 и записан в переменную arr. 
# Получите массив с внешним отступом в один элемент заполненный нулями.

arr = np.random.randint(1, 100, 5 * 5, dtype='int8').reshape(5, 5)
print(arr)
print()

new_arr = np.zeros(np.array(arr.shape) + (2, 2), dtype='int8')
print(new_arr)

[[22  4 90 52 27]
 [55 32 23 64  7]
 [83 81 93 67 38]
 [45 31 26 88 89]
 [94 52 62 60 94]]

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [39]:
new_arr[1:len(new_arr) - 1, 1: len(new_arr) - 1] = arr
new_arr

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 22,  4, 90, 52, 27,  0],
       [ 0, 55, 32, 23, 64,  7,  0],
       [ 0, 83, 81, 93, 67, 38,  0],
       [ 0, 45, 31, 26, 88, 89,  0],
       [ 0, 94, 52, 62, 60, 94,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [40]:
new_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
new_arr

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 22,  4, 90, 52, 27,  0],
       [ 0, 55, 32, 23, 64,  7,  0],
       [ 0, 83, 81, 93, 67, 38,  0],
       [ 0, 45, 31, 26, 88, 89,  0],
       [ 0, 94, 52, 62, 60, 94,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [41]:
# В программе создан массив размером (10, 10) с типом данных np.int8 и записан в переменную arr. 
# Получите массив с внутренним отступом заполненном нулями. 
# Сверху отступ в одну строку, снизу три строки, справа две, а слева четыре.

arr = np.random.randint(1, 100, 10 * 10, dtype='int8').reshape(10, 10)
print(arr)
print()

new_arr = arr.copy()

new_arr[1] = 0

new_arr[1, :4, 8:10] = 0       #Здесь  [выбираю вторую строку,       беру с 0 по 3 элементы,         беру с 8 по 9 элементы]
new_arr[2, :4, 8:10] = 0
new_arr[3, :4, 8:10] = 0
new_arr[4, :4, 8:10] = 0
new_arr[5, :4, 8:10] = 0
new_arr[6, :4, 8:10] = 0

new_arr[0, :10] = 0
new_arr[7, :10] = 0
new_arr[8, :10] = 0
new_arr[9, :10] = 0

arr = new_arr
print(new_arr)

[[ 9 58 30 54 12 60 46 37 53 22]
 [90 91  1  6 34 58 97 92 13 61]
 [22 28 13 61 34 63 57 92  3 57]
 [65 92  5 99 76 18 48 30  6 88]
 [52 69 32 74 74 10 70 59  6  3]
 [24 69 59 12 44 91 80 33 92 87]
 [18  1 37 40 76 64 98 94 16 50]
 [67 16 40  3 41 71 77 34 11 17]
 [25  6 16 73 71 15 30 96 86 26]
 [89 58 74  6  3 85 15 91 28 10]]



IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [202]:
arr = np.random.randint(1, 100, 10 * 10, dtype='int8').reshape(10, 10)
print(arr)
print()

new_arr = arr.copy()

new_arr[0] = 0
new_arr[-3:] = 0
new_arr[:, :4] = 0
new_arr[:, -2:] = 0

new_arr

[[47 22 73 27 72 35 48 96 55 16]
 [25 88 64 14 24 88 20 86 39 63]
 [35 25 93 75 86 86 80 15 41 11]
 [81  4 85 91 79 99 33  6 28 12]
 [11 71 71 68 49 33 19 93 43 78]
 [45 43 48 45 35 50 88 85 65 37]
 [76 27 38  2 62 38 72 49 58  8]
 [68 62 40 74 52 61 80 51  9 63]
 [96  1 83 97 37 17 45 48 76 39]
 [10 55 70 36 81  5 87 67 63 76]]



array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 24, 88, 20, 86,  0,  0],
       [ 0,  0,  0,  0, 86, 86, 80, 15,  0,  0],
       [ 0,  0,  0,  0, 79, 99, 33,  6,  0,  0],
       [ 0,  0,  0,  0, 49, 33, 19, 93,  0,  0],
       [ 0,  0,  0,  0, 35, 50, 88, 85,  0,  0],
       [ 0,  0,  0,  0, 62, 38, 72, 49,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [203]:
new_arr = np.zeros((10,10), dtype=np.int8)
new_arr[1:7,4:8] = arr[1:7,4:8]
new_arr

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 24, 88, 20, 86,  0,  0],
       [ 0,  0,  0,  0, 86, 86, 80, 15,  0,  0],
       [ 0,  0,  0,  0, 79, 99, 33,  6,  0,  0],
       [ 0,  0,  0,  0, 49, 33, 19, 93,  0,  0],
       [ 0,  0,  0,  0, 35, 50, 88, 85,  0,  0],
       [ 0,  0,  0,  0, 62, 38, 72, 49,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [205]:
new_arr = np.zeros_like(arr)
top, right, bottom, left = 1, 2, 3, 4
new_arr[top:-bottom, left:-right] = arr[top:-bottom, left:-right]
new_arr

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 24, 88, 20, 86,  0,  0],
       [ 0,  0,  0,  0, 86, 86, 80, 15,  0,  0],
       [ 0,  0,  0,  0, 79, 99, 33,  6,  0,  0],
       [ 0,  0,  0,  0, 49, 33, 19, 93,  0,  0],
       [ 0,  0,  0,  0, 35, 50, 88, 85,  0,  0],
       [ 0,  0,  0,  0, 62, 38, 72, 49,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [226]:
# В программе создан массив и записан в переменную arr
# С помощью списочной индексации получите массив:
# array(['x_1', 'y_1', 'x_2', 'y_2', 'x_3', 'y_3'])

arr = np.array(['x_1', 'x_2', 'y_3', 'x_3', 'y_2', 'y_1'])
new_arr = np.empty(0)

for i in range(len(arr) // 2):
    new_arr = np.append(new_arr, arr[[i, -i - 1]])
new_arr[-1], new_arr[-2] = new_arr[-2], new_arr[-1]
new_arr.shape = (3, 2)
new_arr

array([['x_1', 'y_1'],
       ['x_2', 'y_2'],
       ['x_3', 'y_3']], dtype='<U32')

In [227]:
arr = np.array(['x_1', 'x_2', 'y_3', 'x_3', 'y_2', 'y_1'])
new_arr = arr[np.array([0, 5, 1, 4, 3, 2])]
new_arr = new_arr.reshape(3,2)
new_arr

array([['x_1', 'y_1'],
       ['x_2', 'y_2'],
       ['x_3', 'y_3']], dtype='<U3')

# 2.1 Математические операции. Транслирование массивов.

In [238]:
arr1 = np.random.randint(0, 5, 10).reshape(5, 2)
arr2 = np.random.randint(0, 5, 10).reshape(5, 2)

display(arr1, arr2)
display(arr1 + arr2)

array([[1, 2],
       [0, 1],
       [0, 0],
       [1, 1],
       [4, 1]])

array([[0, 0],
       [2, 2],
       [2, 3],
       [3, 1],
       [2, 2]])

array([[1, 2],
       [2, 3],
       [2, 3],
       [4, 2],
       [6, 3]])

In [241]:
# В программе создан массив и записан в переменную arr. Умножьте массив на 10.

arr = np.arange(1, 11)
print(arr)

new_arr = arr * 10
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# Даны размеры массивов. Какие из указанных массивов, благодаря транслированию, можно считать согласованными?

# (3, 2) - (2)                      +
# (4, 1, 8) - (4, 2)                -
# (16, 28, 28, 3) - (28, 28, 1)     +
# (2, 3, 4) - (1, 4)                +
# (5, 3, 7) - (3, 7)                +
# (10, 5) - (1)                     +

In [262]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (5, 3, 7), а массив arr_2 имеет размер (5). 
# Умножьте массив arr_1 на arr_2.

arr1 = np.empty(5 * 3 * 7).reshape(5, 3, 7)
arr2 = np.empty(5)
print(arr1.shape)
print(arr2.shape)

new_arr = arr1 * arr2[:, np.newaxis, np.newaxis]
print(new_arr.shape)

(5, 3, 7)
(5,)
(5, 3, 7)


In [259]:
arr1 = np.empty(5 * 3 * 7).reshape(5, 3, 7)
arr2 = np.empty(5)
print(arr1.shape)
print(arr2.shape)

arr2.shape = (5, 1, 1)
new_arr = arr1 * arr2
print(new_arr.shape)

(5, 3, 7)
(5,)
(5, 3, 7)


In [264]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (5, 3, 7), а массив arr_2 имеет размер (7). 
# Прибавьте  к массиву arr_1 массив arr_2.

arr1 = np.empty(5 * 3 * 7).reshape(5, 3, 7)
arr2 = np.empty(7)
print(arr1.shape)
print(arr2.shape)

arr2.shape = (1, 1, 7)
new_arr = arr1 + arr2
print(new_arr.shape)

(5, 3, 7)
(7,)
(5, 3, 7)


In [268]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (5, 3, 7), а массив arr_2 имеет размер (5, 7). 
# Поделите массив arr_1 на arr_2.

arr1 = np.empty(5 * 3 * 7).reshape(5, 3, 7)
arr2 = np.empty(5 * 7).reshape(5, 7)
print(arr1.shape)
print(arr2.shape)

new_arr = np.divide(arr1, arr2[:, np.newaxis, :])
print(new_arr.shape)

(5, 3, 7)
(5, 7)
(5, 3, 7)


In [276]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (6, 4, 3), а массив arr_2 имеет размер (4). 
# Умножьте массив arr_1 на arr_2.

arr1 = np.empty(6 * 4 * 3).reshape(6, 4, 3)
arr2 = np.empty(4)
print(arr1.shape)
print(arr2.shape)

new_arr = arr1 * arr2[:, np.newaxis]
print(new_arr.shape)

(6, 4, 3)
(4,)
(6, 4, 3)


In [284]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (6, 4, 3), а массив arr_2 имеет размер (6, 4). 
# Умножьте массив arr_1 на arr_2.

arr1 = np.empty(6 * 4 * 3).reshape(6, 4, 3)
arr2 = np.empty(6 * 4).reshape(6, 4)
print(arr1.shape)
print(arr2.shape)

new_arr = arr1 * arr2[:, :, np.newaxis]
print(new_arr.shape)

new_arr = arr1 * np.expand_dims(arr2, axis=-1)
print(new_arr.shape)

(6, 4, 3)
(6, 4)
(6, 4, 3)
(6, 4, 3)


In [290]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (5, 3), а массив arr_2 имеет размер (4, 2). 
# Прибавьте к массиву arr_1 массив arr_2.

arr1 = np.empty(5 * 3).reshape(5, 3)
arr2 = np.empty(4 * 2).reshape(4, 2)
print(arr1.shape)
print(arr2.shape)

new_arr = arr1[:, :, np.newaxis, np.newaxis] + arr2
print(new_arr.shape)

(5, 3)
(4, 2)
(5, 3, 4, 2)


In [292]:
# В программе создан массив размером (10, 2) и записан в переменную arr. 
# Массив содержит 10 точек с двумя координатами x и y. Массив loss имеет размер (10), содержит погрешность в измерениях координат для каждой точки. 
# Из координат в массиве arr вычтите погрешность.

arr = np.empty(10 * 2).reshape(10, 2)
loss = np.empty(10)
print(arr.shape)
print(loss.shape)

new_arr = arr - loss[:, np.newaxis]
print(new_arr.shape)

(10, 2)
(10,)
(10, 2)


In [301]:
# В программе создан массив размером (5, 3) и записан в переменную arr. 
# Массив содержит 10 точек с тремя координатами x, y и z. Массив loss имеет размер (5), содержит погрешность в измерениях координаты y. 
# В массиве arr исправьте значение координаты y вычев из нее погрешность.

arr = np.arange(1, 16).reshape(5, 3)
loss = np.arange(5)
display(arr, loss)

arr[:, 1] = arr[:, 1] - loss
display(arr)

(10, 3)
(10,)
(10, 3)


In [327]:
# В программе создан массив размером (10, 4, 2) и записан в переменную arr. 
# Массив содержит 10 наблюдений, в которых четырьмя разными методами измерялись координаты x и y. 
# Массив loss имеет размер (4), содержит погрешность в измерениях каждого метода. 
# В массиве arr исправьте значение координат вычев из них погрешность.

arr = np.arange(2 * 3 * 2).reshape(2, 3, 2)
loss = np.array([2, 2, 2])
display(arr, loss)

new_arr = arr - loss[np.newaxis, :, np.newaxis]
display(new_arr)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

array([2, 2, 2])

array([[[-2, -1],
        [ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7],
        [ 8,  9]]])

In [383]:
# Создан массив с размером (16, 28, 28), 16 картинок 28 на 28 пикселей в градации серого. 
# В массиве взят срез по первой и второй оси и записан в переменную arr. 
# Срез имеет размер (16, 3, 3). 
# Умножьте срез на массив kernels с размером (64, 3, 3), 64 ядра размером 3 на 3 пикселя.

arr = np.empty(16 * 3 * 3).reshape(16, 3, 3)
print(arr.shape)
kernels = np.empty(64 * 3 * 3).reshape(64, 3, 3)
print(kernels.shape)

new_arr = arr[np.newaxis, :, :, :] * kernels[:, np.newaxis, :, :]
print(new_arr.shape)

(16, 3, 3)
(64, 3, 3)
(64, 16, 3, 3)


C:\Users\kuche\AppData\Local\Temp\ipykernel_3416\961295144.py:11: RuntimeWarning: overflow encountered in multiply
  new_arr = arr[np.newaxis, :, :, :] * kernels[:, np.newaxis, :, :]


In [392]:
# Создан массив с размером (16, 28, 28, 3), 16 картинок 28 на 28 пикселей с тремя цветовыми каналами RGB. 
# В массиве взят срез по первой и второй оси и записан в переменную arr. 
# Срез имеет размер (16, 3, 3, 3). 
# Умножьте срез на массив kernels с размером (32, 3, 3), 32 ядра размером 3 на 3 пикселя.

arr = np.empty(16 * 3 * 3 * 3).reshape(16, 3, 3, 3)
print(arr.shape)
kernels = np.empty(32 * 3 * 3).reshape(32, 3, 3)
print(kernels.shape)

new_arr = arr[np.newaxis, :, :, :, :] * kernels[ :, np.newaxis, np.newaxis, :, :]
print(new_arr.shape)

(16, 3, 3, 3)
(32, 3, 3)
(32, 16, 3, 3, 3)


C:\Users\kuche\AppData\Local\Temp\ipykernel_3416\4209547986.py:11: RuntimeWarning: overflow encountered in multiply
  new_arr = arr[np.newaxis, :, :, :, :] * kernels[ :, np.newaxis, np.newaxis, :, :]


In [395]:
arr = np.empty(16 * 3 * 3 * 3).reshape(16, 3, 3, 3)
print(arr.shape)
kernels = np.empty(32 * 3 * 3).reshape(32, 3, 3)
print(kernels.shape)

arr = arr.reshape(16, 1, 3, 3, 3)
kernels = kernels.reshape(1, 32, 3, 3, 1)

new_arr = arr * kernels
print(new_arr.shape)

(16, 3, 3, 3)
(32, 3, 3)
(16, 32, 3, 3, 3)


# 2.2 Математические функции.

In [56]:
arr = np.arange(2, 20).reshape([3, 3, 2])
arr

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [57]:
# Методы

print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.mean())
print(arr.std())

2
19
189
10.5
5.188127472091127


In [59]:
# Функции

print(np.abs(arr))
print()
print(np.max(arr))
print(np.log(arr))
# print(np.exp(arr))
print(np.max(np.exp(arr)))

[[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]]

 [[14 15]
  [16 17]
  [18 19]]]

19
[[[0.69314718 1.09861229]
  [1.38629436 1.60943791]
  [1.79175947 1.94591015]]

 [[2.07944154 2.19722458]
  [2.30258509 2.39789527]
  [2.48490665 2.56494936]]

 [[2.63905733 2.7080502 ]
  [2.77258872 2.83321334]
  [2.89037176 2.94443898]]]
178482300.96318725


In [60]:
print(np.sin(arr))
print(np.cos(arr))
print(np.arctan(arr))

[[[ 0.90929743  0.14112001]
  [-0.7568025  -0.95892427]
  [-0.2794155   0.6569866 ]]

 [[ 0.98935825  0.41211849]
  [-0.54402111 -0.99999021]
  [-0.53657292  0.42016704]]

 [[ 0.99060736  0.65028784]
  [-0.28790332 -0.96139749]
  [-0.75098725  0.14987721]]]
[[[-0.41614684 -0.9899925 ]
  [-0.65364362  0.28366219]
  [ 0.96017029  0.75390225]]

 [[-0.14550003 -0.91113026]
  [-0.83907153  0.0044257 ]
  [ 0.84385396  0.90744678]]

 [[ 0.13673722 -0.75968791]
  [-0.95765948 -0.27516334]
  [ 0.66031671  0.98870462]]]
[[[1.10714872 1.24904577]
  [1.32581766 1.37340077]
  [1.40564765 1.42889927]]

 [[1.44644133 1.46013911]
  [1.47112767 1.48013644]
  [1.48765509 1.49402444]]

 [[1.49948886 1.50422816]
  [1.50837752 1.5120405 ]
  [1.51529782 1.51821327]]]


In [67]:
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [74]:
np.argmax(arr)

3

In [73]:
a = np.where(arr == 4)
a

(array([3], dtype=int64),)

In [80]:
arr[np.argmin(np.abs(arr - 10))]

4

array([-9, -8, -7, -6])