In [2]:
import numpy as np

In [3]:
print(np.linspace(-5, 5, 10))

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [4]:
# a, b = map(int, input().split())
a, b = 2, 9
arr = np.array(list(i for i in range(a, b + 1) if i % 3 == 0))
print(arr)
arr = np.arange(a, b + 1)
arr = arr[arr % 3 == 0]
print(arr)

[3 6 9]
[3 6 9]


In [5]:
np.random.seed(32)
# n = int(input())
n = 6
arr = np.random.rand(n)
arr

array([0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ,
       0.81620514])

In [6]:
n = 3
arr = []
for i in range(0, n + 100): 
    if i > 1: 
        for j in range(2, i):
            if(i % j) == 0: 
                break 
        else:
            if len(arr) < n:
                arr.append(i)
print(arr)

[2, 3, 5]


In [7]:
n = 10
i = 2
arr = []
while len(arr) < n:
    for j in range(2, i):
        if(i % j) == 0: 
                break
    else:
         arr.append(i)
    i += 1
print(arr)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [8]:
# a, b = map(float, input().split())
a, b = 0.22, 2.0

np.round(np.arange(-1*a, a+0.001, b), 1)

array([-0.2])

In [9]:
b = 5
arr = np.linspace(0, np.pi, b)
arr

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [10]:
import numpy as np
arr=np.array([1, 2, '3', {'key1':66}])

print(arr.dtype)
print(arr.size)
print(arr.shape)

object
4
(4,)


In [11]:
# 3, 4, 2
arr = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],

                [[9, 10], [11, 12], [13, 14], [15, 16]],
                
                [[17, 18], [19, 20], [21, 22], [23, 24]]])
arr.shape

(3, 4, 2)

In [12]:
arr = np.empty([256, 256, 3])
arr.shape

(256, 256, 3)

In [13]:
arr1, arr2, arr3 = np.array_split(arr, 3, axis=2)
print(arr1.shape, arr2.shape, arr3.shape)

(256, 256, 1) (256, 256, 1) (256, 256, 1)


In [14]:
arr1 = np.squeeze(arr1)
arr2 = np.squeeze(arr2)
arr3 = np.squeeze(arr3)

arr1 = np.expand_dims(arr1, axis=0)
arr2 = np.expand_dims(arr2, axis=0)
arr3 = np.expand_dims(arr3, axis=0)

np.concatenate([arr1, arr2, arr3]).shape

(3, 256, 256)

# 1.5 Добавление и удаление элементов.

In [19]:
data = np.empty([1000, 28, 28])
arr1 = np.empty([50, 28, 28])
arr2 = np.empty([28, 28])

print(f'Размер data: {data.shape}')
print(f'Размер arr1: {arr1.shape}')
print(f'Размер arr2: {arr2.shape}')

Размер data: (1000, 28, 28)
Размер arr1: (50, 28, 28)
Размер arr2: (28, 28)


In [26]:
# Добавление элементов

new_data1 = np.append(data, arr1) # - одномерный массив
new_data2 = np.append(data, arr1, axis=0) # - многомерный, объединенрие по нулевой оси
new_data3 = np.append(arr1, arr1, axis=2) # - многомерный, объединенрие по второй оси
new_data4 = np.append(data, arr2[np.newaxis], axis=0) # - добавление одного элемента с предварительным добавлением оси

print(f'Размер new_data1: {new_data1.shape}')
print(f'Размер new_data2: {new_data2.shape}')
print(f'Размер new_data3: {new_data3.shape}')
print(f'Размер new_data4: {new_data4.shape}')

Размер new_data1: (823200,)
Размер new_data2: (1050, 28, 28)
Размер new_data3: (50, 28, 56)
Размер new_data4: (1001, 28, 28)


In [27]:
# Удаление элементов по индексу

print(new_data4.shape)

new_data4 = np.delete(new_data4, 1000, axis=0)

print(new_data4.shape)

(1001, 28, 28)
(1000, 28, 28)


In [28]:
# В программе созданы два массива с картинками 28 на 28 пикселей. 
# Массивы записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28), а массив arr_2 имеет размер (5, 28, 28). 
# К картинкам из arr_1 добавьте картинки из arr_2.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28])
arr_2 = np.empty([5, 28, 28])

new_arr = np.append(arr_1, arr_2, axis=0)

new_arr.shape

(15, 28, 28)

In [29]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28), 10 картинок 28 на 28 пикселей. 
# Массив arr_2 имеет размер (28, 28), содержит одну картинку. 
# К картинкам из arr_1 добавьте картинку arr_2.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28])
arr_2 = np.empty([28, 28])

new_arr = np.append(arr_1, arr_2[np.newaxis], axis=0)

new_arr.shape

(11, 28, 28)

In [31]:
# В программе созданы два массива и записаны в переменные arr_1 и arr_2. 
# Массив arr_1 имеет размер (10, 28, 28, 2), 10 картинок 28 на 28 пикселей с двумя цветовыми каналами G и B. 
# Массив arr_2 имеет размер (10, 28, 28, 1), 10 картинок 28 на 28 пикселей с одним цветовым каналом R. 
# Добавьте один массив к другому так, чтобы получить 10 картинок с тремя цветовыми каналами RGB.

# Результат запишите в переменную new_arr.

arr_1 = np.empty([10, 28, 28, 2])
arr_2 = np.empty([10, 28, 28, 1])

new_arr = np.append(arr_2, arr_1, axis=3) # - arr_2 + arr_1, потому что RGB (не GBR)

new_arr.shape

(10, 28, 28, 3)