In [5]:
import numpy as np

In [6]:
print(np.linspace(-5, 5, 10))

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [7]:
# a, b = map(int, input().split())
a, b = 2, 9
arr = np.array(list(i for i in range(a, b + 1) if i % 3 == 0))
print(arr)
arr = np.arange(a, b + 1)
arr = arr[arr % 3 == 0]
print(arr)

[3 6 9]
[3 6 9]


In [8]:
np.random.seed(32)
# n = int(input())
n = 6
arr = np.random.rand(n)
arr

array([0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ,
       0.81620514])

In [9]:
n = 3
arr = []
for i in range(0, n + 100): 
    if i > 1: 
        for j in range(2, i):
            if(i % j) == 0: 
                break 
        else:
            if len(arr) < n:
                arr.append(i)
print(arr)

[2, 3, 5]


In [16]:
n = 10
i = 2
arr = []
while len(arr) < n:
    for j in range(2, i):
        if(i % j) == 0: 
                break
    else:
         arr.append(i)
    i += 1
print(arr)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [21]:
a, b = map(float, input().split())

np.round(np.arange(-1*a, a+0.001, b), 1)

array([-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, -0. ,
        0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [22]:
b = 5
arr = np.linspace(0, np.pi, b)
arr

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [26]:
import numpy as np
arr=np.array([1, 2, '3', {'key1':66}])

print(arr.dtype)
print(arr.size)
print(arr.shape)

object
4
(4,)
