In [106]:
import pandas as pd
import numpy as np

# 2.2 Объект Series в Pandas и его создание

In [107]:
# создание объекта Series из списка
my_list = [1, 2, 3, 4, 5]
s = pd.Series(my_list)
print(s)

# создание объекта Series из массива NumPy
my_array = np.array([1, 2, 3, 4, 5])
s = pd.Series(my_array, list('zxcvb'))
print(s)

# создание объекта Series из словаря Python
my_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
s = pd.Series(my_dict)
print(s)

# создание объекта Series из списка кортежей
s = pd.Series([(1, 'a'), (2, 'b'), (3, 'c')])
print(s)

# создание объекта Series из скалярного значения
s = pd.Series(5, index=['a', 'b', 'c'])
print(s)


0    1
1    2
2    3
3    4
4    5
dtype: int64
z    1
x    2
c    3
v    4
b    5
dtype: int32
a    1
b    2
c    3
d    4
e    5
dtype: int64
0    (1, a)
1    (2, b)
2    (3, c)
dtype: object
a    5
b    5
c    5
dtype: int64


In [108]:
# создание объекта Series
s1 = pd.Series([1, 2, 3])

# создание нового объекта Series на основе существующего
s2 = pd.Series(s1)
print(s2)

0    1
1    2
2    3
dtype: int64


In [109]:
s = pd.Series([1, 2, 3], {1, 2, 3})
s = pd.Series([1, 2, 3], (1, 2, 3))
s = pd.Series([1, 2, 3], [1, 2, 3])
s

1    1
2    2
3    3
dtype: int64

In [110]:
print(__import__('pandas').Series(dict(zip('abc', [1, 4, 6, 2]))))

a    1
b    4
c    6
dtype: int64


In [111]:
arr = [1, 2, 3, 4, 5]

print(pd.Series(np.array(arr), [*'abcdf']))

a    1
b    2
c    3
d    4
f    5
dtype: int32


In [112]:
# a = tuple((i, j) for i, j in zip(list(map(str, input().split())), list(map(int, input().split()))))
a = tuple((i, j) for i, j in zip([1, 2, 3], list('abc')))
pd.Series(a)

0    (1, a)
1    (2, b)
2    (3, c)
dtype: object

In [113]:
# a = (zip(input().split(), input().split()))
a = (zip([1,2,3], [*'abc']))
pd.Series(a)

0    (1, a)
1    (2, b)
2    (3, c)
dtype: object

In [114]:
s = 'Prived Medved Kag Dela'
pd.Series(s.split(' '))

0    Prived
1    Medved
2       Kag
3      Dela
dtype: object

In [115]:
from string import ascii_lowercase

# data = [bool(i) for i in list(map(int, input().split()))]
data = [0, 1, 0, 0, 1]
data = [bool(i) for i in data]
pd.Series(data, list(ascii_lowercase[:len(data)]))

a    False
b     True
c    False
d    False
e     True
dtype: bool

In [116]:
# data = np.array(input().split()).astype(int)
data = np.array([0, 1, 0, 0, 1])
pd.Series(data == 1, index=list(ascii_lowercase)[:len(data)])

a    False
b     True
c    False
d    False
e     True
dtype: bool

In [117]:
pd.Series(['2022-01-01', '2022-01-02', '2022-01-03'])

0    2022-01-01
1    2022-01-02
2    2022-01-03
dtype: object

In [118]:
# n, m = (int(i) for i in input().split())
n, m = -5, 35
data = list(range(n, m + 1, 10))
ind = list(range(1, 2 * len(data), 2))
pd.Series(data, ind)

1    -5
3     5
5    15
7    25
9    35
dtype: int64

# 2.3 Атрибуты index и values объекта Series

In [119]:
# Создание объекта Series с пользовательскими метками
s = pd.Series(data=[10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

# Просмотр меток
print(s.index)

# Просмотр данных
print(s.values)

Index(['a', 'b', 'c', 'd'], dtype='object')
[10 20 30 40]


In [120]:
# Создание объекта Series с пользовательскими метками
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

# Выбор элементов по меткам
print(s['a'])
print(s[['a', 'c']])

10
a    10
c    30
dtype: int64


In [121]:
# Изменение элемента по метке
s['a'] = 50

# Просмотр измененных данных
print(s.values)

[50 20 30 40]


In [122]:
# Выполнение операции над элементами
s = s * 2

# Просмотр измененных данных
print(s.values)

[100  40  60  80]


In [123]:
# Создайте объект Series, содержащий первые 10 нечетных чисел, с метками - буквами латинского алфавита в верхнем регистре.
from string import ascii_uppercase
pd.Series(range(10), list(ascii_uppercase[:10])).head()

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [124]:
# Создайте объект Series, содержащий буквы латинского алфавита в нижнем регистре. Выведите на печать атрибуты index и values полученного объекта, каждый с новой строки.
data = pd.Series(list(ascii_lowercase))
print(data.index)
print(data.values)

RangeIndex(start=0, stop=26, step=1)
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [125]:
states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 
          'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa']
populations = [4903185, 731545, 7278717, 3017825, 39538223, 578713, 3605944, 986809, 21538187,
 10711908, 1455271, 1826156, 12671821, 6745354, 3179849]
data = pd.Series(populations, states)
# print(data[input()])
s = 'Florida'
print(data[s])

21538187


In [126]:
# print(data[input().split()])
s = ['Arizona', 'California',  'Florida',  'Hawaii']
print(data[s])

Arizona        7278717
California    39538223
Florida       21538187
Hawaii         1455271
dtype: int64


In [127]:
ind = ['2022-05-01', '2022-05-02', '2022-05-03']
data = [64, 73, 71]
variables = ['2022-05-01', '2022-05-03']

ser = pd.Series(data, ind)
print(ser[variables])

2022-05-01    64
2022-05-03    71
dtype: int64


In [128]:
ind = ['2022-05-01', '2022-05-02', '2022-05-03']
data = [64, 73, 71]
variables = ['2022-05-01', '2022-05-03']

ser = pd.Series(data, ind)
print(*ser[variables])

64 71


In [129]:
from datetime import date, timedelta
np.random.seed(33)
dates = list(map(str,[date(2019, 1, 4) + timedelta(days=i) for i in range(360)]))
temperatures = np.random.randint(-10, 35, len(dates))
dates = pd.to_datetime(dates)
ser = pd.Series(temperatures, dates) # приведение к типу datetime
n = 3 # номер месяца
print(ser[dates.month == n].head())

2019-03-01    23
2019-03-02     5
2019-03-03     4
2019-03-04     4
2019-03-05    18
dtype: int32


In [130]:
names = ['Иван', 'Олег', 'Татьяна', 'Марина', 'Алексей', 'Андрей']
scores = [65, 61, 83, 68, 69, 99]
request = ['Олег', 'Татьяна']
ser = pd.Series(scores, names)
print(*ser[request].values)

61 83


In [131]:
countries = ['Россия', 'США', 'Китай', 'Индия', 'Япония', 'Германия', 'Великобритания', 'Франция', 'Италия', 'Канада', 'Южная_Корея', 'Австралия']
populations = [144.5, 328.2, 1393.0, 1366.0, 126.5, 83.1, 66.7, 66.99, 60.4, 37.59, 51.78, 25.4]
n, m = 'Япония', 110
ser = pd.Series(populations, countries)
print(ser.head())
ser[n] = m
print(ser.head())

Россия     144.5
США        328.2
Китай     1393.0
Индия     1366.0
Япония     126.5
dtype: float64
Россия     144.5
США        328.2
Китай     1393.0
Индия     1366.0
Япония     110.0
dtype: float64


In [132]:
dates = ['2022-06-04', '2022-06-05', '2022-06-06', '2022-06-07', '2022-06-08', '2022-06-09', '2022-06-10']
temperatures = [68, 72, 75, 70, 68, 73, 79]
ser = pd.Series(temperatures, dates)

ind = ser.index

val = (ser.values - 32) * 5/9
ser = pd.Series(val, ind)
print(ser)

2022-06-04    20.000000
2022-06-05    22.222222
2022-06-06    23.888889
2022-06-07    21.111111
2022-06-08    20.000000
2022-06-09    22.777778
2022-06-10    26.111111
dtype: float64


In [133]:
ser = ser.apply(lambda x: int(x / (5/9) + 32))
print(ser)

2022-06-04    68
2022-06-05    72
2022-06-06    75
2022-06-07    70
2022-06-08    68
2022-06-09    73
2022-06-10    79
dtype: int64


In [134]:
ser = (ser - 32) * 5 / 9
print(ser)

2022-06-04    20.000000
2022-06-05    22.222222
2022-06-06    23.888889
2022-06-07    21.111111
2022-06-08    20.000000
2022-06-09    22.777778
2022-06-10    26.111111
dtype: float64


# 2.4 Атрибут dtype объекта Pandas

In [135]:
# создание серии со значениями с плавающей точкой
s = pd.Series([1, 2, 3, 4, 5], dtype='float')
print(s)

# создание серии с целочисленными значениями
s = pd.Series([1, 2, 3, 4, 5], dtype=int)
print(s)

# создание серии с датами
s = pd.Series(['2022-04-01', '2022-04-02', '2022-04-03'], dtype='datetime64[ns]')
print(s)

# создание серии с категориальными значениями
s = pd.Series(["dog", "cat", "dog", "fish", "cat"], dtype="category")
print(s)

# создание серии из списка, содержащего строковые значения
s = pd.Series(['apple', 'banana', 'cherry'])
print(s)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int32
0   2022-04-01
1   2022-04-02
2   2022-04-03
dtype: datetime64[ns]
0     dog
1     cat
2     dog
3    fish
4     cat
dtype: category
Categories (3, object): ['cat', 'dog', 'fish']
0     apple
1    banana
2    cherry
dtype: object


In [136]:
ser = pd.Series([True, False, True], index=list('xyz'), dtype='bool')
print(ser)
ser[:] = False
print(ser)

x     True
y    False
z     True
dtype: bool
x    False
y    False
z    False
dtype: bool


In [137]:
ser = pd.Series([10, 20, 30, 40], index=list('abcd'), dtype='float64')
print(ser)
ser *= 2
print(ser)
print(ser.mean())

a    10.0
b    20.0
c    30.0
d    40.0
dtype: float64
a    20.0
b    40.0
c    60.0
d    80.0
dtype: float64
50.0


# 2.5 Применение математических функций и операторов к объекту Series

In [138]:
# Функции из модуля math:
# math.sin(x) - возвращает синус x (x в радианах)
# math.cos(x) - возвращает косинус x (x в радианах)
# math.tan(x) - возвращает тангенс x (x в радианах)
# math.exp(x) - возвращает экспоненту x
# math.log(x) - возвращает натуральный логарифм x
# math.sqrt(x) - возвращает квадратный корень из x

# Функции из модуля numpy:
# numpy.abs(x) - возвращает абсолютное значение x
# numpy.round(x, n) - округляет x до n знаков после запятой
# numpy.floor(x) - округляет x вниз до ближайшего целого числа
# numpy.ceil(x) - округляет x вверх до ближайшего целого числа
# numpy.power(x, n) - возвращает x в степени n
# numpy.exp(x) - возвращает экспоненту x
# numpy.log(x) - возвращает натуральный логарифм x
# numpy.sqrt(x) - возвращает квадратный корень из x

In [139]:
s1 = pd.Series([1, 2, 3]) 
s2 = pd.Series([4, 5, 6]) 
s3 = s1 + s2 
print(s3)

0    5
1    7
2    9
dtype: int64


In [140]:
s1 = pd.Series([1, 2, 3]) 
s2 = pd.Series([4, 5, 6]) 
mask = s1 < s2 
print(mask)

0    True
1    True
2    True
dtype: bool


In [141]:
s1 = pd.Series([1, 2, 3]) 
s2 = pd.Series([4, 5, 6]) 
mask = (s1 < s2) & (s1 > 2)
print(mask)

0    False
1    False
2     True
dtype: bool


In [142]:
s1 = pd.Series([7, 2, 3]) 
s2 = pd.Series([4, 5, 6]) 
mask = s1 < s2 
print(mask) 

s3 = pd.Series([10, 20, 30]) 
s4 = s3[mask] 
print(s4) 

0    False
1     True
2     True
dtype: bool
1    20
2    30
dtype: int64


In [143]:
# создание pd.Series
s = pd.Series([0, 1, 2, 3])

# вычисление экспоненты и логарифма
exp_s = np.exp(s)
log_s = np.log(s)

# вывод результатов
print(exp_s)
print(log_s)

0     1.000000
1     2.718282
2     7.389056
3    20.085537
dtype: float64
0        -inf
1    0.000000
2    0.693147
3    1.098612
dtype: float64


c:\Users\kuche\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [144]:
s1 = pd.Series([1, 2, 3]) 
s2 = pd.Series([4, 5, 6]) 
mask = s1 > 2 
s3 = s1[mask] + s2[mask] 
print(s3)

2    9
dtype: int64


In [145]:
ser1 = pd.Series([1, 2, 3], dtype='int16')
ser2 = pd.Series([2, 4, 6], dtype='int16')
print(ser1+ser2)
print(ser1*ser2)

0    3
1    6
2    9
dtype: int16
0     2
1     8
2    18
dtype: int16


In [146]:
ser = pd.Series([1, 2, 3, 4, 5], index=list('abcde'))
print(ser[ser<3])

a    1
b    2
dtype: int64


In [147]:
ser = pd.Series([10, 20, 30])
ser = ser > 15
ser

0    False
1     True
2     True
dtype: bool

In [148]:
ser1 = pd.Series([1.0, 2.0, 3.0])
ser2 = np.sqrt(np.exp(ser1) - np.log(ser1)).round(2)
print(ser2)

0    1.65
1    2.59
2    4.36
dtype: float64


In [149]:
ser1 = pd.Series([1, 4, 5, 3, 7, 9, 8, 2], dtype='uint32')
print(ser1)
ser2 = ser1[(ser1 % 2) == 1]
print(ser2)

0    1
1    4
2    5
3    3
4    7
5    9
6    8
7    2
dtype: uint32
0    1
2    5
3    3
4    7
5    9
dtype: uint32


In [150]:
s = pd.Series(['cat', 'fish', 'can', 'able', 'call'], dtype='string')
char = 'c'
s[s.str.startswith(char)]

0     cat
2     can
4    call
dtype: string

In [151]:
ser = pd.Series(['2021-01-01', '2021-02-21', '2021-03-18', '2021-05-02', '2021-08-11', '2021-12-12'], dtype='datetime64[ns]')
print(ser)
print(ser[ser.between('2021-03-18', '2021-09-22', inclusive='neither')])

0   2021-01-01
1   2021-02-21
2   2021-03-18
3   2021-05-02
4   2021-08-11
5   2021-12-12
dtype: datetime64[ns]
3   2021-05-02
4   2021-08-11
dtype: datetime64[ns]


In [152]:
s = pd.Series(['абрек', 'аул', 'барнаул', 'кит', 'арнлк'], dtype='string')
print(s)
s2 = s[(s.str.startswith('a')) & (s.str.endswith('к'))]
print(s2)

0      абрек
1        аул
2    барнаул
3        кит
4      арнлк
dtype: string
Series([], dtype: string)


# 2.7 Атрибут name объекта Series