In [2]:
import re
# не трогайте этот код, он необходим для автоматической проверки
str_input = 'asdada ! asda, asd.'

# ваш код тут

str_input = re.sub(r'[,.!]', '', str_input).lower()
str_input

'asdada  asda asd'

In [5]:
import torch
import numpy as np

In [6]:
# Синтаксис PyTorch аналогичен синтаксису numpy

# torch.tensor() ==> numpy.array()

In [21]:
print(torch.tensor([2, 3]))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.int32))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32, requires_grad=True))

# print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32, device=torch.device('cuda:0')))


tensor([2, 3])
tensor([[2, 3],
        [4, 5]], dtype=torch.int32)
tensor([[2., 3.],
        [4., 5.]])
tensor([[2., 3.],
        [4., 5.]], requires_grad=True)


In [35]:
# Свойства и методы tensor

tensor = torch.tensor([[[2, 3], [4, 5]],
                       [[6, 7], [8, 9]]], 
                       dtype=torch.float32, 
                       requires_grad=True)

display(tensor)

print(tensor.dtype)

print(tensor.shape)

print(tensor.size())

print(tensor.ndim)

print(tensor[0, 0, 0])

print(type(tensor[0, 0, 0]))

print(tensor[0, 0, 0].item())

print(type(tensor[0, 0, 0].item()))

tensor([[[2., 3.],
         [4., 5.]],

        [[6., 7.],
         [8., 9.]]], requires_grad=True)

torch.float32
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
3
tensor(2., grad_fn=<SelectBackward0>)
<class 'torch.Tensor'>
2.0
<class 'float'>


In [40]:
# Создание массивов разного размера

tensor = torch.zeros([2, 3, 2])
print(tensor)
print(tensor.dtype)

tensor = torch.ones([2, 3, 2])
print(tensor)
print(tensor.dtype)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
torch.float32
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.float32


In [42]:
tensor = torch.zeros([2, 3])
print(tensor)


tensor = torch.zeros_like(tensor)
print(tensor)
print(tensor.dtype)

tensor = torch.full_like(tensor, 7)
print(tensor)
print(tensor.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[7., 7., 7.],
        [7., 7., 7.]])
torch.float32


In [43]:
torch.arange(2, 10, 0.5)

tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000,
        6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [44]:
torch.diag(torch.tensor([2, 5]))

tensor([[2, 0],
        [0, 5]])