In [66]:
import torch
import numpy as np

# 1 Знакомство с Pytorch

In [67]:
# Синтаксис PyTorch аналогичен синтаксису numpy

# torch.tensor() ==> numpy.array()

In [68]:
print(torch.tensor([2, 3]))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.int32))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32, requires_grad=True))

# print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32, device=torch.device('cuda:0')))


tensor([2, 3])
tensor([[2, 3],
        [4, 5]], dtype=torch.int32)
tensor([[2., 3.],
        [4., 5.]])
tensor([[2., 3.],
        [4., 5.]], requires_grad=True)


In [69]:
# Свойства и методы tensor

tensor = torch.tensor([[[2, 3], [4, 5]],
                       [[6, 7], [8, 9]]], 
                       dtype=torch.float32, 
                       requires_grad=True)

display(tensor)

print(tensor.dtype)

print(tensor.shape)

print(tensor.size())

print(tensor.ndim)

print(tensor[0, 0, 0])

print(type(tensor[0, 0, 0]))

print(tensor[0, 0, 0].item())

print(type(tensor[0, 0, 0].item()))

tensor([[[2., 3.],
         [4., 5.]],

        [[6., 7.],
         [8., 9.]]], requires_grad=True)

torch.float32
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
3
tensor(2., grad_fn=<SelectBackward0>)
<class 'torch.Tensor'>
2.0
<class 'float'>


In [70]:
# Создание массивов разного размера

tensor = torch.zeros([2, 3, 2])
print(tensor)
print(tensor.dtype)

tensor = torch.ones([2, 3, 2])
print(tensor)
print(tensor.dtype)

tensor = torch.full(size=[2, 3, 2], fill_value=7)
print(tensor)
print(tensor.dtype)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
torch.float32
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.float32
tensor([[[7, 7],
         [7, 7],
         [7, 7]],

        [[7, 7],
         [7, 7],
         [7, 7]]])
torch.int64


In [71]:
tensor = torch.zeros([2, 3])
print(tensor)


tensor = torch.zeros_like(tensor)
print(tensor)
print(tensor.dtype)

tensor = torch.full_like(tensor, 7)
print(tensor)
print(tensor.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[7., 7., 7.],
        [7., 7., 7.]])
torch.float32


In [72]:
torch.arange(2, 10, 0.5)

tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000,
        6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [73]:
print(torch.diag(torch.tensor([2, 5, 7])))

print(torch.eye(5))

print(torch.tril(torch.tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]])))

tensor([[2, 0, 0],
        [0, 5, 0],
        [0, 0, 7]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1, 0, 0],
        [2, 3, 0],
        [3, 4, 5]])


In [74]:
# Изменение размера тензора

tensor = torch.tensor([1, 2, 3, 4])
print(tensor)

tensor_1 = tensor.view(4, 1)
print(tensor_1)

tensor_2 = tensor.reshape([2, 2])
print(tensor_2)

tensor([1, 2, 3, 4])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2],
        [3, 4]])


In [75]:
# Добавление осей в тензор

print(tensor.shape)

tensor = torch.unsqueeze(tensor, 0)
print(tensor.shape)

torch.Size([4])
torch.Size([1, 4])


In [76]:
# Арифметические операции

tensor = torch.tensor([1, 2, 3, 4, 5])

print(tensor * 5)

print(tensor + torch.tensor([1, 2, 3, 4, 5]))

tensor([ 5, 10, 15, 20, 25])
tensor([ 2,  4,  6,  8, 10])


In [77]:
# Математические функции

tensor = torch.tensor([1, 2, 3, 4, 5, 6],
                      dtype=torch.float32)

print(sum(tensor))

print(torch.mean(tensor))

print(tensor.mean())

tensor(21.)
tensor(3.5000)
tensor(3.5000)


In [78]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6],
                      dtype=torch.float32)

tensor = tensor.view([2, 3])
print(tensor)

tensor_mean = tensor.mean(dim=1, keepdim=True)
print(tensor_mean)

tensor_mean = tensor.mean(dim=0, keepdim=True)
print(tensor_mean)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[2.],
        [5.]])
tensor([[2.5000, 3.5000, 4.5000]])


In [79]:
# CPU и GPU

print(torch.cpu.is_available())
print(torch.cuda.is_available()) 

True
False


In [80]:
tensor = torch.tensor([1., 2., 3.], requires_grad=True)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = tensor.to(device)

print(tensor.device)

cpu


In [81]:
# Добавление оси

tensor = torch.zeros((64, 28, 28))

new_tensor = tensor[:, None, :, :]

new_tensor.shape

torch.Size([64, 1, 28, 28])

In [82]:
# Сложение тензоров

tensor_1 = torch.tensor([1, 2, 3, 4, 5, 6])
tensor_2 = torch.tensor([1, 2, 3, 4, 5, 6])

print(tensor_1 + tensor_2)

print(tensor_1.add(tensor_2))

print(torch.add(tensor_1, tensor_2))

tensor([ 2,  4,  6,  8, 10, 12])
tensor([ 2,  4,  6,  8, 10, 12])
tensor([ 2,  4,  6,  8, 10, 12])


In [83]:
# Конкатенация тензоров

tensor_001 = torch.tensor([[1, 1], [2, 2]])
tensor_002 = torch.tensor([[3, 3], [4, 4]])

tensor_cat = torch.cat([tensor_001, tensor_002])

print(f"tensor_001.shape => {tensor_001.shape}")
print(tensor_001, end='\n\n')
print(f"tensor_002.shape => {tensor_002.shape}")
print(tensor_002, end='\n\n')

print('Объединение по нулевой оси')

print(f"tensor_cat.shape => {tensor_cat.shape}")
print(tensor_cat)

print('Объединение по первой оси')

tensor_001 = torch.tensor([[1, 1, 1], [2, 2, 2]])
tensor_002 = torch.tensor([[3, 3], [4, 4]])

tensor_cat = torch.cat([tensor_001, tensor_002], dim=1)

print(f"tensor_cat.shape => {tensor_cat.shape}")
print(tensor_cat)

tensor_001.shape => torch.Size([2, 2])
tensor([[1, 1],
        [2, 2]])

tensor_002.shape => torch.Size([2, 2])
tensor([[3, 3],
        [4, 4]])

Объединение по нулевой оси
tensor_cat.shape => torch.Size([4, 2])
tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])
Объединение по первой оси
tensor_cat.shape => torch.Size([2, 5])
tensor([[1, 1, 1, 3, 3],
        [2, 2, 2, 4, 4]])


In [84]:
# Изменение размера тензора

tensor = torch.zeros([2, 5])
print(f"Размер тензора до изменения размера => {tensor.shape}")

tensor = tensor.view([-1, 2])
print(f"Размер тензора после изменения размера => {tensor.shape}")


Размер тензора до изменения размера => torch.Size([2, 5])
Размер тензора после изменения размера => torch.Size([5, 2])


In [85]:
# Функция argmax()

tensor = torch.tensor([[2, 5],
                      [4, 1]])

print(torch.argmax(tensor, dim=1))

print(tensor.argmax(dim=1))

tensor([1, 0])
tensor([1, 0])


In [86]:
# Сравнение тензоров

tensor_001	=	torch.tensor([[1, 3], [2, 2]])
tensor_002	=	torch.tensor([[3, 3], [2, 2]])

tensor_equal = tensor_001 == tensor_002
print(tensor_equal)

tensor_all = torch.all(tensor_equal)
print(tensor_all)

tensor_any = torch.any(tensor_equal)
print(tensor_any)

tensor_equal = torch.equal(tensor_001, tensor_002)
print(tensor_equal)

tensor([[False,  True],
        [ True,  True]])
tensor(False)
tensor(True)
False


In [87]:
# Сравнение по осям

print('Сравнение по нулевой оси')
tensor_001	=	torch.tensor([[3, 3], [1, 1]])
tensor_002	=	torch.tensor([[3, 3], [2, 2]])

tensor_equal = tensor_001 == tensor_002
print(tensor_equal)

tensor_all = torch.all(tensor_equal, dim=0)
print(tensor_all)

print()

print('Сравнение по первой оси')
tensor_001	=	torch.tensor([[3, 3], [1, 1]])
tensor_002	=	torch.tensor([[3, 3], [2, 2]])

tensor_equal = tensor_001 == tensor_002
print(tensor_equal)

tensor_all = torch.all(tensor_equal, dim=1)
print(tensor_all)

Сравнение по нулевой оси
tensor([[ True,  True],
        [False, False]])
tensor([False, False])

Сравнение по первой оси
tensor([[ True,  True],
        [False, False]])
tensor([ True, False])


In [88]:
# Если нужно сохранить размерность тензора, то можно воспользоваться аргументом keepdim со значением True.

tensor_001 = torch.tensor([[3, 3], [1, 1]])
tensor_002 = torch.tensor([[3, 3], [2, 2]])

tensor_equal = tensor_001 == tensor_002
tensor_all = torch.all(tensor_equal, dim=1, keepdim=True)

print(tensor_001)
print(tensor_002, end='\n\n')

print(tensor_equal.shape)
print(tensor_equal, end='\n\n')

print(tensor_all.shape)
print(tensor_all)


tensor([[3, 3],
        [1, 1]])
tensor([[3, 3],
        [2, 2]])

torch.Size([2, 2])
tensor([[ True,  True],
        [False, False]])

torch.Size([2, 1])
tensor([[ True],
        [False]])


In [94]:
# Даны два тензора и записаны в переменные tensor_1 и tensor_2. 
# Тензор tensor_1 размером 64 на 20, тензор tensor_2 размером 64 на 30. 
# Сложите два тензора, чтобы получился тензор размером 64 на 50.

# Результат запишите в переменную new_tensor.

# Воспользуйтесь операцией конкатенация torch.cat().

tensor_1 = torch.ones([64, 20])
tensor_2 = torch.ones([64, 30])

new_tensor = torch.cat([tensor_1, tensor_2], dim=1)

new_tensor.shape


torch.Size([64, 50])