In [2]:
import torch
import numpy as np

# 1.3 Знакомство с Pytorch

In [3]:
# Синтаксис PyTorch аналогичен синтаксису numpy

# torch.tensor() ==> numpy.array()

In [4]:
print(torch.tensor([2, 3]))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.int32))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32))

print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32, requires_grad=True))

# print(torch.tensor([[2, 3], [4, 5]], dtype=torch.float32, device=torch.device('cuda:0')))


tensor([2, 3])
tensor([[2, 3],
        [4, 5]], dtype=torch.int32)
tensor([[2., 3.],
        [4., 5.]])
tensor([[2., 3.],
        [4., 5.]], requires_grad=True)


In [5]:
# Свойства и методы tensor

tensor = torch.tensor([[[2, 3], [4, 5]],
                       [[6, 7], [8, 9]]], 
                       dtype=torch.float32, 
                       requires_grad=True)

display(tensor)

print(tensor.dtype)

print(tensor.shape)

print(tensor.size())

print(tensor.ndim)

print(tensor[0, 0, 0])

print(type(tensor[0, 0, 0]))

print(tensor[0, 0, 0].item())

print(type(tensor[0, 0, 0].item()))

tensor([[[2., 3.],
         [4., 5.]],

        [[6., 7.],
         [8., 9.]]], requires_grad=True)

torch.float32
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
3
tensor(2., grad_fn=<SelectBackward0>)
<class 'torch.Tensor'>
2.0
<class 'float'>


In [6]:
# Создание массивов разного размера

tensor = torch.zeros([2, 3, 2])
print(tensor)
print(tensor.dtype)

tensor = torch.ones([2, 3, 2])
print(tensor)
print(tensor.dtype)

tensor = torch.full(size=[2, 3, 2], fill_value=7)
print(tensor)
print(tensor.dtype)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
torch.float32
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.float32
tensor([[[7, 7],
         [7, 7],
         [7, 7]],

        [[7, 7],
         [7, 7],
         [7, 7]]])
torch.int64


In [7]:
tensor = torch.zeros([2, 3])
print(tensor)


tensor = torch.zeros_like(tensor)
print(tensor)
print(tensor.dtype)

tensor = torch.full_like(tensor, 7)
print(tensor)
print(tensor.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[7., 7., 7.],
        [7., 7., 7.]])
torch.float32


In [8]:
torch.arange(2, 10, 0.5)

tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000,
        6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [9]:
print(torch.diag(torch.tensor([2, 5, 7])))

print(torch.eye(5))

print(torch.tril(torch.tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]])))

tensor([[2, 0, 0],
        [0, 5, 0],
        [0, 0, 7]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1, 0, 0],
        [2, 3, 0],
        [3, 4, 5]])


In [10]:
# Изменение размера тензора

tensor = torch.tensor([1, 2, 3, 4])
print(tensor)

tensor_1 = tensor.view(4, 1)
print(tensor_1)

tensor_2 = tensor.reshape([2, 2])
print(tensor_2)

tensor([1, 2, 3, 4])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2],
        [3, 4]])


In [11]:
# Добавление осей в тензор

print(tensor.shape)

tensor = torch.unsqueeze(tensor, 0)
print(tensor.shape)

torch.Size([4])
torch.Size([1, 4])


In [12]:
# Арифметические операции

tensor = torch.tensor([1, 2, 3, 4, 5])

print(tensor * 5)

print(tensor + torch.tensor([1, 2, 3, 4, 5]))

tensor([ 5, 10, 15, 20, 25])


tensor([ 2,  4,  6,  8, 10])


In [13]:
# Математические функции

tensor = torch.tensor([1, 2, 3, 4, 5, 6],
                      dtype=torch.float32)

print(sum(tensor))

print(torch.mean(tensor))

print(tensor.mean())

tensor(21.)
tensor(3.5000)
tensor(3.5000)


In [14]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6],
                      dtype=torch.float32)

tensor = tensor.view([2, 3])
print(tensor)

tensor_mean = tensor.mean(dim=1, keepdim=True)
print(tensor_mean)

tensor_mean = tensor.mean(dim=0, keepdim=True)
print(tensor_mean)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[2.],
        [5.]])
tensor([[2.5000, 3.5000, 4.5000]])


In [15]:
# CPU и GPU

print(torch.cpu.is_available())
print(torch.cuda.is_available()) 

True
False


In [17]:
tensor = torch.tensor([1., 2., 3.], requires_grad=True)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = tensor.to(device)

print(tensor.device)

cpu


In [23]:
# Добавление оси

tensor = torch.zeros((64, 28, 28))

new_tensor = tensor[:, None, :, :]

new_tensor.shape

torch.Size([64, 1, 28, 28])